### PR TITLE
Fix Issue 413 according to comments

### PR DESCRIPTION
**Pull request by jellypuno**
Signed-off-by: jellypuno <jessielaine.punongbayan@broadcom.com>

### CODE REVIEW

**Comment by Colin-Stone** [comment]
This may help https://code.visualstudio.com/api/extension-guides/command

**Comment by jellypuno** [comment]
> This wont work. You have added the datasetProvider as an optional field
> `export async function openPS(node: ZoweNode, previewMember: boolean, datasetProvider?: DatasetTree)`
> In your code you will get an undefined error thrown when opening from favorites
> `await datasetProvider.refreshElement(node); await datasetProvider.refresh();`
> 
> Your solution may be around the command
> `vscode.commands.registerCommand("zowe.ZoweNode.openPS", (node) => openPS(node, true));`
> This needs the datasetProvider added. Maybe then it's possible to call the command with the node

I tested it. It is not having an error except for refreshJobsServer() that's why I passed the provider there: `vscode.commands.registerCommand("zowe.refreshJobsServer", async (node) => refreshJobsServer(node, jobsProvider));`

I could still add the providers as you said but this code already works.

**Comment by Colin-Stone** [comment]
image

**Comment by jellypuno** [comment]
@Colin-Stone I find it weird that I did not experience this during my testing. I was in the impression that the values for the provider is propagated during initialization so I don't need to pass it anymore. At least that is what I saw. But anyways, thank you for testing it and capturing this error.

**Comment by jellypuno** [comment]
> That's sorted it. Thanks Jelly. No idea why code coverage is down, I thinkit may be a glitch with codecov itself rather than a reduction in testing

Yeah... I don't know as well. 😕  Thank you for your reviewing. 👍

**Pull request merged**
