### PR TITLE
fix(v3): SonarCloud medium and high-priority bugs

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This PR ports the changes from #2714 to the `next` branch.

## Release Notes

Milestone:

Changelog: No changelog

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by zFernand0 — DISMISSED** [review]
These changes are very similar (if not identical) to #2714 

I know we can't see the `next` branch just yet, but the fact that there are no new bugs is a good sign 😋 
- https://sonarcloud.io/project/issues?resolved=false&pullRequest=2716&id=zowe_vscode-extension-for-zowe

Thanks for porting over the changes 
LGTM! 😋

**Review by adam-wolfe — COMMENTED** [review]
Should this PR include the changes made to `packages/zowe-explorer/__tests__/__integration__/uss/ussNodeActions.integration.test.ts` in #2714?

**Comment by traeok** [comment]
> Should this PR include the changes made to `packages/zowe-explorer/__tests__/__integration__/uss/ussNodeActions.integration.test.ts` in #2714?

Thanks for spotting this @adam-wolfe , I forgot that that change was part of another commit that was not cherry-picked. I've added the change for that file and resolved any remaining lint errors in `next`. Should be good now 👍

**Comment by traeok** [comment]
Same situation with Codecov as in #2714 😅  Codecov is having a bad time with these changes for some reason

image

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Pull request merged**
