### PR TITLE
Integration test improvements

### PR DESCRIPTION
**Pull request by katelynienaber**
## Proposed changes

The integration tests have recently been driving me nuts. So, I made the following improvements:
- Functions called in file `systemTestEnv.ts` handle promises properly now. So if one node fails to be created/deleted, you don't have to re-run the script.
- Scripts `create-env.ts` and `clean-env.ts` will now run automatically. So you can just select `Zowe Explorer Integration Tests (Mocha)` from the dropdown, and the nodes will be created and deleted for you, before and after the integration tests are run.
- There is now a new script in the ZE `package.json`: `createDemoNodes`. This script will create some basic data sets, members, and USS folders/files which can be used in our demos.

## Release Notes

Milestone: Backlog

Changelog: Improved integration tests for greater efficiency.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

This PR should be merged AFTER PR #1421 (because I made changes to file `systemTestEnv.ts` in that PR as well)

### CODE REVIEW

**Comment by katelynienaber** [comment]
`yarn audit` command is failing because of @zowe/cli depndency on package tar...

**Comment by JillieBeanSim** [comment]
@katelynienaber add the tar version to the top level package.json to fix the audit issue like this
```
 "resolutions": {
    "**/lodash": "^4.17.21",
    "**/postcss": "^8.2.10",
    "**/tar": "^6.1.2"
  },
```

**Comment by katelynienaber** [comment]
@JillieBeanSim done, thank you!

**Comment by JillieBeanSim** [comment]
@katelynienaber did you run `yarn` after adding the update to the package.json? I am seeing a change in the yarn.lock when I run it locally.

**Comment by JillieBeanSim** [comment]
This is awesome, I am getting 2 failures on tests I fixed in the past so we could look back to see how that was fixed.
image

**Comment by JillieBeanSim** [comment]
some how/some where this *.EXT.ALLOC.LIKE data set is being created.  I don't see where this is happening and though.  It is causing the count to be off for the save tests
image

**Review by JillieBeanSim — DISMISSED** [review]
Love this, still a little buggy sometimes if tests crash but could be addressed later to run a full clean with any/all data sets included even the ones we should be deleting in the tests themselves to call and wipe the environment clean.

I think we should close the other PR https://github.com/zowe/vscode-extension-for-zowe/pull/1421 in favor of this one as all tests are fixed plus the extra stuff in this PR.  Could attach the related issue https://github.com/zowe/vscode-extension-for-zowe/issues/1354 to this PR.

merging master in fixed what I was seeing with the yarn.lock file

**Comment by katelynienaber** [comment]
@JillieBeanSim I think that is a good idea, I have linked that issue to this PR, and closed the other PR.

When you say "crashes in the middle of tests", could you tell me how to cause this to happen? Maybe I could work on this in innovation week...in any case I would like to open another issue for that.

**Review by JillieBeanSim — APPROVED** [review]
LGTM! Integration tests are running great and they all pass. Thanks @katelynienaber

**Review by zFernand0 — APPROVED** [review]
LGTM!
Wondering if there should be a `cleanupDemoNodes` function in the `scripts/systemTestEnv.ts` file 😋 
Minor details though.

**Comment by jellypuno** [comment]
> LGTM!
> Wondering if there should be a `cleanupDemoNodes` function in the `scripts/systemTestEnv.ts` file 😋
> Minor details though.

We can add that as a future enhancement. I'll merge this PR.

**Pull request merged**
