### PR TITLE
Fix issue 648 - Context value of undefined on new member save

### PR DESCRIPTION
**Pull request by katelynienaber**
Resolves issue #648.

I changed variable label to uppercase on line 1739 so that the labels will match
in the search starting on line 1765.

Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Please update with a meaningful title and link to related issue

**Comment by Colin-Stone** [comment]
This one can be merged into master @zFernand0  is it worth us keeping the branch temporarily and decide if we want a v1.4.2 at some point or shall we just focus on getting v1.5.0 out?.

**Comment by zFernand0** [comment]
> This one can be merged into master @zFernand0 is it worth us keeping the branch temporarily and decide if we want a v1.4.2 at some point or shall we just focus on getting v1.5.0 out?.

We can discuss more tomorrow (during refinement) but given all the merge conflicts, with a lot of PRs, it might be worth focusing more on 1.5.0 instead of 1.4.2 (unless we know of some customer that absolutely needs a fix before Monday or something similar.

**Comment by zFernand0** [comment]
LGTM!
Two questions:
1. Could you resolve the merge conflicts? (I think the function was moved to some utils file) 😋 
2. Can we capture this in a unit test?

**Comment by katelynienaber** [comment]
> LGTM!
> Two questions:
> 
> 1. Could you resolve the merge conflicts? (I think the function was moved to some utils file) 😋
> 2. Can we capture this in a unit test? (I'm just asking since it's labeled as a bug)

Done :3 Added a small unit test for this within saveFile

**Pull request merged**
