### PR TITLE
Issue #472

### PR DESCRIPTION
**Pull request by stepanzharychevbroadcom**

### CODE REVIEW

**Comment by Colin-Stone** [comment]
The issue is not part of an agreed milestone so I have to prioritize reviewing those for now

**Comment by jellypuno** [comment]
For easier reference #472

**Comment by stepanzharychevbroadcom** [comment]
Changes related to necessary fixes are moved to https://github.com/zowe/vscode-extension-for-zowe/pull/600.

**Comment by stepanzharychevbroadcom** [comment]
Closing it before we figure out about priorities.

**Pull request closed without merging**
