### PR TITLE
fix(FTP): One active FTP connection per operation; remove temp. files once finished

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This PR fixes a couple of issues with the FTP extension (found while working on FileSystemProvider):
- `FTPClient.connectWithArguments` was called twice before the first connection was closed in `putContents`. The fix closes this connection before opening a new one.
  - This seems like it might affect the behavior in #2499, but I haven't been able to reproduce the issue without the fix
- Temporary files created by `getContentsTag` were not removed after use, causing orphaned temp. files with remote content to persist in the user's temp folder.

## Release Notes

Milestone: 2.12.0 (or 2.13.0, I know there's a lot going out for this release)

Changelog:

- Fixed an issue with FTP where temp. files for e-tag comparison were not deleted after use.
- Fixed an issue with FTP where another connection attempt was made, even though one was already active.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Comment by tiantn** [comment]
Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!
截屏2023-10-31 15 38 42

**Comment by zFernand0** [comment]
> Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you! 截屏2023-10-31 15 38 42

Hey @tiantn,
Do we expect falsy values from the plugin?

**Comment by traeok** [comment]
> Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!

Hi @tiantn, no problem! I'm hesitant to invert this behavior, as `connection != null` will determine whether the connection object is valid before trying to call its functions.

Unless there is a need to check for other "falsy values," I think we can keep this check as-is 🙂

**Comment by tiantn** [comment]
> > Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!
> 
> Hi @tiantn, no problem! I'm hesitant to change the current check, as `connection != null` will determine whether the connection object is valid before trying to call its functions.
> 
> Unless there is a need to check for other "falsy values," I think we can keep this check as-is 🙂

Hi @traeok , @zFernand0 , we consider the `undefined` case so want to change it.

**Comment by zFernand0** [comment]
> > > Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!
> > 
> > 
> > Hi @tiantn, no problem! I'm hesitant to change the current check, as `connection != null` will determine whether the connection object is valid before trying to call its functions.
> > Unless there is a need to check for other "falsy values," I think we can keep this check as-is 🙂
> 
> Hi @traeok , @zFernand0 , we consider the `undefined` case so want to change it.

Hey @tiantn,

The `!=` operator should be equivalent to `connection !== undefined && connection !== null`.

Changing it to `!connection` will result in an error where:
- `null.close` throws `Uncaught TypeError: Cannot read properties of null (reading 'close')`
- `undefined.close` throws ``Uncaught TypeError: Cannot read properties of undefined (reading 'close')`

I believe you meant `if(connection) { connection.close() } `.
However that can lead to problems for truthy values where you might see this error: 
 - `Uncaught TypeError: connection.close is not a function`

**Comment by tiantn** [comment]
> > > > Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!
> > > 
> > > 
> > > Hi @tiantn, no problem! I'm hesitant to change the current check, as `connection != null` will determine whether the connection object is valid before trying to call its functions.
> > > Unless there is a need to check for other "falsy values," I think we can keep this check as-is 🙂
> > 
> > 
> > Hi @traeok , @zFernand0 , we consider the `undefined` case so want to change it.
> 
> Hey @tiantn,
> 
> The `!=` operator should be equivalent to `connection !== undefined && connection !== null`.
> 
> Changing it to `!connection` will result in an error where:
> 
>     * `null.close` throws `Uncaught TypeError: Cannot read properties of null (reading 'close')`
> 
>     * `undefined.close` throws ``Uncaught TypeError: Cannot read properties of undefined (reading 'close')`
> 
> 
> I believe you meant `if(connection) { connection.close() } `. However that can lead to problems for truthy values where you might see this error:
> 
>     * `Uncaught TypeError: connection.close is not a function`
> 
> 
> In this case, a more thorough check could be `connection != null && connection instanceof T` 😋

Hi @zFernand0 , @traeok , sorry, I am wrong. I mean`if(connection)` or`if (connection !== null && connection !== undefined)`.

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Comment by zFernand0** [comment]
> > > > > Hi @traeok, thank you for the fix. Could you also update the following line in red frame to ` if (!connection) {`? Thank you!
> > > > 
> > > > 
> > > > Hi @tiantn, no problem! I'm hesitant to change the current check, as `connection != null` will determine whether the connection object is valid before trying to call its functions.
> > > > Unless there is a need to check for other "falsy values," I think we can keep this check as-is 🙂
> > > 
> > > 
> > > Hi @traeok , @zFernand0 , we consider the `undefined` case so want to change it.
> > 
> > 
> > Hey @tiantn,
> > The `!=` operator should be equivalent to `connection !== undefined && connection !== null`.
> > Changing it to `!connection` will result in an error where:
> > ```
> > * `null.close` throws `Uncaught TypeError: Cannot read properties of null (reading 'close')`
> > 
> > * `undefined.close` throws ``Uncaught TypeError: Cannot read properties of undefined (reading 'close')`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe you meant `if(connection) { connection.close() } `. However that can lead to problems for truthy values where you might see this error:
> > ```
> > * `Uncaught TypeError: connection.close is not a function`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this case, a more thorough check could be `connection != null && connection instanceof T` 😋
> 
> Hi @zFernand0 , @traeok , sorry, I am wrong. I mean`if(connection)` or`if (connection !== null && connection !== undefined)`.

I do believe that `connection != null` and `connection !== null && connection !== undefined` functionally behave the same way. 
The only reasons I see for changing it is because:
- Code Quality Tools:
  - If there is a syntactical analysis tool that complains about this
    - SonarCLoud doesn't seem to fail the quality check.
- Strict Mode Considerations:
  - If you're working in strict mode (`'use strict';`), using `!=` may throw a TypeError.
    - We haven't had any Javascript `strict;` users requesting that we avoid these.

If we want to have a more robust check, I believe that checking for `instanceof T` might be more impactful than switching from `1=` to `!==`.

That said, I'm ok if we decide to leave it as-is, or change it in the future.

If someone feels strongly one way or the other, I'm happy to approve a follow-up PR with these changes :yum:

**Review by zFernand0 — APPROVED** [review]
I believe I've expressed my point of view on the `!= null` vs. `!== null || !== undefined`  debate. Approving for now.

LGTM! :yum:

**Review by tiantn — APPROVED** [review]
Thank you @traeok and @zFernand0 !

**Comment by JillieBeanSim** [comment]
Hey @tiantn @traeok @zFernand0 & @t1m0thyj, I see this has the approvals but before I merged I wanted to ask if we would like this out with the patch release 2.12.1?  If so we will want to rebase to maintenance or the [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2540) for merging all 2.12.0 changes into maintenance

**Pull request merged**
