### PR TITLE
Migrate to Webpack v5

### LINKED ISSUE #2214: Replace Webpack 4 with newer bundler
Microsoft has upgraded away from Webpack 4 in their VSCE samples so we are falling a bit behind now 🙂 https://github.com/microsoft/vscode-extension-samples/blob/main/webpack-sample/package.json

For the v3 release, we could investigate alternatives like Webpack 6 or Turbopack (used in the K8s repo).

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Fixes #2214 

Webpack v5 migration docs: https://webpack.js.org/migrate/5/

Migrated our outdated webpack v4 to the newest release of webpack v5, this has introduced some really good things for our repo, as well as things that we should all know about when reviewing this PR:

## Code Splitting and Minimization

Code splitting using vendor strategy was used for optimizing load times on our project, see here for reference on how that was achieved: https://blog.jakoblind.no/code-split-vendors-with-webpack-for-faster-load-speed/

Minimization of our code was also integrated into our bundle for Zowe Explorer, which now greatly reduces the `extension.js` file size using Webpack's built in minimzer using Terser and ESBuild: https://webpack.js.org/plugins/terser-webpack-plugin/

## Bundling for VS Code for web and VS Code Desktop Versions

VS Code has a recommended way of setting up initially the `webpack.config.js`, this repo now follows (mostly) those recommendations. A thing to note is that our repo currently uses `fs` which are node.js API's that can't be used in the web and cause issues with bundling. We didn't notice this before with v4 since we were already bundling as `node` instead of VS Code's recommended `webworker` target to support both platforms in one bundle. See more on this here: https://code.visualstudio.com/api/working-with-extensions/bundling-extension

## Future things to address

Webpack no longer resolves polyfills automatically like in v4, which means if we switch the target to `webworker` we need to add those polyfill resolutions through fallbacks: https://webpack.js.org/configuration/resolve/#resolvefallback

Even if the work above is done, we need to discuss the approach to handle `fs` being used across Zowe Explorer and Zowe Explorer API in order to bundle for web and support that too (if we choose to support it).

## Release Notes

Milestone: v3 pre-releases

Changelog: Migrated to Webpack v5

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
the changes built and packaged without errors but I get this when trying to launch the debugger and that fails
Screenshot 2024-01-26 at 4 19 09 PM

**Comment by t1m0thyj** [comment]
> the changes built and packaged without errors but I get this when trying to launch the debugger and that fails Screenshot 2024-01-26 at 4 19 09 PM

This happened to me recently too but I don't think its a problem with this PR - if you switched Node versions with `nvm` recently, might need to reinstall pnpm globally (`npm install -g pnpm`)?

**Review by JillieBeanSim — DISMISSED** [review]
remembering to reinstall pnpm after each node update will have to be something I remember to do now lol don't even remember updating node since last time testing next. Thanks @t1m0thyj 
LGTM! thanks for the updates @rudyflores

**Review by traeok — CHANGES_REQUESTED** [review]
Thanks for all your work on this @rudyflores! I do have a small request:

I ran into an issue that isn't directly related to this PR, but I realized I was unable to run the watch script after downgrading my Node version to v18.

On line 24 in `.vscode/tasks.json`, the type is set to "process" instead of "shell" - because of this, the task fails on Windows with OS error 193 because it tries to execute the Linux/macOS binary (which is not a valid Win32 application).

Can you please update this to "shell"? This should resolve the watch script failures on Windows.

**Comment by rudyflores** [comment]
@traeok good catch! Should be all fixed now :)

**Review by traeok — DISMISSED** [review]
LGTM, thanks for the tech. currency and for quickly resolving the `watch` task 😁

**Comment by traeok** [comment]
I noticed after approving that the changelog headers have the `next` snapshot as the header instead of "Recent Changes" - I think that will resolve the failing changelog stage

**Review by traeok — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @rudyflores for this update

**Pull request merged**
