### PR TITLE
Issue:1013 Add beforeMemberName to textbox for pasteMember()

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Copy & Paste PDS member should prefill filename field
https://github.com/zowe/vscode-extension-for-zowe/issues/1013

ZE-copy-paste-prefilled-textbox

## Release Notes

Milestone: 1.13.0

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by katelynienaber — DISMISSED** [review]
Hey @JillieBeanSim, for some reason I am getting this error:

image

When trying to copy/paste a member from ISPPROF...maybe a permissions issue? I tried it with a binary and a text member, paste seems to work when pasting something _into_ ISPPROF or between 2 of my own data sets, but not copying _out_ of ISPPROF and pasting somewhere else.

If it is a permissions thing, is there a way to show a different error here? Since the problem probably is from MF and not from the `zowe.pasteMember` function.

**Comment by JillieBeanSim** [comment]
> Hey @JillieBeanSim, for some reason I am getting this error:
> 
> image
> 
> When trying to copy/paste a member from ISPPROF...maybe a permissions issue? I tried it with a binary and a text member, paste seems to work when pasting something _into_ ISPPROF or between 2 of my own data sets, but not copying _out_ of ISPPROF and pasting somewhere else.
> 
> If it is a permissions thing, is there a way to show a different error here? Since the problem probably is from MF and not from the `zowe.pasteMember` function.

@katelynienaber this error popping up is pre-existing and seems to be the go to pop up for anything that goes wrong with copy/paste.  I think it is out of scope for this PR and a new issue should be created to deal specifically with error handling for copy/paste as this PR was to only add the member name into the textbox.  For the error handling of copy/paste some investigation will need to be done so we don't catch the error and output what we think it should be since the same error pops up for multiple issues whether it is a permissions error an issue with copying from one data set type to a different data set type and so on.

**Comment by JillieBeanSim** [comment]
I created the Error Handling issue for copy/paste https://github.com/zowe/vscode-extension-for-zowe/issues/1209

**Comment by lauren-li** [comment]
Since z/OSMF allows copying of a sequential data set into a PDS as a member, should we also implement the beforeMemberName prefill in that case as well? PDS member to PDS member is working great with the prefilled value, but I don't get any prefilled value for sequential data set -> PDS member:

ze-copyPS

**Comment by JillieBeanSim** [comment]
> Since z/OSMF allows copying of a sequential data set into a PDS as a member, should we also implement the beforeMemberName prefill in that case as well? PDS member to PDS member is working great with the prefilled value, but I don't get any prefilled value for sequential data set -> PDS member:
> 
> ze-copyPS

with a sequential data set there is no before member name

**Review by katelynienaber — APPROVED** [review]
Looks great to me!

**Review by lauren-li — APPROVED** [review]
> with a sequential data set there is no before member name

@JillieBeanSim That's a very good point. I retract the suggestion I made in my previous comment.

This PR looks good to me! All unit and expected integration tests are passing, and the functionality for prefilling the destination member name field with the name of the copied data set member appears to be working well.

Thanks @JillieBeanSim for this UX improvement!

**Pull request merged**
