### PR TITLE
fix(ProfileUtils.ts): remove redundant isTheia() function in favor of global variable

### LINKED ISSUE #2412: Remove `isTheia` function from ProfileUtils
> I believe the `isTheia` function may be duplicate code, since we already have `globals.ISTHEIA` that can be checked to determine whether we're running in a Theia environment.
> Would it make sense to remove the `isTheia` function from this file and replace it with `globals.ISTHEIA`?

_Originally posted by @t1m0thyj in https://github.com/zowe/vscode-extension-for-zowe/pull/2410#discussion_r1283256379_

### PR DESCRIPTION
**Pull request by ArvindParekh**
## Proposed changes
Fixes #2412 

- Removed the isTheia() function, since we already have globals.ISTHEIA that can be checked to determine whether we're running in a Theia environment.
- Replaced the occurences of isTheia() with globals.ISTHEIA

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — DISMISSED** [review]
LGTM, thanks @ArvindParekh!

**Review by traeok — COMMENTED** [review]
Hi @ArvindParekh,

I realized shortly after approving that some unit tests are failing - looks like its related to some Jest mocks for the removed `ProfileUtils.isTheia` function. Once those are resolved I will approve 👍

**Comment by traeok** [comment]
SonarCloud code duplication resurfaced from old tests, no new duplication to worry about 😋

**Review by zFernand0 — APPROVED** [review]
Changes make sense to me
LGTM! 😋 

Thanks @ArvindParekh and @traeok  😋

**Comment by ArvindParekh** [comment]
Perfect :)
Thanks for the support @traeok 👍🏻

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
