### PR TITLE
PR #1120 linked issue: Always allow prompting

### PR DESCRIPTION
**Pull request by katelynienaber**
## Proposed changes

In PR #1120, we noticed that users won't be prompted to enter their credentials, if a profile was previously marked `invalid`.

This should cause prompting to occur if the user is missing enough credentials in their session/combined profiles, no matter whether the profile was validated before or not.

I've tested this with the contents of PRs #1120 & #1150 and found no huge showstoppers.

## Release Notes
Milestone: 1.12.1
Changelog: Updated credential prompting to occur even if profile has been marked "invalid".

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

Would prefer this to be merged before #1120 & #1150 (not absolutely necessary but that's how I tested them)

### CODE REVIEW

**Comment by lauren-li** [comment]
@katelynienaber When I try to run a search with just a regular profile that has username/password already, I am getting new prompts for username and password. At least the fields are pre-filled, but it adds at least 3 extra keypresses/clicks to the UX flow. Did you encounter this while testing, as well?:
ze-prompt

**Comment by katelynienaber** [comment]
> @katelynienaber When I try to run a search with just a regular profile that has username/password already, I am getting new prompts for username and password. At least the fields are pre-filled, but it adds at least 3 extra keypresses/clicks to the UX flow. Did you encounter this while testing, as well?:
> ze-prompt

@lauren-li I am not getting this issue. Could you tell me what exactly you have in your base/service profiles?

I tried it with validation on & off, both ways did not get extra prompts.

**Comment by lauren-li** [comment]
> @lauren-li I am not getting this issue. Could you tell me what exactly you have in your base/service profiles?
> 
> I tried it with validation on & off, both ways did not get extra prompts.

@katelynienaber I have no base profile. The service profile I used in my gif has the following information filled in: host, port, user, password, and rejectUnauthorized. (No SCS plugin.) Validation is on.

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
@katelynienaber I am getting the same thing as @lauren-li for profiles that already have creds with it asking me if I want to save, and an error pops up for profiles that don't have creds but the prompting for that profile does work and lets me query
ZE-cred-prompting

**Comment by katelynienaber** [comment]
@jellypuno would you be able to test this? I am not getting this error, chatted with @lauren-li and we are pretty sure everything is the same with our setups...

**Comment by jellypuno** [comment]
> @jellypuno would you be able to test this? I am not getting this error, chatted with @lauren-li and we are pretty sure everything is the same with our setups...

@katelynienaber I'll test it after my meetings

**Comment by lauren-li** [comment]
After pulling in the latest changes (which was basically just the `master` branch merge with the ppf file) and rerunning `yarn`, somehow the issue I was seeing before is no longer happening. I'm certain I ran `yarn` the first time I tested this, so I'm not sure how the issue is suddenly gone, but I'm not complaining.

**Comment by lauren-li** [comment]
@katelynienaber So far this seems to work alright, but I have a question: Is this PR also supposed to get rid of the credentials error? The error no longer prevents me from getting prompted for and entering credentials, but it would be new for existing users who are accustomed to being able to create and use credential-less profiles in Zowe Explorer without any error messages.

ze-pwError

**Comment by katelynienaber** [comment]
> @katelynienaber Just a reminder to change your base branch for this PR from `master` to `v1.12.x`. 🙂
> 
> So far this seems to work alright, but I have a question: Is this PR also supposed to get rid of the credentials error? The error no longer prevents me from getting prompted for and entering credentials, but it would be new for existing users who are accustomed to being able to create and use credential-less profiles in Zowe Explorer without any error messages.

@lauren-li This should be fixed, I did some rearranging to get the error to go away. Also rebased off v1.12.x

**Review by JillieBeanSim — COMMENTED** [review]
I am still seeing the issue with prompting if creds are already in profile, after looking at the code in Profiles.checkCurrentProfile() and testing a change I believe these lines can be taken out since the prompt doesn't worry about host and port, and after testing all profiles work (creds included, creds as empty string, and creds as undefined) https://github.com/zowe/vscode-extension-for-zowe/blob/62442606b95dc048d2c829b78d0ee7e93029facb/packages/zowe-explorer/src/Profiles.ts#L91. once that is taken out line 87 is no longer needed as well.  Also lines 74-76 can be removed as lines 105-107 are using diff variables now.
This GIF is with my changes
ZE-prompt
In this GIF the 1st profile has creds, the 2nd has empty string for user/pass, and the final (as name says) has no user/pass field in yaml

**Comment by JillieBeanSim** [comment]
also this PR is still showing that you would like to merge into `master` instead of `v1.12.x`

**Comment by lauren-li** [comment]
> also this PR is still showing that you would like to merge into master instead of v1.12.x

@katelynienaber If you click "Edit" in the upper right, the PR should let you change `master` to `v1.12.x` here:

Screen Shot 2021-02-05 at 8 39 30 AM

**Comment by JillieBeanSim** [comment]
I put a PR in for the changes requested to this branch https://github.com/zowe/vscode-extension-for-zowe/pull/1184

**Comment by katelynienaber** [comment]
@JillieBeanSim @lauren-li Hey, I thinkk I have gotten to your comments :)

Billie I checked that thing I mentioned in the call and it should be covered in the [duplicate prompting fix](https://github.com/zowe/vscode-extension-for-zowe/pull/1150).

**Review by JillieBeanSim — APPROVED** [review]
Thanks @katelynienaber for doing this work!  Everything works great and I love that ZE is now handling profiles with creds, with creds as empty string (which will soon be a thing of the past), and undefined cred fields in yamls to coincide with how Zowe CLI is handling the profile creation now with all fields being optional.  So excited for this to be merged in!!! All expected tests and checks are passing for me too.

**Review by lauren-li — APPROVED** [review]
This looks good to me now! All unit and expected integration tests are passing. I am able to query my credentialed profiles without any additional prompts, and I get appropriate prompts for username and password when trying to use credential-less profiles (both with and without empty-string username and password fields).

Thank you @katelynienaber for your hard work on this PR! Thanks as well to @JillieBeanSim for the supporting PR!

**Pull request merged**
