### PR TITLE
updated RNs (1.8.0)

### PR DESCRIPTION
**Pull request by IgorCATech**
Signed-off-by: Igor Kazmyr <43951184+IgorCATech@users.noreply.github.com>

## Proposed changes

Update the ZE release notes as 1.8.0 has been released

## Release Notes

Milestone: 1.8

Changelog: 

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by IgorCATech** [comment]
We have some Jenkins issues, @zdmullen @zFernand0 https://wash.zowe.org:8443/blue/organizations/jenkins/zowe-cli-vscode-extension/detail/PR-976/2/pipeline

**Comment by IgorCATech** [comment]
@zFernand0 Just a reminder to approve this PR :)

**Comment by zFernand0** [comment]
If people have conflicts with `package-lock.json`, it should be fine to remove it and do an `npm install` again (which will add it back).

**Comment by IgorCATech** [comment]
Good to know! Will do so next time if need be

**Pull request merged**
