### PR TITLE
View and manage jobs

### PR DESCRIPTION
**Pull request by crshnburn**
Adds a new set of views which shows the current jobs that match the specified owner and prefix and then view the spool contents for the jobs. Users can send a modify or stop command to a job as well as deleting a job from the system all using the Zowe CLI.

Signed-off-by: Andrew Smithson <smithson@uk.ibm.com>

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Hi Andy. I'm considering if we should converge into one taxonomy like this: 
```
Zowe
|
| ----Favorites
|
| ---- MyProfile 1
		|
		| ---- Datasets
		|		|
		|		| ---- MYUSER.TEST.JCL
		|		|	:	:
		|		| ---- MYUSER.PROD.JCL
						|
						| ---- COMPARE
						| ---- COPY
		|
		| ---- USS Files
		|		|
		|		| ---- /u/myuser
		|				|
		|				| ---- file1.txt
		|
		| ---- Jobs
				|
				| ---- AJOB1(INPUT)
				| ---- AJOB2(ACTIVE)
				| ---- TSU1(ABEND S222)
```

Rather than having separate sections, we would be grouping under profiles with separate sections for Jobs, datasets and uss. Bouncing this idea around to see what people think makes most sense.

**Comment by crshnburn** [comment]
@Colin-Stone That looks like a good layout, and would remove a small annoyance I was finding switching constantly between the two side bar layouts.

**Comment by ChrisBoehmCA** [comment]
Could you merge with master please and resolve the merge conflicts?

**Comment by crshnburn** [comment]
@ChrisBoehmCA Have rebased on master

**Comment by ChrisBoehmCA** [comment]
Thanks. I'm not sure if I did something wrong, but I'm getting this on startup: 

[Zowe.vscode-extension-for-zowe]: Menu item references a command `refresh-all` which is not defined in the 'commands' section.

[Zowe.vscode-extension-for-zowe]: Menu item references a command `add-session` which is not defined in the 'commands' section.

**Comment by crshnburn** [comment]
Apologies, those errors were masked by a problem in my development workspace. Have corrected the names now so it should work as intended.

**Pull request merged**
