### PR TITLE
Allow refresh for dataset member names

### PR DESCRIPTION
**Pull request by rudyflores**
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>

## Proposed changes
Adding a right-click action to refresh data sets to retrieve new list of members from the mainframe

refresh-pds

## Release Notes

Milestone: Release v1.16.0
Changelog: Refresh feature for data set member names in a profile.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]

**Comment by JillieBeanSim** [comment]
Thanks @rudyflores for your work on this! This PR looks good to me and all expected tests and checks are passing.

**Comment by jellypuno** [comment]
@tomofbroadcom Kindly review this PR. Do you think the word `Refresh` in the context menu is okay?

**Comment by katelynienaber** [comment]
@jellypuno @tomofbroadcom Maybe we could call the "main refresh" on the top bar, "Refresh Profiles"

And this would be "Refresh Data Set"

Or something just a thought

**Comment by lauren-li** [comment]
> @jellypuno @tomofbroadcom Maybe we could call the "main refresh" on the top bar, "Refresh Profiles"
> 
> And this would be "Refresh Data Set"
> 
> Or something just a thought

@rudyflores @katelynienaber @jellypuno @tomofbroadcom 

I like "Refresh Data Set" for this command's label.

The "main refresh" on the top bar is currently labeled "Refresh Data Sets View", as it not only refreshes profiles, but also refreshes the expand/collapse state of the data sets.

**Comment by katelynienaber** [comment]
> > @jellypuno @tomofbroadcom Maybe we could call the "main refresh" on the top bar, "Refresh Profiles"
> > And this would be "Refresh Data Set"
> > Or something just a thought
> 
> @rudyflores @katelynienaber @jellypuno @tomofbroadcom
> 
> I like "Refresh Data Set" for this command's label.
> 
> The "main refresh" on the top bar is currently labeled "Refresh Data Sets View", as it not only refreshes profiles, but also refreshes the expand/collapse state of the data sets.

Could we make the main refresh "Refresh View" since it is available on each view? Or is it currently "Refresh Data Sets/USS/Jobs" view, where the name changes depending on which view you're refreshing? That's fine too, it's more accurate. I'm just worried people might be confused because the name is very similar to this other refresh option in the context menu.

**Comment by lauren-li** [comment]
> > > @jellypuno @tomofbroadcom Maybe we could call the "main refresh" on the top bar, "Refresh Profiles"
> > > And this would be "Refresh Data Set"
> > > Or something just a thought
> > 
> > 
> > @rudyflores @katelynienaber @jellypuno @tomofbroadcom
> > I like "Refresh Data Set" for this command's label.
> > The "main refresh" on the top bar is currently labeled "Refresh Data Sets View", as it not only refreshes profiles, but also refreshes the expand/collapse state of the data sets.
> 
> Could we make the main refresh "Refresh View" since it is available on each view?
> 
> Or is it currently "Refresh Data Sets/USS/Jobs View", where the name changes depending on which view you're refreshing? That's fine too, it's more accurate. I'm just worried people might be confused because the name is very similar to this other refresh option in the context menu.

@katelynienaber Yes, the "main refresh" on the top bar is currently labeled "Refresh Data Sets/USS/Jobs View", where the name changes depending on which view you're refreshing. The view specification is important, since these commands can also be triggered from the Command Palette, and each of these main refreshes only refreshes its own view, not all 3 views.

**Comment by tomofbroadcom** [comment]
Currently we have similar needs in 1-2 other extensions. So let me think about it.

It sounds good to have a rule for the label "Refresh [what]". At this moment the plus button says "Add Profile to Data Sets View", but under a profile are data sets. So what is really being refreshed and why?

A: I changed my mainframe password in a profile, so I need to refresh all profiles to be able to work with data sets again?
B: I think that the content of data sets may have changed since I loaded them an hour ago, so I need to refresh all data sets?

And a second thing: How does it work with that main refresh? Does it go to MF as 1 request for the whole ZE? Just asking because of the possibility of locking your account immediately.

@katelynienaber Is the "View" an understandable name, or it's only in VSCode? I wonder how is this called in other IDEs or tools. E.g. panel, section, folder... 

T.

**Comment by phaumer** [comment]
I agree, @tomofbroadcom's analysis is spot on except that there are two sub-cases for (B): (B.1) the list of member names is updates (e.g. a member was added or renamed) and (B.2) the content of a member is changed. This PR is not about (B.2), but we need to name things so there is no confusion about it. 

IMHO, the top-level icon is not a refresh at all as it collapses all trees. I propose to rename it to "Reload Profiles" then it is clear that it will pick up the changed passwords. 

For the second perhaps we need to make sure the context menu only appears for a PDS in the first place and rename it to "Update member list" or "Refresh member names" as for sequential data sets the user is probably looking for the existing "Pull from Mainframe" to actually refresh the contents.

**Comment by lauren-li** [comment]
Thanks @tomofbroadcom for your insights! As @phaumer mentioned, this PR is focusing on adding support for use case `B.1` (the list of member names is updated (e.g. a member was added, renamed, deleted)) rather than `B.2`.

> A: I changed my mainframe password in a profile, so I need to refresh all profiles to be able to work with data sets again?

You do not need to manually refresh anything for a profile update (such as a profile password change) to take effect. This is done automatically when the profile update is made.

> B: I think that the content of data sets may have changed since I loaded them an hour ago, so I need to refresh all data sets?

This PR adds support for this use case by adding the command to refresh the member list for a specific PDS.

> And a second thing: How does it work with that main refresh? Does it go to MF as 1 request for the whole ZE? Just asking because of the possibility of locking your account immediately.

The top-level (or "main") refresh for the view  actually makes no calls to the mainframe. It is purely a local refresh of the view in VS Code, and includes things like resetting profile validation statuses and (for Data Sets View) the expand/collapse states of data sets. Because it has effects on both profiles and data sets in the UI, I prefer the current label of "Refresh Data Sets View" over "Reload profiles", until there is some additional development work done to clarify/separate exactly what this button is refreshing/loading.

Regarding @phaumer's comment below:
> For the second perhaps we need to make sure the context menu only appears for a PDS in the first place and rename it to "Update member list" or "Refresh member names" as for sequential data sets the user is probably looking for the existing "Pull from Mainframe" to actually refresh the contents.

In my testing of this PR, I only see the Refresh Data Set context menu item appearing for PDS's (and not PS's). However, I would be fine with renaming the label to "Refresh member list".

**Review by lauren-li — APPROVED** [review]
I think this PR looks good! All unit and expected integration tests are passing. I only see the new "Refresh Data Set" command appearing for PDS's, and it behaves as expected.

If we end up wanting to relabel "Refresh Data Set" to something like "Refresh member list", I can re-approve this PR.

**Review by JillieBeanSim — APPROVED** [review]
LGTM thanks @rudyflores for your work on this item.  All expected tests and checks are passing and functionality works great.

**Comment by jellypuno** [comment]
Hi everyone, It seems like we need to discuss the labels more. I'm okay to merge this PR but I will open a discussion so we can agree on the right label for refresh.

**Pull request merged**
