### PR TITLE
Fix Theia input box breakage and update Theia tests to pass

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

updated broken Theia test and added workaround for Theia input box issues, created a new file `ui-views` to house the workaround in the `UIViews.inputBox()` method.  would eventually like to move all UI related methods to be housed in this file like status bar, notification, etc. 

also added an update for failing windows 12 audit

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
down to 5 failing theia tests from 16, 4 are timeouts and 1 no such element.  will continue to look into these.  I also have failing unit tests from my changes added.
image

**Comment by JillieBeanSim** [comment]
not seeing any pop up messages in theia 1.19.0

**Comment by JillieBeanSim** [comment]
eclipse-theia/theia issues:
1. [VS Code pop up notifications not showing in Theia 1.19.0](https://github.com/eclipse-theia/theia/issues/10453) - Fixed and will be released 11/25/2021 :tada:

**Review by jellypuno — APPROVED** [review]
looks good to me!

**Review by crawr — APPROVED** [review]
Happy to approve this PR. It ran perfectly for me locally and the workflow made sense when I watched it in headless mode.
Thanks @JillieBeanSim !

**Pull request merged**
