### PR TITLE
Fix for issue #396: Cannot show DS attributes for PS files in Favorites

### PR DESCRIPTION
**Pull request by katelynienaber**
Small edit to function `showDSAttributes`.

Signed-off-by: katelynienaber <katelyn.nienaber@broadcom.com>

### CODE REVIEW

**Comment by katelynienaber** [comment]
> 👍
> Could you revert back the package-lock file?

Should be in latest commit P:

Sorry I will get the hang of this soon...

**Comment by zFernand0** [comment]
No problem at all!
We are all learning 😸

**Comment by katelynienaber** [comment]
Thanks for your help !!

**Comment by katelynienaber** [comment]
> Looks good to me!

Is there something else I should do with this/the other pull request? I can't merge anything myself.

**Comment by zFernand0** [comment]
The only thing I can think of is that , in order to publish a 1.0.2 this fix will have to be ported to the `v1.0.x` branch.

**Pull request merged**
