### PR TITLE
Solve migration of v1 configuration issues

### PR DESCRIPTION
**Pull request by rudyflores**
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>

## Release Notes

Milestone: v2.6.1

Changelog: Fixed issue with standardization of old v1 settings in Zowe Explorer during activation

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
The edge case seems to have been a lot worse that what I was originally thinking 😋 
Not much was migrated (all history, favorites, sessions, ...)
it was basically a completely new set of settings 😋 

LGTM! 😋 

Note: I noticed quite a few errors in the debug console, but nothing that prevents the extension from working as expected.
I still get the following pop-up, and the extension works as expected after a reload.
image

Here are the error details:
```
TypeError: Cannot read properties of undefined (reading 'split')

---

Partial Stack trace: 
	at Function.setDirectValue (/root/gh/zowe/vscode-extension-for-zowe/packages/zowe-explorer/out/src/extension.js:193479:38)
        ...
	at module.exports../src/utils/SettingsConfig.ts.__awaiter (/root/gh/zowe/vscode-extension-for-zowe/packages/zowe-explorer/out/src/extension.js:193455:12)
        ...
	at Function.standardizeGlobalSettings (/root/gh/zowe/vscode-extension-for-zowe/packages/zowe-explorer/out/src/extension.js:193521:16)
        ...
	at Function.standardizeSettings (/root/gh/zowe/vscode-extension-for-zowe/packages/zowe-explorer/out/src/extension.js:193483:16)
```

**Review by traeok — APPROVED** [review]
LGTM! Thanks @rudyflores 

I also noticed the debug error that Fernando mentioned - I think if we do a check if `newSetting != null` this will solve the `split` error coming from `setDirectValue`.

**Comment by rudyflores** [comment]
@zFernand0 @traeok I'm pretty sure this issue must be related to `globals.ts`'s dictionary with the settings names having undefined values on its keys (not sure why since these are static values hard coded). My guess it might be related to the several map errors showing in the debug console which might be related to the VS Code issue I linked in the previous version of this PR which I closed

**Review by traeok — APPROVED** [review]

**Comment by zFernand0** [comment]
> I'm pretty sure this issue must be related to `globals.ts`'s dictionary with the settings names having undefined values on its keys (not sure why since these are static values hard coded). My guess it might be related to the several map errors showing in the debug console which might be related to the VS Code issue I linked in the previous version of this PR which I closed

I completely missed this comment: https://github.com/zowe/vscode-extension-for-zowe/pull/2118#issuecomment-1423092235

Thank you! 🙏

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
