### PR TITLE
Make sure the error is thrown and reported

### PR DESCRIPTION
**Pull request by Colin-Stone**
Signed-off-by: Colin Stone <30794003+Colin-Stone@users.noreply.github.com>
The error needs to be rethrown to be reported.

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Code coverage is still appearing a little wacky. The junit tests coverage is actually a little better as I have added one new line which is covered by testing.

**Comment by zFernand0** [comment]
If we look at the [history of the `extension.ts`](https://codecov.io/gh/zowe/vscode-extension-for-zowe/branch/master/history/src/extension.ts?before=f65b20bcfc62a590a39c4082ea3a651f7da6833a) file it would seem that codecov is reporting a different number of lines tracked on the file fluctuating between 814 and 1017. (See proof below)

Should we submit an issue to @codecov?

[`073dbff`](https://codecov.io/gh/zowe/vscode-extension-for-zowe/src/073dbffbdf4c4b78f0254d1663c91875524fd0f3/src/extension.ts)
image

image


[`f65b20b`](https://codecov.io/gh/zowe/vscode-extension-for-zowe/src/f65b20bcfc62a590a39c4082ea3a651f7da6833a/src/extension.ts)
image

image

**Comment by Colin-Stone** [comment]
> 
> Should we submit an issue to @codecov?
> 


Thanks for the review. Are we seeing similar codecov issues with cli?. I was going to ask if we need to create an example for them but I think they can see this so yes probably worth raising an issue

**Comment by zFernand0** [comment]
Possibly related issue on codecov-batch: https://github.com/codecov/codecov-bash/issues/83
Similar issue on another project: https://github.com/zephyrproject-rtos/zephyr/pull/13608

**Pull request merged**
