### PR TITLE
VSC Compare function, not working with Favorites from Zowe Explorer

### PR DESCRIPTION
**Pull request by SanthoshiBoyina**
## Proposed changes

The feature of Visual Studio Code to compare 2 files, if the file on the mainframe has changed in the meantime, doesn't work if you open a Member under Favorites. It overrides the file automatically.  In this bug fix, we are able to trigger Compare function when ETAGs are mismatched.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
Is this for 2.12.0? @JillieBeanSim @SanthoshiBoyina

**Comment by JillieBeanSim** [comment]
> Is this for 2.12.0? @JillieBeanSim @SanthoshiBoyina

I am not opposed to it being included if the tests are fixed and the coverage is good in time, not seeing the coverage report yet with failing tests

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
I am seeing the diff editor open then when trying to save that I get the pop up to compare, I would assume one or the other happen but not both and the second right behind the first encounter.

**Review by traeok — COMMENTED** [review]
Thanks for working on this bug fix @SanthoshiBoyina! 

I'm running into the same situation as @JillieBeanSim - the side-by-side diff appears, but the dialog with Compare/Overwrite does not. However, this occurs for non-favorited nodes as well. I think this is because calls to `willForceUpload` (in `src/shared/utils.ts`) were removed with a previous PR, and this function was responsible for showing the dialog:

```ts
Gui.infoMessage(localize("saveFile.info.confirmUpload", "Would you like to overwrite the remote file?"), {
        items: [localize("saveFile.overwriteConfirmation.yes", "Yes"), localize("saveFile.overwriteConfirmation.no", "No")],
    })
```
_(lines 284-286 in the mentioned file)_

I'm wondering if we still want to use this `willForceUpload` function somewhere? As a quick solution, if we add this dialog to the `compareFileContent` function in `src/shared/utils.ts`, or if we show the dialog before calling `compareFileContent`, it should fix the issue.

**Comment by JillieBeanSim** [comment]
I don't think we should be forceUploading anything unless the decision came from user.

**Comment by traeok** [comment]
> I don't think we should be forceUploading anything unless the decision came from user.

@JillieBeanSim I agree. My comment was mostly pointing out that the dialog we used to show before the diff is no longer there. We used to call a similar `willForceUpload` function (mentioned above) that contained a similar dialog, but this call was removed at some point in the past and now we do not show a dialog at all when a conflict occurs. This is a regression introduced in a previous release, since we used to show a dialog, but it is not a result of the work on this PR. This could always be added to the repo as a separate issue for a future PR to solve.

**Comment by JillieBeanSim** [comment]
ok, if we had a regression maybe the popup can be added/moved to the shared.utils.compareFileContent() [method](https://github.com/zowe/vscode-extension-for-zowe/blob/464d7128ab890df5aa16ad20a45ea782f68201af/packages/zowe-explorer/src/shared/utils.ts#L362).  this will cut down on introducing duplicate code to bring it back in other cases and fix the duplication here in this PR

**Comment by SanthoshiBoyina** [comment]
> I am seeing the diff editor open then when trying to save that I get the pop up to compare, I would assume one or the other happen but not both and the second right behind the first encounter.

VS Code has a built-in mechanism to show a notification when you try to save a dirty file that has been changed outside of VS Code or by another program
save-conflict
In order not to make this built-in vs code notification pop up, In the setting we need to configure `files.saveConflictResolution` to `overwriteFileOnDisk` option from the default `askUser` option.

**Comment by traeok** [comment]
> > I am seeing the diff editor open then when trying to save that I get the pop up to compare, I would assume one or the other happen but not both and the second right behind the first encounter.
> 
> VS Code has a built-in mechanism to show a notification when you try to save a dirty file that has been changed outside of VS Code or by another program save-conflict In order not to make this built-in vs code notification pop up, In the setting we need to configure `files.saveConflictResolution` to `overwriteFileOnDisk` option from the default `askUser` option.

@SanthoshiBoyina Currently, PDS members and USS files are being written to temp files, so VS Code has no way of checking whether the document has a different e-tag than the mainframe. It calculates an e-tag for the temp. file on disk, but we do not use that e-tag when trying to upload file contents. Until we switch to something like a FileSystemProvider (#2207), we have to temporarily save the on-disk file, and then check with the mainframe to see if we have to do conflict resolution on our own. If there is a conflict, we un-save the file and then present a similar dialog.

**Comment by rudyflores** [comment]
Seems like the issue here with the compare editor not showing is because the `node` being passed into `compareFileContent` is a directory, can see that the error that shows in the debug console when trying to click on `Compare` mentions that a directory was entered too, this happens right when `node.getUSSDocumentFilePath()` is called in line `377`

**Pull request closed without merging**
