### PR TITLE
Open recent member keyboard shortcut (NOT including USS files)

### PR DESCRIPTION
**Pull request by katelynienaber**
This does not work for USS files, I will start working on that soon.

Signed-off-by: katelynienaber <katelyn.nienaber@broadcom.com>

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Have you branched against your own repo rather than against zowe here?. I would expect to see a button available that would allow your branch to be updated to the latest version of master. Without being up to date we can't really review

**Comment by katelynienaber** [comment]
Hello, is there no other way to update it than to move my code manually to
a branch off master? Where should the update button be?

It is a branch of my personal fork of Zowe. I got advice from Alex to do it
from Zowe (official branch) for all future pull requests. Was hoping I
would not have to move my code manually from this particular branch...

Thanks,

*Katelyn Nienaber*
Software Engineer | Mainframe Division
*CA Technologies, A Broadcom Company*
*Phone: *+420 226 207 737 ext. 7737

CA CZ, s.r.o. | V Parku 2316/12 Chodov | Praha 4, 148 00 Czech Republic
Katelyn.Nienaber@broadcom.com <Milada.Kohlerova@broadcom.com> | broadcom.com

Identification No. 25694073, registered in the Commercial Register
maintained by the Municipal Court in Prague in Section C, Insert No. 61808

**Comment by Colin-Stone** [comment]
I don't know. Maybe it has something to do with with not being a direct descendant. For example in another PR I see this...
image
So I suspect that one is okay because it has a direct relationship. Hence a button is available to do it automatically. As yours is a fork and then a branch I think it's too far away from the original.

**Comment by katelynienaber** [comment]
> I don't know. Maybe it has something to do with with not being a direct descendant. For example in another PR I see this...
> image
> So I suspect that one is okay because it has a direct relationship. Hence a button is available to do it automatically. As yours is a fork and then a branch I think it's too far away from the original.

I can see this button...maybe you can't see it because it would be updating my fork instead of a branch off master?

In any case I will make a branch off master tomorrow and move my edits there. I've put recentMemberPrompt into the dataset tree provider and everything seems to be working, so that's something at least :V

**Comment by zFernand0** [comment]
@jackjia-ibm @MarkAckert, can you think of a reason why new members of the team (i.e. CLI and VSCode-Team) are not able to push branches directly to the repo?

It seems that @katelynienaber and @stepanzharychevbroadcom  are both part of the teams below:
https://github.com/orgs/zowe/teams/vscode-team
https://github.com/orgs/zowe/teams/cli

**Comment by Colin-Stone** [comment]
@katelynienaber If you have the Update button and the text says merge the content of master into this barnch as in the image you should be able to pull the latest updates from master into your fork/branch and that way ring yourself up to date. Please also note that your build failed so check out the details why.

**Comment by Colin-Stone** [comment]
> @jackjia-ibm @MarkAckert, can you think of a reason why new members of the team (i.e. CLI and VSCode-Team) are not able to push branches directly to the repo?
> 
> It seems that @katelynienaber and @stepanzharychevbroadcom are both part of the teams below:
> https://github.com/orgs/zowe/teams/vscode-team
> https://github.com/orgs/zowe/teams/cli

I think it's my error as Katelyn described

>
> I can see this button...maybe you can't see it because it would be updating my fork instead of a 
> branch off master?
>

When I've been reviewing PR's that need merging, rather than requesting the developer does it, I usually kick it off myself. In the case where the branch is not public this isn't possible.

**Comment by katelynienaber** [comment]
Ok I am closing this PR and creating a new one from the _emulate_file_picker_172_ branch of Zowe.

**Pull request closed without merging**
