### PR TITLE
(Doc) Update Zowe Explorer 1.13.1 RNs

### PR DESCRIPTION
**Pull request by IgorCATech**
Signed-off-by: Igor Kazmyr <igor.kazmyr@broadcom.com>

## Proposed changes

A release notes update for Zowe Explorer 1.13.1. Changes are made to the ZE ReadMe and Changelog.

## Release Notes

Milestone: 1.13.1

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by katelynienaber — DISMISSED** [review]
LFTM (Looks Fine To Me) 😄

**Comment by jellypuno** [comment]
@IgorCATech There's a markdown problem in the theia build. Can you please check it?

$ markdownlint CHANGELOG.md README.md
CHANGELOG.md: 4: MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Above] [Context: "## `1.13.1`"]

**Comment by IgorCATech** [comment]
@jellypuno We have one remaining failing check "ze-build (12.x, macos-latest)". I was trying to run the `yarn install --frozen-lockfile` command as it was suggested in the log but I ended up getting an error, which looks like this: 
```
error C:\..\..\vscode-extension-for-zowe\node_modules\geckodriver: Command failed.
Exit code: 1
```
Not sure how to proceed here

**Comment by jellypuno** [comment]
@IgorCATech I change the base to 1.13.x

**Review by jellypuno — APPROVED** [review]

**Review by katelynienaber — APPROVED** [review]
SSFTM (still seems fine to me)

**Pull request merged**
