### PR TITLE
Migrate/Recall regression of icon and right click options update

### PR DESCRIPTION
**Pull request by likhithanimma1**
## Proposed changes

Solves #2755 
Fixed issue of migrate/recall icons and right-click options now update instantly upon selection, eliminating the need to reload VSCode

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by t1m0thyj — APPROVED** [review]
Can't really test this PR since I don't have access to a system that supports the `hmigrate` command, but changes LGTM - thanks @likhithanimma1!

**Review by zFernand0 — APPROVED** [review]
I'm kind of on the same boat here where it's a bit complicated to get a system to test the `hmigrate` functionality. 😅 

However, the changes do make sense to me 🥳 

LGTM! 😋

**Review by traeok — DISMISSED** [review]
LGTM, thanks @likhithanimma1! 🙂

**Comment by zFernand0** [comment]
Hey @rudyflores, @SanthoshiBoyina, and/or @JillieBeanSim,
when you get a chance, could you test the functionality before merging?

**Review by traeok — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @likhithanimma1 for the fix!

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
Sorry, functionally the changes work great.  I see the Theia tests are failing due to the changes.  Once those are addressed I think this will be good to merge

they just need updated for the new passed parameter
Screenshot 2024-03-11 at 9 18 27 AM

**Review by zFernand0 — APPROVED** [review]
🥳

**Review by JillieBeanSim — APPROVED** [review]

**Pull request merged**
