### PR TITLE
Issue921 validation information

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Alert user to validation of profiles
https://github.com/zowe/vscode-extension-for-zowe/issues/921

User will be notified that the profile is being validated during validation

## Release Notes

Milestone:
1.7.x or 1.8

Changelog: 
Alert user to validation of profiles

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by phaumer** [comment]
@zFernand0 @dkelosky as this is a breaking bug I recommend that we should actually merge this into the v1.7.x branch and publish it as a fix as we are getting reports from users who cannot save on USS anymore.

**Comment by jellypuno** [comment]
For codecov/patch, the test is not covering lines 918 and 919. Can you check why?

image

**Comment by JillieBeanSim** [comment]
> looks great! I'm thinking if it is possible to add a timeout? I have system that is not responding and the error message is there for more than 1 minute. I have to reload it.

One thing I could do is make it cancellable, where the Notification has a cancel button that will cancel the validation
image

image

**Comment by lauren-li** [comment]
@JillieBeanSim I like the "Cancel" button idea! :O

**Comment by jellypuno** [comment]
@JillieBeanSim Cancel button would be great!

@zFernand0 Maybe we should open a new issue to apply this progress bar with cancel button everywhere. Make it into a separate function? What do you think?

**Comment by zFernand0** [comment]
A new issue will be nice. That way we don't forget to apply it everywhere. But thanks Billie for adding it :yum:

**Comment by JillieBeanSim** [comment]
> A new issue will be nice. That way we don't forget to apply it everywhere. But thanks Billie for adding it 😋

@jellypuno @zFernand0 I have this set so if the `Cancel` is clicked the profile will be unverified vs inactive. Is that ok with you?

**Comment by jellypuno** [comment]
> > A new issue will be nice. That way we don't forget to apply it everywhere. But thanks Billie for adding it 😋
> 
> @jellypuno @zFernand0 I have this set so if the `Cancel` is clicked the profile will be unverified vs inactive. Is that ok with you?

@JillieBeanSim Yes that is fine with me. Thank you for adding this! :)

**Pull request merged**
