### PR TITLE
USS Favorites

### PR DESCRIPTION
**Pull request by rodney-wilson**
Add basic favorite functionality for USS explorer:
- Add files and directories as favorites
- Remove files and directories from favorites
- Expand favorited directories and open favorited files
- Sanitize search input starting with more than one slash
- Unit tests for the added functionalities

Related issues:
- #37 (Introduce Favorites functionality to USS extension)
- zowe/zowe-cli#297 (VSCode USS File extension - Favorites)

### CODE REVIEW

**Comment by ChrisBoehmCA** [comment]
Hi, 

Please follow the instructions on the DCO status check link (https://github.com/zowe/vscode-extension-for-zowe/pull/87/checks?check_run_id=134963940) to sign off your commit. We require all commits to be signed off. Sorry for the inconvenience.

**Comment by rodney-wilson** [comment]
Thanks @ChrisBoehmCA for letting us know. We have resolved the `signoff` issue. 

We made sure to `signoff` each of our individual commits while working on this feature. However, when we squashed our commits in our fork via the web UI, we were not given an option to `signoff`. Going forward, we will avoid squashing our commits to prevent this issue.

**Comment by lauren-li** [comment]
Colin, thanks for reviewing this and pointing out the failing integration test! We also get the same integration test failing with the same error on our end, and are currently looking into it.

**Comment by lauren-li** [comment]
Addressed the failing integration test mentioned above.

**Pull request merged**
