### PR TITLE
Fixed MVS Delete issues and not being able to delete in Theia/Che at all

### PR DESCRIPTION
**Pull request by phaumer**
## Proposed changes

See details in this issue: https://github.com/zowe/vscode-extension-for-zowe/issues/1477
and this PR: https://github.com/zowe/vscode-extension-for-zowe/pull/1483

- Fixed computing list of items to delete
- Fixed Cancel button during delete of many
- Fixed incorrect message reporting files that were not deleted as deleted if op was cancelled
- Fixed deleting on Theia/Che

Theia currently does not support multi-select and using the tree api to get the selection state does not work (See eclipse-theia/theia#9074). 
So I added a special single select case, which would not require a withProgress dialog anyway.

## Release Notes

- Fixed the issue that Delete was broken for the data set view in Theia

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [X] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [X] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [X] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by phaumer** [comment]
I have some questions about the failings tests as they do not seem to mock the withProgress VS Code API as other tests do. I need to ask for someone to help me get them fixed.

**Comment by katelynienaber** [comment]
I think also lint is failing. When I try to package ZE I get a const/let error in `dataset/actions.ts` on line 257

**Comment by phaumer** [comment]
Thanks @JillieBeanSim and @katelynienaber. I merged the test fixes and opened the PR for review now.

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @phaumer  for your work on this

**Comment by katelynienaber** [comment]
I am having trouble testing this, because when I right-click in Theia, the context menu doesn't appear. @phaumer @JillieBeanSim did you have any luck with this? Jelly tried testing it but she can't create a profile via Theia XD

**Comment by JillieBeanSim** [comment]
> I am having trouble testing this, because when I right-click in Theia, the context menu doesn't appear. @phaumer @JillieBeanSim did you have any luck with this? Jelly tried testing it but she can't create a profile via Theia XD

@katelynienaber I didn't have any trouble with the right click menu in theia. Worked great for me

**Comment by JillieBeanSim** [comment]
ok, I am using an older theia.  I see that things are broken on theia 1.17.2 so looking back on theia version so we can document the supported version

**Comment by katelynienaber** [comment]
Lol this is great, our Theia support is awesome :D

- In Theia 1.15, Theia fix works great!
- I tested it in Theia version 1.14, and the nodes are not deleted at all.
- 1.16 and up, no right-click menu.

Also one more thing...if you select a data set and its members for deletion, and the parent data set is deleted first, ZE still tries to delete the members. But they are already gone. So an error is thrown, which makes the countdown for node deletion disappear, even though deletion is still happening. In the `The following items were deleted` message, it doesn't list the members as deleted, just the parent node. Maybe it's possible to make sure the children are deleted first, so they show up in the list of deleted nodes? Or just remove the children from the array of nodes to be deleted, so the error doesn't come up?

**Comment by lauren-li** [comment]
> Lol this is great, our Theia support is awesome :D
> 
>     * In Theia 1.15, Theia fix works great!
> 
>     * I tested it in Theia version 1.14, and the nodes are not deleted at all. But right-click menu is there.
> 
>     * 1.16 and up, no right-click menu.
> 
> 
> Also one more thing...if you select a data set and its members for deletion, and the parent data set is deleted first, ZE still tries to delete the members. But they are already gone. So an error is thrown, which makes the countdown for node deletion disappear, even though deletion is still happening. In the `The following items were deleted` message, it doesn't list the members as deleted, just the parent node. Maybe it's possible to make sure the children are deleted first, so they show up in the list of deleted nodes? Or just remove the children from the array of nodes to be deleted, so the error doesn't come up?

Interesting - I also tested this PR in Theia 1.14.0, and delete seemed to work well for PDS, PS, and members. I didn't see regressions in other things I smoketested (creating a profile, submitting a job, viewing jobs, searching for and creating USS resources) - except when I submitted a job, clicking on the job link in the pop-up info message did not show the job in the Jobs view (but I don't think that is related to the changes in this PR).

Regarding ZE still trying to delete PDS members after the parent data set is deleted first, that is definitely suboptimal UX and we should file a separate issue to fix it, as it also happens in the current 1.18.1 release. On the bright side, despite the `not found` errors for the members, the delete of the PDS still goes through.

**Review by katelynienaber — APPROVED** [review]
Approving ^^

Issue that @lauren-li mentioned should be opened separately is [here](https://github.com/zowe/vscode-extension-for-zowe/issues/1492).

**Comment by lauren-li** [comment]
Thanks @katelynienaber for opening up the new issue (#1492)!

I didn't leave a formal approval here, but as mentioned in my earlier [comment](https://github.com/zowe/vscode-extension-for-zowe/pull/1487#issuecomment-919847042), the functionality was working well for me in manual testing (both in Theia 1.14.0 and VS Code). Unit tests and all expected integration tests were also passing.

Thanks @phaumer for this fix!

**Pull request merged**
