### PR TITLE
Issue #968a: Group data sets’ favorites by profile and allow extenders to activate before loading profiles

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Addresses the following issues for the Data Sets tree:
#968 (Favorites created by other extensions should not throw errors as the other extensions are not activated yet)
#168 (Group Favorites section based on profile)

This PR groups favorites for the Data Set tree by profile. Data set favorite nodes are still created when Zowe Explorer activates, but the profile/session properties of those nodes are not set until the user actually clicks to expand the relevant profile grouping node in the Favorites section for the first time. This lazy loading of profiles allows extenders to activate before profile loading is requested, and also prevents Zowe Explorer from throwing errors for invalid favorites/favorites’ profiles upon VS Code/Zowe Explorer startup when the user may not even be looking to interact with Zowe Explorer/data set favorites.

The profile/session values that are set when the user first clicks to expand a profile grouping node in the Favorites section are stored with the relevant favorites’ nodes, so that favorites’ profile loading should only need to occur once per profile group during a VS Code session. Any subsequent clicks to expand the same profile grouping node should just reference the stored values.

Gif of UI change:
Zowe Explorer group by profile PR

## Release Notes

Milestone: 1.9

Changelog: Group Data Set favorites by profile, and load/set favorites’ profiles only when the user clicks to expand the relevant profile grouping node in the Favorites section.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

## Further comments

Note that this PR addresses both issues #968 and #168, but does not close either of them. Similar modifications should also be made to the USS and Jobs favorites before closing these issues.

## Related issues
The following issues found in master branch were fixed incidentally as part of the work for this PR:
- Tooltip of DS member did not update on rename.
- Rename DS member from Favorites did not also rename DS member in Session section.
- Delete PDS member from Favorites did not delete it from Session section - had to collapse/re-expand the node in the Session section. (However, the reverse is already working: Delete PDS member from the Session node does delete it from the corresponding Favorites node without any extra user action.)
- Errors appeared when deleting PDS/sequential data sets in general (not just from the Favorites section): e.g.`Error running command zowe.deleteDataset: Cannot read property 'getLabel' of null. This is likely caused by the extension that contributes zowe.deleteDataset.`

With this PR, all functionality with the Data Sets tree (both related and unrelated to favorites) should be working at least as well as they were originally, but some pre-existing issues (listed below) were found while working on this PR. I believe these issues can be fixed in future PRs, as they are already in the master branch, and not regressions caused by this PR. Note that some of these may already be filed in our Issues section, but I wanted to note them here as a convenient reference in case reviewers encountered any of them during testing:

**Favorites-specific issues**
- Favorited searches in DS, USS, and Jobs start out with a magnifying glass icon. After clicking on the favorited search, the icon changes to a folder icon with a validation circle. The user can then add a duplicate entry of that search to favorites settings.json and UI.

**General issues**
- #973 (Rename causes VS Code to flip through editor tabs)
- Create sequential DS gives a debug error. (This appears to involve the `createFile` function, which was not modified in this PR.): `rejected promise not handled within 1 second: Error: TreeError [zowe.explorer] Data tree node not found: [object Object]`

**Syncing issues between Favorites and Sessions sections**
- If the user renames a PDS node in the Session (i.e. not Favorites) section from a different profile (e.g. in zoweCLI2) that refers to the same host/username/pw, then the corresponding node in Favorites (favorited from zoweCLI1) will not be renamed. (If the PDS node is renamed from Favorites, other profiles won’t have the updated ds name until refresh/re-search in the other profiles.)
- Create new PDS member in Session section does not create new member in Favorites and vice versa - have to collapse and re-expand PDS to see update. 
- Migrate DS from Session or Favorites section does not update the DS node or its context menu in Favorites (but it does update the node in the Session section - whether Migrate is clicked from Session or Favorites section). However, the node's "Show DS Attributes" command in Favorites and Session sections will show it’s migrated.

### CODE REVIEW

**Comment by jellypuno** [comment]
Hi @lauren-li Thank you for adding this. So far, it works similarly as what we have before (in terms of using zosmf profiles). The only thing that I noticed is that the favorites are removed once the profile is hidden. This is not the original behavior. Favorites are retained even if the profiles are hidden.

fave err1

**Comment by lauren-li** [comment]
Thanks @jellypuno for trying out this PR! I'm working on fixing this now.

**Comment by lauren-li** [comment]
@jellypuno I believe I've fixed the issue (which actually had to do with both hiding and deleting profiles). The unit test has been updated accordingly. I've also gone ahead and applied equivalent updates to my Jobs favorites PR (#991), so you should not see the problem there if you test that PR as well.

Thanks for catching this! Let me know if you see the issue persisting or find anything else.

**Comment by jellypuno** [comment]
@lauren-li looks great! thank you for the fix. One thing that I notice is that the icon is not changed if it is loaded through favorites. Although this is the current behaviour and it is not connected to this update.

Capture

**Review by jellypuno — APPROVED** [review]
Functionality works great! Thank you @lauren-li

**Comment by lauren-li** [comment]
> Functionality works great! Thank you @lauren-li

Thank you @jellypuno!
 
> One thing that I notice is that the icon is not changed if it is loaded through favorites. Although this is the current behaviour and it is not connected to this update.

I noticed this issue in the current `master` branch, as well (noted in my PR description). This would be a good UX issue to address in a future issue/PR, as the behavior does not seem intuitive.

**Comment by lauren-li** [comment]
Thanks @JillieBeanSim! Points 1 and 3 (being able to favorite a profile without a search, and not being able to favorite a DS member without the parent PDS) are both pre-existing behaviors in the master branch. I believe both are good candidates to address as future improvements to Zowe Explorer.

Regarding the second point with the error when renaming a DS member from, I am working to try and recreate the issue on my branch, but have been unable to thus far.

**Comment by lauren-li** [comment]
@JillieBeanSim The error in point 2 may have to do with the new DS member name being too long. Do you still get the error when renaming to a DS member name that is 8 characters or less?

I was able to recreate the errors in the Marketplace version with a 9-character rename, as well.

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim The error in point 2 may have to do with the new DS member name being too long. Do you still get the error when renaming to a DS member name that is 8 characters or less?
> 
> I was able to recreate the errors in the Marketplace version with a 9-character rename, as well.

correct, after restesting within the naming restrictions it worked, maybe we need a different error when naming conventions aren't followed vs a 500 error.

**Review by JillieBeanSim — DISMISSED** [review]
@lauren-li thanks for you work on this, functionality works great! tests and checks passing with the exception of known failing integration tests

**Comment by lauren-li** [comment]
Thank you to all those who have looked at this PR so far! To explain the most recent change (as it occurred after approvals were made):
- While working on bringing @katelynienaber's USS work into my USS PR #1006, I found an issue where `findFavoritedNode()` was not handling the case when there is no matching profile node in Favorites. Since the function works similarly in both Data Sets and USS, I added the fix (and related unit test) into this PR branch, as well.

The change is quite minor, but please feel free to take another look if you have the chance to.

**Review by katelynienaber — DISMISSED** [review]
Works great! I love the new functionality, nodes are refreshing properly when favorites are added/removed and when nodes are added/deleted, from favorites or from the regular sessions.

**Review by zFernand0 — APPROVED** [review]
😍 This is awesome!
No need to address conflicts yet

**Review by zFernand0 — DISMISSED** [review]

**Review by zFernand0 — APPROVED** [review]
good to go! 
Thanks @lauren-li

**Comment by zFernand0** [comment]
others have already approved! 
Merging!

**Pull request merged**
