### PR TITLE
Fix failure to load optional secure fields from profiles

### LINKED ISSUE #731: Fails to load profiles with optional secure fields when SCS enabled
When the Secure Credential Store plugin is enabled, and I have a profile containing optional secure fields that are not set (e.g., an SSH profile with no `keyPassphrase` value), the extension fails to load my profiles.

This issue was fixed in the `DefaultCredentialManager` of Imperative here: [@zowe/imperative#366](https://github.com/zowe/imperative/pull/366/files#diff-050e978f1da3b12e0441f6c1af9e1433). The same fix (adding an `optional` param to the `loadCredentials` method) should be implemented in the `KeytarCredentialManager` of Zowe Explorer.

### PR DESCRIPTION
**Pull request by tjohnsonBCM**
Fixes #731 by updating `KeytarCredentialManager` to not fail when an optional secure field is missing in a profile. This makes Zowe Explorer work in an environment with the SCS plugin enabled and multiple profile types such as SSH stored securely.

### CODE REVIEW

**Comment by jellypuno** [comment]
I tried to recreate this the scenario above in master. And it doesn't happen. I can see my credentials

**Comment by tjohnsonBCM** [comment]
Thanks for catching this @jellypuno, I believe this is #643 rearing its ugly head again 😢

Pushed a commit that seems to work around this for now, until the underlying problem (https://github.com/zowe/imperative/issues/379) is fixed.

**Comment by jellypuno** [comment]
@tjohnsonBCM Cool! I will check it :) Thank you

**Comment by jellypuno** [comment]
Hey @tjohnsonBCM this looks good! Thanks for the change. I am discovering bugs on my end while reviewing this PR 😢

**Pull request merged**
