### PR TITLE
Add jobs not found message

### PR DESCRIPTION
**Pull request by rudyflores**
Solves #2362 
## Proposed changes

Add `Jobs not found` message to jobs view when performing a filter search and not jobs are returned.

## Release Notes

Milestone: 2.9.2

Changelog: Added jobs not found message when no results are returned from filter.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @rudyflores for the fix

**Review by traeok — CHANGES_REQUESTED** [review]
This looks great, thanks @rudyflores 🙂 

However, would it be possible to move this underneath where we store the result of `this.getJobs` on line 179 of `ZoweJobNode.ts`? I added it as a part of my PR for fixing the jobs tree view, but realized you were working on this as well:

https://github.com/zowe/vscode-extension-for-zowe/pull/2371/files#diff-4cee24f48f3ba395a073912031b5e2cc03e49d117821c3fda3e588d64544daa6R178-R189

This way, it will match what we are doing when no spool files are returned (in the branch above), and then we should be able to merge it cleanly into the changes in #2371

**Comment by JillieBeanSim** [comment]
audit fix PR against maintenance https://github.com/zowe/vscode-extension-for-zowe/pull/2372

**Review by traeok — APPROVED** [review]
LGTM, thanks @rudyflores !

**Review by zFernand0 — APPROVED** [review]
LGTM! :yum:

**Pull request merged**
