### PR TITLE
Issue #1428: Limit commands shown in context menu on multi-select

### PR DESCRIPTION
**Pull request by katelynienaber**
## Proposed changes

Fix for issue #1428.

This is only a change in the Datasets tree (because only Datasets tree supports multi-select at this time).

Also, if you multi-select datasets/members and then try to do something with the _profile_, it is disabled. I did this because you could multi-select profiles _and_ datasets, and then try to run a profiles command. So, I think we should handle this in another PR and for now it is simply disabled.

deleteExampleDocs

## Release Notes
Milestone: Backlog
Changelog: Commands which do not support multi-select are hidden when many elemene

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

It would be really cool to merge this before I add multi-copy/paste ^^' That's why I added this to 21PI3, because that is the deadline on the multi-select completion.

### CODE REVIEW

**Comment by jellypuno** [comment]
Is it possible to convert the regex to a positive check rather than a negative check on listMultiSelection? So we only need to add it in one or two `when` property?

`"when": "view == zowe.uss.explorer && viewItem =~ /^(?!.*_fav.*)(textFile.*|binaryFile.*|directory.*)/ && !listMultiSelection",`

**Comment by katelynienaber** [comment]
A thought from Venkat: will a phrase like `Delete data set(s)` translate well? Maybe we should choose something else jic...

**Comment by lauren-li** [comment]
> A thought from Venkat: will a phrase like `Delete data set(s)` translate well? Maybe we should choose something else jic...

@katelynienaber I have a vague recollection of the Zowe Explorer squad discussing this (or at least the wording of this context menu item), and I think you had proposed just changing it to "Delete" (for both data sets and members), as that's the wording VS Code uses for both files and folders (single or multiple selection). Using this wording would also cover the edge(?) case where a user multi-selects a mix of data sets and members.

**Comment by katelynienaber** [comment]
@lauren-li this has been added!

**Comment by JillieBeanSim** [comment]
@katelynienaber can do the audit fix like so, the fix is also in Fernando's PR 
image

**Comment by katelynienaber** [comment]
@JillieBeanSim Audit is fixed and pushed...

**Comment by jellypuno** [comment]
> > Is it possible to convert the regex to a positive check rather than a negative check on listMultiSelection? So we only need to add it in one or two `when` property?
> > `"when": "view == zowe.uss.explorer && viewItem =~ /^(?!.*_fav.*)(textFile.*|binaryFile.*|directory.*)/ && !listMultiSelection",`
> 
> I don't think so. Since you can only turn on multi-select for the whole tree, you have to put controls on the ones that don't support it. AFAIK VSCode doesn't have any other way to tell that the command is unsupported, and it will try to run the unsupported commands even when many items are selected.
> 
> Info about multi-select for custom trees (turned on when the `TreeViewOptions` are passed in on tree initialization): [microsoft/vscode#76941](https://github.com/microsoft/vscode/issues/76941)

@lauren-li Do you think a change in the docs is needed here?

**Comment by lauren-li** [comment]
> > > Is it possible to convert the regex to a positive check rather than a negative check on listMultiSelection? So we only need to add it in one or two `when` property?
> > > `"when": "view == zowe.uss.explorer && viewItem =~ /^(?!.*_fav.*)(textFile.*|binaryFile.*|directory.*)/ && !listMultiSelection",`
> > 
> > 
> > I don't think so. Since you can only turn on multi-select for the whole tree, you have to put controls on the ones that don't support it. AFAIK VSCode doesn't have any other way to tell that the command is unsupported, and it will try to run the unsupported commands even when many items are selected.
> > Info about multi-select for custom trees (turned on when the `TreeViewOptions` are passed in on tree initialization): [microsoft/vscode#76941](https://github.com/microsoft/vscode/issues/76941)
> 
> @lauren-li Do you think a change in the docs is needed here?

@jellypuno Yes, it would be good to put a short explanation into `docs/README-Extending.md#contextual-hooks` about how if the Extender is adding a command that does not support multi-select to a Zowe Explorer menu, they will need to add the `!listMultiSelection` into their command's `when` clause. That would make sense to do as part of this PR.

**Comment by jellypuno** [comment]
Discussion: https://github.com/zowe/vscode-extension-for-zowe/discussions/1476

**Comment by zFernand0** [comment]
@katelynienaber,
Just wanted to drop by and thank you for all the contributions (this one in particular 😋)
Just updated the branch one last time to prevent future merge conflicts.
We will be closing this PR for now.
The PR and the issue have been linked to the Multi Selection Epic (#1286).
We will get back to this for sure 😋

**Comment by zFernand0** [comment]
Please refer to 7f97adfeb2cdeecf7b93c994e56c9d01df45e6f2 for the latest code changes.
`git checkout 7f97adfeb2cdeecf7b93c994e56c9d01df45e6f2`

**Pull request closed without merging**
