### PR TITLE
Port/2533+2692

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

Migrate the following PRs:
- #2692
- #2712

## Release Notes

Milestone: vNext

Changelog: N/A

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

I few things I noticed...
- I'm unable to run the `pnpm --filter vscode-extension-for-zowe vscode:prepublish` script.
  - Failed with `bad export type for 'tree_sitter_tsx_external_scanner_create': undefined` (likely due to not locking down the version of `@vscode/l10n-dev`
- Should we lock down the above dependency
```
> npx @vscode/l10n-dev export --o ./l10n ./src

Need to install the following packages:
@vscode/l10n-dev@0.0.33
Ok to proceed? (y) 
```

---

UPDATE: 
- The above issue happened because I was on NodeJS v20
- The `npx @vscode/l10n-dev ...` was changed to the PNPM equivalent: `pnpm dlx @vscode/l10n-dev ...` 😋 
- There were lots of new changes because of the following:
  | Before | After |
  |-|-|
  | `toBeCalled `| `toHaveBeenCalled` |
  | `toBeCalledTimes` | `toHaveBeenCalledTimes` |

### CODE REVIEW

**Comment by zFernand0** [comment]
Waiting on the following PR to fix the Audit check:
- `https://github.com/zowe/zowe-cli/pull/2050

**Comment by zFernand0** [comment]
Will update this PR once the vNext version of the `@zowe/cli` is updated to address the Audit check 😋

**Comment by JillieBeanSim** [comment]
@zFernand0 I was able to run `pnpm --filter vscode-extension-for-zowe vscode:prepublish` on this branch and do see some changes in the bundle file
Screenshot 2024-02-13 at 10 52 52 AM

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @zFernand0

**Comment by JillieBeanSim** [comment]
Should we update the lerna in this PR to kick off release of audit fixes?

**Comment by zFernand0** [comment]
> Should we update the lerna in this PR to kick off release of audit fixes?

Done! Although I'm a bit confused as to why we should update it even for the `next` branch 😋

**Comment by JillieBeanSim** [comment]
> > Should we update the lerna in this PR to kick off release of audit fixes?
> 
> Done! Although I'm a bit confused as to why we should update it even for the `next` branch 😋

Thanks.  IDK, know there was mention that next would publish with all merged PRs but last was on the 7th and I know we have been merging since 7th.
https://github.com/zowe/vscode-extension-for-zowe/releases/tag/v3.0.0-next.202402071248

**Review by JillieBeanSim — APPROVED** [review]

**Review by traeok — APPROVED** [review]
LGTM, thanks @zFernand0

**Pull request merged**
