### PR TITLE
Update v1.21.x with 1.21.1-SNAPSHOT versioning

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Update v1.21.x with 1.21.1-SNAPSHOT versioning

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jellypuno — APPROVED** [review]
LGTM! Thanks @lauren-li

**Comment by JillieBeanSim** [comment]
Why are we adding SNAPSHOT to the release branch?  We have never done this before.
@lauren-li @jellypuno

**Comment by JillieBeanSim** [comment]
> > Why are we adding SNAPSHOT to the release branch? We have never done this before. @lauren-li @jellypuno
> 
> Oh sorry. 😅 Are we only adding it in master branch?

I was asking since in the past we have only done it to the Master branch.  Didn't know if I missed a conversation that changed that.

**Comment by lauren-li** [comment]
> > > Why are we adding SNAPSHOT to the release branch? We have never done this before. @lauren-li @jellypuno
> > 
> > 
> > Oh sorry. 😅 Are we only adding it in master branch?
> 
> I was asking since in the past we have only done it to the Master branch. Didn't know if I missed a conversation that changed that.

if we generate a build off of the v1.21.x branch, it’s good to indicate that it’s a snapshot rather than the actual v1.21.1. As long as this doesn’t mess up a pipeline - which we should double check if we haven’t done this before.

@crawr @zFernand0 I was wondering if you have any thoughts on this?

**Comment by JillieBeanSim** [comment]
if we do decide to start adding SNAPSHOT to release branch as well as Master branch we may want to look into how we can automate this in the deployment scripts.  Remembering the follow up PR to master after a release is one thing, but 2 follow up PRs is another.

**Comment by zFernand0** [comment]
(personally) I think adding Snapshot to any release branch makes sense.
Another suggestion (if you want to get rid of release branches) is to use tags in order to produce hotfixes 😋

**Comment by lauren-li** [comment]
> (personally) I think adding Snapshot to any release branch makes sense. Another suggestion (if you want to get rid of release branches) is to use tags in order to produce hotfixes 😋

@zFernand0 Just to double-check: Do you know of any pipelines attached to the release branches?

Doesn't getting rid of release branches and only using tags mean that we lose the ability to easily fix bugs in a hotfix release that is separate from upcoming features we are adding?

**Comment by zFernand0** [comment]
> Doesn't getting rid of release branches and only using tags mean that we lose the ability to easily fix bugs in a hotfix release that is separate from upcoming features we are adding?

Tags work the same way as branches in terms of producing a hot fix without adding new features.
You can `git checkout <tag>`, make the hotfix, and release from the branch created off of the tag : )
It may take some time to get used to though.
It might be easier to just continue with release branches for now 😋

**Comment by crawr** [comment]
The release wiki has to be updated to reflect the changes here.
A new issue will be opened to address the automation of this process.

**Review by JillieBeanSim — APPROVED** [review]

**Comment by lauren-li** [comment]
Thanks all for the reviews and discussion! I have updated the wiki page for [Preparing for a release](https://github.com/zowe/vscode-extension-for-zowe/wiki/Preparing-for-a-release), and created issue #1614 to automate the process.

**Pull request merged**
