### PR TITLE
[maintenance] Dependency updates for audit failures

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

to release a 2.6.2 patch for the updates I cherry picked Peter's commits from https://github.com/zowe/vscode-extension-for-zowe/pull/2153 and updated all CHANGELOGS creating the PR against the `maintenance` branch.

## Release Notes

Milestone: 2.6.2

Changelog: Updated dependencies for security audits.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by phaumer** [comment]
Thanks so much @JillieBeanSim
As @t1m0thyj mentioned, the integration tests are not used at the moment and need work, I also updated the mocha to the latest.

**Review by phaumer — APPROVED** [review]

**Comment by zFernand0** [comment]
Sorry for the delay, but I'm still trying out this PR.
I'll leave a proper comment in a few moments.

**Comment by zFernand0** [comment]
I tried running the Theia tests since they were skipped on this PR.
I'm afraid I ran into a few problems 😢 
The `@types/mocha` package seems to contain very old references which makes the code compile even with the jump from 6 to 10. 
However, there were some deprecations and removals that we may need to update on this PR if we want to update the Mocha dependency.
I'll open a quick PR against this branch to discuss these changes 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 

Thanks for updating all of these packages 🥳

**Review by zFernand0 — APPROVED** [review]

**Comment by zFernand0** [comment]
FYI, All code smells and duplication are coming from our integration tests. 
I believe we can address these items when we work on the following issues:
- #1595 
- #2103

**Review by t1m0thyj — APPROVED** [review]
LGTM. Thanks @phaumer and @zFernand0 for removing so many resolutions in package.json 🙂

**Pull request merged**
