### PR TITLE
fix: remove jest-stare

### PR DESCRIPTION
**Pull request by VitGottwald**
because it is causing random test failures,
[see](https://github.com/dkelosky/jest-stare/issues/300)

### CODE REVIEW

**Comment by dkelosky** [comment]
hey @VitGottwald, as @tjohnsonBCM mentioned, I think `jest-stare` failing is only a symptom of real a mocking problem with `fs`.  I'll add notes to #774.

It might still be valid to remove `jest-stare` but perhaps for another reason 😄 .

**Comment by VitGottwald** [comment]
@dkelosky I agree and do believe there are bigger hidden problems to fix. jest-stare is simply one more thing to worry about at this point, that's why I want it out of the picture.

**Comment by VitGottwald** [comment]
The test suite actually is failing after jest-stare is removed. I will investigate. I guess I will come at similar conclusion as you and @tjohnsonBCM .

**Comment by VitGottwald** [comment]
You are right about `jest.mock('fs')` @dkelosky . Because it is a core node module, explicit jest.mock is [required](https://jestjs.io/docs/en/manual-mocks)
> Warning: If we want to mock Node's core modules (e.g.: fs or path), then explicitly calling e.g. jest.mock('path') is required, because core Node modules are not mocked by default.

**Comment by dkelosky** [comment]
I know I'm being a pain here, but the premise of this change was on a perceived failure in the reporter and not wanting to divert energy from refactoring.  

Perhaps this issue & PR should titles should be changed to reflect the current work: "Removing Unused Reporter" or whatever lines you're thinking.

As I mentioned, I don't care if it's removed, however, the test failures are independent from `jest-stare`.  

The important takeaway was how to handle mocking of core node modules and shouldn't be conflated with removing a reporter.

**Comment by VitGottwald** [comment]
You are certainly not pain here @dkelosky . Not at all. If someone is a pain here it is myself. 

You are right, jest-stare seems not to be an issue in the end. I wanted to eliminate unnecessary code and it became a scapegoat in the effort.

I am closing this PR in favour of https://github.com/zowe/vscode-extension-for-zowe/pull/776

**Pull request closed without merging**
