### PR TITLE
Enhance throw error in zowe ftp extension

### PR DESCRIPTION
**Pull request by tiantn**
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Thanks for adding the common class 🥳

**Review by zFernand0 — CHANGES_REQUESTED** [review]
the changelog for zowe-explorer is not required since the only thing that changed was the license header on a test file.

However, patch coverage may need to be increased a bit more 😢

**Review by std4lqi — DISMISSED** [review]

**Review by std4lqi — APPROVED** [review]

**Comment by tiantn** [comment]
Thank you @std4lqi for your guidance and kindly help me solved some problems. Thank you @zFernand0 for your review.

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @tiantn for the updates, there seems to be a broken FTP unit tests.

**Comment by tiantn** [comment]
> @tiantn looks like there are some broken unit tests that need to be fixed before we can merge this in.

Thank you @JillieBeanSim. I increased the timeout value to 100000 ms but still got timeout error in windows environments. I found some message `info There appears to be trouble with your network connection. Retrying...` in workflow. Could you help to check the network of windows environments? Thank you very much!

**Comment by tiantn** [comment]
Hi @JillieBeanSim, I fixed the unit test error in windows. Could you help to review? Thank you very much!

**Comment by JillieBeanSim** [comment]
> Hi @JillieBeanSim, I fixed the unit test error in windows. Could you help to review? Thank you very much!

Awesomes! thanks @tiantn, will do!

**Review by zFernand0 — APPROVED** [review]
This makes the error handling more consistent for the FTP extension, and may also fix a few edge cases where the error was not shown to the end user.
The changes LGTM! 😋 

This also makes it clear where the error is coming from.
image

Curious if we could combine the standardized `ZoweFtpExtensionError` with the common `Gui` class for showing error messages 🤔

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @tiantn for the fix

**Pull request merged**
