### PR TITLE
Issue 868: PDS member search filter

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Accept member name or member pattern in the initial search filter of a profile and no longer throw an error if this is entered like it does now.  Use the search filter with member name or pattern to search for the appropriate data sets then when data set is opened the member search appears within.

This is part one of multiple parts discussed in the issue https://github.com/zowe/vscode-extension-for-zowe/issues/868

## Images to help describe changes
If no member filter added to the search filter `zowebjs.test*.*, zowebjs.testnds` I get this list of members
image

Allowing member search in the filter search bar, the search entered into the filter is `zowebjs.test*.*(test*), zowebjs.testnds(test*)`
pds-member-filter-working

## Release Notes

Milestone: 1.12.0

Changelog: Allowing member search and member search filters in the Data Sets filter search bar.
- We may want to include a new GIF of the filter search as well

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by lauren-li — COMMENTED** [review]
I think this works really well (and also the functionality is a great addition)! All unit and expected system tests are passing. Thanks for your hard work on this @JillieBeanSim!

The only thing we might want to refine (not sure if as part of this PR or a separate one) is, if the user has done a previous member search within a data set, they will continue to see the data set filtered by their previous search until they manually refresh the data set contents by closing and reopening the folder. Only then can they see the new results. Perhaps we could fix this by refreshing the data set element for them when they run a new search for a member?

Gif to illustrate:
In the below gif, I first run a member search for `ZOWELKL.AT*(B)`, which correctly returns no members. After I revise my search to `ZOWELKL.AT*(B*)`, my resulting member for the new query does not appear until I close and reopen the parent data set `ZOWELKL.ATEST`:
ze-memberSearch2

**Comment by JillieBeanSim** [comment]
@lauren-li thanks for catching that, I will look into it.  I also want to wait on a discussion about an item @jelaplan brought up in the issue about the text/info in the pop up textbox:
image

If this is changed we can handle it in this PR as well.

**Comment by zdmullen** [comment]
Suggestion for the message: 

"Create a new filter. For example: HLQ.*, HLQ.aaa.bbb, HLQ.ccc.ddd(member)"

Need documentation updates here with the (member) search addition. @IgorCATech

**Comment by jelaplan** [comment]
Thank Zach (@zdmullen) for the text suggestion.  I think the refresh issue is a bug. If a user searches, the results need to appear. It seems unreasonable to ask a user to open and close the data set to get the results.

**Comment by JillieBeanSim** [comment]
new defaultDialogText in DatasetTree 

image

**Review by zdmullen — APPROVED** [review]
This is great! One thing that I thought about while testing was the length of the search history that we provide the user with for filters (just five items), as though it might become backlogged with searches for members, pushing previous searches for different data sets out of the list. I don't think this is a big issue, just something we might discuss again in the future. 

Just one item-- let's be sure to not only have the documentation for this, but a gif as well so that we can really highlight it when we release 2.0. It's an item people have been waiting for, so it'll be good to give it more of a limelight. Thanks, @JillieBeanSim!

**Comment by katelynienaber** [comment]
@JillieBeanSim This works great!

The one thing I noticed is, if I run a search, then create a member whose name doesn't fit the search criteria, the new member doesn't show up in the list.

Ex:
- Search for `PDS.TEST(ABC)`
- Create member `DEF`
- The list is refreshed but the new member is not in it

Maybe we could edit the search to include the old search pattern, _and_ the new node's name? ie. after the new node was created above, search string would look like `PDS.TEST(ABC),PDS.TEST(DEF)` and so the new node would show up...

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim This works great!
> 
> The one thing I noticed is, if I run a search, then create a member whose name doesn't fit the search criteria, the new member doesn't show up in the list.
> 
> Ex:
> 
> * Search for `PDS.TEST(ABC)`
> * Create member `DEF`
> * The list is refreshed but the new member is not in it
> 
> Maybe we could edit the search to include the old search pattern, _and_ the new node's name? ie. after the new node was created above, search string would look like `PDS.TEST(ABC),PDS.TEST(DEF)` and so the new node would show up...

@katelynienaber with a filter in place and the new member not fitting the filter it wouldn't show, the search filter would need to be updated to include the new item/search.  This is why the icon is important to remind the user that a particular filter is in place.

**Comment by katelynienaber** [comment]
> @katelynienaber with a filter in place and the new member not fitting the filter it wouldn't show, the search filter would need to be updated to include the new item/search. I am not sure this should be done automatically, but done by the user since they are the one that put the particular filter in place. If other members start with `def` not only the new they would all begin to show automatically. This is why the icon is important to remind the user that a particular filter is in place.

Aha okay. I hadn't read that other thread. So I like this very much :)

**Review by katelynienaber — APPROVED** [review]
LGTM :)

**Pull request merged**
