### PR TITLE
Fix check in deployment.yaml for 'SNAPSHOT'

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

fix if check syntax for `Check version is bumped` 

deployment failed in PR https://github.com/zowe/vscode-extension-for-zowe/pull/1463, https://github.com/zowe/vscode-extension-for-zowe/actions/runs/1189528202

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
This should work!
If you would like to test it, you could do se here, or in a fork 😋

**Comment by JillieBeanSim** [comment]
> This should work!
> If you would like to test it, you could do se here, or in a fork 😋

watching now https://github.com/zowe/vscode-extension-for-zowe/actions/runs/1190383414 fingers crossed

**Comment by JillieBeanSim** [comment]
@zFernand0 it didn't work, created a draft release with the uploads.  I deleted the draft

**Comment by JillieBeanSim** [comment]
Finally! Winner, Winner, Chicken Dinner!!! https://github.com/zowe/vscode-extension-for-zowe/runs/3485740840
image

**Comment by zFernand0** [comment]
Thanks for cleaning things up!
Looks much nicer! : )

**Review by zFernand0 — APPROVED** [review]

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
