### PR TITLE
fix(trees): Refresh breaks tree states and icons; misc. UI updates

### PR DESCRIPTION
**Pull request by adam-wolfe**
## Proposed changes

- [x] Replace `labelRefresh` functionality with `mOnDidChangeTreeData.fire()` for proper refresh in `vscode.TreeView`
- [x] Removed updates to children array in `refreshAll` to preserve tree states
- [x] Added unique IDs for all nodes that are added to our tree views (Data Sets, Unix System Services, Jobs)
  - Without these unique IDs, VSCode will build an ID based on the parent label and the current node label, which can introduce ID conflicts. This prevents VSCode from losing track of `TreeItem` objects

Additional, misc. fixes:
- [x] Renamed all instances of "datasets" to "data sets"
- [x] Added separators in quick picks to visibly separate actions & history
- [x] Replaced "plus" and "pencil" unicode chars w/ icons where applicable
- [x] Changed the naming of some options for better UX

## Release Notes

Milestone: 2.9.0

Changelog:
- Fixed issue where refreshing views collapsed the respective trees. [#2215](https://github.com/zowe/vscode-extension-for-zowe/issues/2215)
- Added optional `id` variable to `IZoweTreeNode` interface, to allow developers to pass a unique ID for tree nodes.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Comment by adam-wolfe** [comment]
Additional thoughts re. refreshing in the USS view specifically:

- It may not make sense to display the refresh directory button (download icon) for session nodes, or maybe it should just have different alt text.
- Should we show the refresh directory button for directory nodes?
- Regardless, it might make sense to modify \zowe-explorer\src\uss\init.ts to also allow the refreshDirectory function to refresh the session node since the refresh directory icon is shown next to the session nodes. i.e.:
 
selectedNodes = selectedNodes.filter((x) => contextuals.isUssDirectory(x) **_|| contextuals.isUssSession(x)_**);

**Review by zFernand0 — CHANGES_REQUESTED** [review]
This fix seems to work whenever there is only one profile loaded in the tree.
However, in this GIF you may see that the contents of the USS Directories never comes back after a refresh.
Also, the folder icons may need to be "reopened" 😋 

temp

**Comment by adam-wolfe** [comment]
> This fix seems to work whenever there is only one profile loaded in the tree. However, in this GIF you may see that the contents of the USS Directories never comes back after a refresh. Also, the folder icons may need to be "reopened" 😋
> 
> temp [ temp ](https://user-images.githubusercontent.com/37381190/232324719-ea74b018-0b89-40b4-891b-c678f460a1ba.gif) [ ](https://user-images.githubusercontent.com/37381190/232324719-ea74b018-0b89-40b4-891b-c678f460a1ba.gif)

Should be resolved now including the folder icon issue.

**Review by traeok — COMMENTED** [review]
Thanks for looking into this @adam-wolfe - I noticed that the trees no longer collapse, but the icons will reset after the refresh. Note the expanded folder icon changes to a collapsed folder after refreshing:

IconsResetAfterRefresh

Aside from that, LGTM!

**Review by traeok — COMMENTED** [review]
Marked previous review as outdated as I had issues with the previous demo GIF.

Thanks for looking into this @adam-wolfe - I noticed that the trees no longer collapse, but the icons will reset after the refresh. Note the expanded folder icon for `EmptyRootFolder` changes to a collapsed folder after refreshing:

IconsResetAfterRefresh

This could be outside of this PR's scope as it might be how we are currently updating icons, but I figured it was worth mentioning. Aside from that, LGTM!

**Comment by adam-wolfe** [comment]
Beyond the icon issues, now the trees collapse when opening a file after refreshing. I'll take another look at at.

**Comment by traeok** [comment]
I've continued working on this issue and resolved the tree state bugs by adding unique identifiers to tree nodes. (`id` variable)

This does not work in Theia as Theia builds its own ID structure. However, since the issue does not occur on Theia, I've adjusted the code to only add IDs in non-Theia environments.

In addition, I've added some minor UI changes to this PR to clean up the UX, and standardized some of the naming conventions to match the rest of Zowe Explorer.

**Comment by adam-wolfe** [comment]
LGTM thanks Trae

**Review by zFernand0 — CHANGES_REQUESTED** [review]
LGTM! 😋 

(Approved, but waiting until v2.8.0 goes out)

**Review by zFernand0 — DISMISSED** [review]

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! thanks @adam-wolfe :) 

@zFernand0 do you think the addition of the unique id to nodes will help with the issue we spoke about yesterday with the tree node label overlapping

**Review by JillieBeanSim — APPROVED** [review]

**Comment by zFernand0** [comment]
> Do you think the addition of the unique id to nodes will help with the issue we spoke about yesterday with the tree node label overlapping

It may! 😋

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
