### PR TITLE
pds-member-search-icons

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Adds the new icon at the PDS level for data sets that have a member search filter in place

## Release Notes

1.12.0

related issue: https://github.com/zowe/vscode-extension-for-zowe/issues/868

Milestone: 1.12.0

Changelog: Adds the new icon at the PDS level for data sets that have a member search filter in place

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

filter-search-icon

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
Still need to get the folder to close after filter search has changed if that folder is included in new search and fix unit test

**Comment by jellypuno** [comment]
@JillieBeanSim Thank you Billie for adding the fix of the issue here. So just for recording purposes, I am experiencing the said issue when I tried to search for a dataset in this format: `ZOS.PUBLIC.D*, z80428.cbl(he*)`

The expected result is that it will show me all contents from ZOS.PUBLIC.D* and the the HELLO member from z80428.cbl. 
The actual result is that it showed me HELLO member from z80428.cbl and ZOS.PUBLIC.D* has no contents (There should be 4 modules inside). Then it also fires all the list APIs during that filtering. 

SEARCHpdS

**Comment by JillieBeanSim** [comment]
Thanks @jellypuno I will look into what is going on with multiple searches

**Comment by JillieBeanSim** [comment]
@jellypuno when you get a chance see if changes fixes issue you mentioned.  I am no longer adding the memberPattern to session node, only to data set node that is related to member filter.  

I do have a couple more things to work out like the open folder closing after filter search change and now removing memberPattern from data set when filter search changes

**Comment by jellypuno** [comment]
@JillieBeanSim Thank you! I will test it.

**Comment by JillieBeanSim** [comment]
@jellypuno @lauren-li I have fixed all but one issue I think, I cannot get the folder to automatically close in between filter searches.  I have tried `this.refreshElement(node)` where node is the session node and setting the collapsibleState to Collapsed on a data set level isn't working. Any ideas on how I can handle this?

What I have done is:
1. no longer adding the `memberPattern` to session node, only to data set node that is related to member filter
1. removing `memberPattern` from data set when filter search changes that doesn't need it anymore
1. filter icon after initial search
1. fixed sessionActiveOpen and sessionOpen (for unverified) icons for when session is expanded

filter-icon-folder-wont-close

**Comment by lauren-li** [comment]
> I cannot get the folder to automatically close in between filter searches.

@JillieBeanSim If I'm understanding the issue you mentioned correctly, I think this happens between data set searches on `master` branch and v1.11.1, as well. So if we want to fix it, it could be done as a separate PR.

(Gif of what I see with Zowe Explorer 1.11.1):
ze-dsSearch

**Comment by JillieBeanSim** [comment]
Thanks @lauren-li for noticing that this happens on Master and v1.11.1

I have pushed a change to keep the folder icon state if search changes and folder icon is open, it will now stay open as it does in your gif of v1.11.1

**Review by lauren-li — DISMISSED** [review]
This PR looks really good to me now. The icons are present and appear to be behaving as expected, and the data set nodes now refresh correctly with consecutive member search queries. The multiple "Get Dataset list" requests are gone, and some of the integration tests that were timing out for me on `master` branch are now passing again (probably related). All unit and expected integration tests are passing.

Thanks @JillieBeanSim for your hard work on this PR!

**Comment by jellypuno** [comment]
Hi @JillieBeanSim , The getList issue is fixed! thank you for that. I found one small issue:

The filtering doesn't work with this format: `ZOS.PUBLIC.D*, z80428.*l(he*)`. The correct datasets appear but the member filter is not correct. It displays all members inside the dataset.

If I change the filtering to: zos.public.*2.jc*(cb*d*), these are the members that are displayed. I was expecting that the last 5 members are not going to be there but maybe I'm wrong.

image

**Comment by jellypuno** [comment]
A future enhancement that I think we should add is the cancellation of the filter. Because after I click create member, I am not able to see that because I have a filter.

**Comment by JillieBeanSim** [comment]
> Hi @JillieBeanSim , The getList issue is fixed! thank you for that. I found one small issue:
> 
> The filtering doesn't work with this format: `ZOS.PUBLIC.D*, z80428.*l(he*)`. The correct datasets appear but the member filter is not correct. It displays all members inside the dataset.
> 
> If I change the filtering to: `zos.public.*2.jc*(cb*d*)`, these are the members that are displayed. I was expecting that the last 5 members are not going to be there but maybe I'm wrong.
> 
> image

@jellypuno did you try the same search via Zowe CLI with `cd*d*` as the pattern sent?  I ask as I just pass the member as the pattern to the api call

**Comment by jellypuno** [comment]
@JillieBeanSim I will try it in CLI 👍

**Comment by katelynienaber** [comment]
@JillieBeanSim For some reason this is not working for me at all. Maybe I'm doing something wrong. I ran yarn and prepublish, I have the most recent changes on this branch. It doesn't filter by member and I don't see the icon change...
memberSearchGif

**Comment by JillieBeanSim** [comment]
@jellypuno I think I have this issue you ran into fixed now

@katelynienaber make sure you pull latest changes then run `yarn` & `yarn build` to test.  The `prepublish` is for strings I believe

@lauren-li would you mind re-testing as I cancelled your review with changes to fix issue that was ran into.

**Comment by jellypuno** [comment]
thanks @JillieBeanSim . I will test it again. 👍

**Comment by lauren-li** [comment]
@JillieBeanSim I think I am now seeing something similar to what @katelynienaber mentioned in her comment (https://github.com/zowe/vscode-extension-for-zowe/pull/1146#issuecomment-766732818).

I no longer seem to get filtered members in my searches. My search for "ZOWELKL.ABC(TEST*)" returned the following (which is also the same result I get when searching for "ZOWELKL.ABC(TEST)", without the asterisk). The filter icon does not appear, and all members within the data set are returned, even after closing/reopening the PDS to be sure it's refreshed. There may be some extra calls being made to "Get Dataset list command", but I'm not 100% sure. Just something to keep an eye on in additional testing, although it's definitely much improved over the current `master` branch: 
ze-1146-abc

Here are my search results for "ZOWELKL.TEST(HELLO)". I get back all members of ZOWELKL.TEST (instead of just the member named "HELLO"), and I also get other data sets whose names contain "ZOWELKL.TEST", but who are sequential data sets (and therefore have no members), or who do not have any members named "HELLO": 
ze-1146-members

Please let me know if my testing queries are formatted incorrectly! The data sets and members in my gifs are also available if you want to test with them, as well.

(I'm not sure if this is helpful, but: I seemed to have better success when testing this PR at commit db2869e. Of the cases I mentioned above, the only thing that also doesn't work at that commit is that the search for "ZOWELKL.TEST(HELLO)" returns other data sets containing "ZOWELKL.TEST" in their names but no members/no members named "HELLO". However, member filtering of ZOWELKL.TEST does seem to work at that commit.)

**Comment by JillieBeanSim** [comment]
@lauren-li @jellypuno latest commit should be able to handle more robust pattern searches like `zos.public.*2.jc*(cb*d*)` as well as simple searches.

@lauren-li make sure you do a fetch and pull to get latest, looks like you were testing Sunday's commit that was just a save in the middle of my work and not fully functional

**Comment by JillieBeanSim** [comment]
looks like I broke an integration test, working to fix

**Comment by jellypuno** [comment]
Thank you @JillieBeanSim for your hard work. This is looking really great! and I appreciate that you handled the issues that I've found before. One thing that I notice is this: 

pds

What happened is that I searched for a dataset then I tried to login in a different profile. After that I cancelled the operation then everything was refreshed. It seems like a bug but maybe it is not. It might be a new ZE behavior that I am not familiar with

Another minor thing that I notice is that the progress bar when calling the filter member API and the updating of the tree are 2 separate progress bar. So, as a user, there was a 5 sec panic that I felt and I thought that the filter did not work because my tree was not updated. But this is really minor and you don't have to fix it.

**Comment by JillieBeanSim** [comment]
> Thank you @JillieBeanSim for your hard work. This is looking really great! and I appreciate that you handled the issues that I've found before. One thing that I notice is this:
> 
> pds
> 
> What happened is that I searched for a dataset then I tried to login in a different profile. After that I cancelled the operation then everything was refreshed. It seems like a bug but maybe it is not. It might be a new ZE behavior that I am not familiar with
> 
> Another minor thing that I notice is that the progress bar when calling the filter member API and the updating of the tree are 2 separate progress bar. So, as a user, there was a 5 sec panic that I felt and I thought that the filter did not work because my tree was not updated. But this is really minor and you don't have to fix it.

Hey @jellypuno, thanks for reviewing.  I did notice the slow load and have been making notes for a fine tune of this feature, also included in this list is when a user puts in a search for 2 items that may have overlapping data sets in a ds search filter and both include a member search filter the first may be overwritten.  We could open a new item to handle things like this after the initial is released and document limitations and behavior for when this enhancement is used.

The other issue with changing between profiles I haven't ran into or looked for yet, but will check it out if it's a quick fix like not making node dirty or something I could add it here but if more in depth fix we may need a new issue for it. What do you think?

**Comment by JillieBeanSim** [comment]
@jellypuno  I do wonder why the whole view is being refreshed upon login to APIML.  previously you could easily have multiple sessions open with a search in each without refreshing the view upon open/search of another session

**Review by jellypuno — DISMISSED** [review]
works great for me! Thank you @JillieBeanSim ! this is amazing :)

**Comment by katelynienaber** [comment]
@JillieBeanSim When I do a filter search, the icon appears on the DS, like expected. Then, if I add the DS to favorites, the favorited node has the filter icon...but the member list in faves isn't filtered, so the icon doesn't match the filter state of the fave node:
image

Also, I tried refreshing to see if that would fix the icon issue above, but the node with the filter icon disappeared from faves altogether.

**Comment by JillieBeanSim** [comment]
@katelynienaber what I could do right now is make sure add to favorites doesn't show in context menu for data sets that have a filter search on them and we could bring in this functionality in the future

**Comment by katelynienaber** [comment]
@JillieBeanSim That's cool, if you push again I will review again

**Comment by lauren-li** [comment]
@katelynienaber @JillieBeanSim It would be good to document for users the limitations of this regarding favorites. In a future PR/release, we can add additional functionality so that Favorites can handle member filtering, as well.

I am still testing this PR, and will update on how it goes!

**Comment by katelynienaber** [comment]
@lauren-li I think that you can add the search to favorites. It's just when trying to favorite a node.

Also I noticed you can't favorite a member, in general...but that is another issue. Not related to this PR.

**Comment by JillieBeanSim** [comment]
@katelynienaber just pushed the context menu and inline option change for favoriting a filtered data set.
filter-icon-no-favorite

**Comment by katelynienaber** [comment]
Hey @JillieBeanSim sorry for the delay...the favorite button is removed from the filtered data set, but not from the members of the filtered data set. The favorited member of a filtered DS still disappears when the workspace is refreshed.

**Comment by JillieBeanSim** [comment]
@katelynienaber "Your killing me Smalls" (ie The Sandlot lol) I think I have a fix here for you
filter-icon-no-favorite-members

**Comment by jellypuno** [comment]
> @katelynienaber what I could do right now is make sure add to favorites doesn't show in context menu for data sets that have a filter search on them and we could bring in this functionality in the future

I'm okay with this. Let's open an issue so we won't forget.

**Review by jellypuno — APPROVED** [review]
Looks great! thanks @JillieBeanSim

**Review by katelynienaber — DISMISSED** [review]
I approve these changes. I also approve these classy movie references.

EDIT: I have the same issue as @lauren-li, unfortunately...only seems to occur if the data set name is nonexistent and you try to add a member filter.

If the filter can't find a member with that pattern, but the DS exists, then it's fine.

**Comment by lauren-li** [comment]
Overall, this looks really good, but I wanted to check if anyone else is having issues when trying to run a member-filtering query that includes a data set name with a wildcard (`*`) that does not return anything. For example, searching for `HLQ.A*(TEST)` or `HLQ.A*(TEST*)` when I don't have any data sets starting with `HLQ.A*` gives me the following error:
Screen Shot 2021-01-27 at 7 15 42 PM

Executing the query with just the data set portion (i.e. `HLQ.A*`) correctly returns `No datasets found` in the UI.

If this issue isn't just specific to me, it may be related to line 1048 or 1060 in `DatasetTree.ts`.

**Comment by lauren-li** [comment]
I think the issue is here:
Screen Shot 2021-01-28 at 3 32 46 AM

`dsn` is being used as the basis for the `index` counter, but the `index` is being used on `name`. Since `name` equals `No datasets found` in the case I described in my previous comment but `dsn` is an array of more than one string (`['HLQ', 'zzz*']`), the `index` goes higher (1) than what's available in the `name` variable, and so a value of `undefined` gets passed into the `dsName` parameter of `checkFilterPattern(dsName, itemName)`.

Line 1048 in `checkFilterPattern` then attempts to perform `startsWith` on the `undefined` value, which results in the `startsWith` error.
Screen Shot 2021-01-28 at 3 43 36 AM

~
Also (and this can be done in a future PR), I think it might be helpful to comment the code here for better maintainability, especially the bits involving regular expressions.

**Comment by lauren-li** [comment]
To be honest, I'm having trouble understanding what each variable signifies, so I'm not sure if we want to change using `dsn`'s `index` on `name`. Assuming we want to stick with it (since most use cases seem to be working well already), could we just do a check like `if (name[index])` at line 977 before running `checkFilterPattern` on `name[index]`? @JillieBeanSim Correct me if I'm wrong, but `checkFilterPattern` appears to be all about seeing if `dsName` includes, startsWith, or endsWith something, so perhaps we can skip the function altogether if `dsName` is `undefined`. So something like:

Screen Shot 2021-01-28 at 4 36 11 AM

Although there is an `if (dsName)` being done within `checkFilterPattern` on a nested block, it seems the code within this block only changes the outcome when`dsName` is equal to some component of the queried dataset/member names. In the case of the user doing a member filter on a data set that doesn't exist, `dsName` would either be equal to `'No datasets found'` or `undefined`, neither of which are valid queries.

I would welcome adding comments to this code when we get a chance.

**Comment by JillieBeanSim** [comment]
@lauren-li @katelynienaber the issue has been addressed in latest commit

**Review by katelynienaber — APPROVED** [review]
The issue is fixed for me. Thanks @JillieBeanSim!

**Comment by JillieBeanSim** [comment]
> > @katelynienaber what I could do right now is make sure add to favorites doesn't show in context menu for data sets that have a filter search on them and we could bring in this functionality in the future
> 
> I'm okay with this. Let's open an issue so we won't forget.

Thanks for creating the issue @katelynienaber https://github.com/zowe/vscode-extension-for-zowe/issues/1164

**Comment by lauren-li** [comment]
> @lauren-li @katelynienaber the issue has been addressed in latest commit

Thanks @JillieBeanSim, testing now!

**Review by lauren-li — APPROVED** [review]
The issue I mentioned above is fixed, and this PR looks good to me now! All unit and expected integration tests are passing, and I have not found any other issues in testing various combinations of data set and member filtering searches.

Thank you @JillieBeanSim for your hard work on this PR! It is very awesome to be able to filter by data set members now.

~
One thing we should note in our documentation of this new feature is the current limitations: favoriting functionality is currently not available for filtered data sets and data set members. Also, favorited searches with a member filter will return all members of the parent data set.

**Pull request merged**
