### PR TITLE
Standardize delete confirmations for USS & Job trees

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

This PR is a small part of the issue #1485 and should not close the issue.

This PR brings in the standardization of the VSC deletion prompt for the USS and Jobs tree.

## Release Notes

Milestone: 1.20.0

Changelog: Add Visual Studio Code's standard deletion prompt for the USS and Job trees.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by katelynienaber — CHANGES_REQUESTED** [review]
Hello! The dialog works fine. I noticed that the delete key on the keyboard will make the confirmation dialog pop up in data sets/jobs, but it doesn't work in USS. Is this an issue related to this PR?

The delete option in the context menu works in all 3 trees though.

**Comment by JillieBeanSim** [comment]
> Hello! The dialog works fine. I noticed that the delete key on the keyboard will make the confirmation dialog pop up in data sets/jobs, but it doesn't work in USS (like, the delete key does nothing in USS, but it will delete things in DS/jobs views). Is this an issue related to this PR?
> 
> The delete option in the context menu works in all 3 trees though.

Hey @katelynienaber would have to check against master to see if the same issue is present there, I don't believe I touched anything dealing with quick/shortcut keys just the type of dialog that was used.

**Comment by JillieBeanSim** [comment]
@katelynienaber I did check the master branch and the same issue is present so I created this issue to address it https://github.com/zowe/vscode-extension-for-zowe/issues/1510

**Review by katelynienaber — APPROVED** [review]
LGTM! Thanks @JillieBeanSim :)

**Review by jellypuno — APPROVED** [review]
Looks good to me! Thank you @JillieBeanSim

**Pull request merged**
