### PR TITLE
Port main changes to next

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Bring changes from `2.11.1` to `2.12.0` from `main` branch of Zowe Explorer into `next` branch for our upcoming pre-release 2 of `3.0`

## Release Notes

Milestone: v3.0 pre-release 2

Changelog: bring changes from main into next (v2.11.1 -> 2.12.0)

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
Heads up @JillieBeanSim @zFernand0 @t1m0thyj have a couple comments on failing checks here:

1. I discussed with @traeok about that failing check on circular dependencies and we'll have to address this in a separate PR, feel free to add more comments on this Trae!
2. Theia check fails due to `build:integration` script still calling v1 profile functions, these were removed for v3 preparations to remove support for v1 profiles
3. Failing SonarCloud check is due to already exisiting duplications from tests being ported

**Comment by rudyflores** [comment]
Quick reminder as well, the Persistent object for history is currently still using VS Code settings for storing these properties, this is a known issue which just needs me to bring back the Local Storage code in a separate PR I will create once this is merged :)

**Comment by zFernand0** [comment]
> Heads up @JillieBeanSim @zFernand0 @t1m0thyj have a couple comments on failing checks here:
> 
> 1. I discussed with @traeok about that failing check on circular dependencies and we'll have to address this in a separate PR, feel free to add more comments on this Trae!
> 2. Theia check fails due to `build:integration` script still calling v1 profile functions, these were removed for v3 preparations to remove support for v1 profiles
> 3. Failing SonarCloud check is due to already exisiting duplications from tests being ported

For number `#2`
- I was hoping to address this in a draft PR I have open.
- https://github.com/zowe/vscode-extension-for-zowe/pull/2529
- Here I update some dependencies to allow for other checks to pass 😋 
- Also, no circular dependency failures on said PR 😋

**Review by zFernand0 — APPROVED** [review]

**Comment by rudyflores** [comment]
> * fix(cd): Workflow and Dependency Updates #2529

That sounds good! 

As for the circular dependencies this seems to be a problem in `main` as well, this is due to `IZoweTree` and `IZoweTreeNode` importing each other
image

image

**Review by JillieBeanSim — COMMENTED** [review]
I believe the file ZoweExplorerApi.ts shouldn't be added,  I think it was changed to the interface.ts file in the extend directory.

**Comment by rudyflores** [comment]
I ran this command locally for the failing sample check `for dir in samples/*; do pushd $dir && pnpm --ignore-workspace i && pnpm run compile && popd; done` and seems to work just fine, for some reason it seems to be failing in the check itself though, @traeok any thoughts on this?

**Comment by traeok** [comment]
> I ran this command locally for the failing sample check `for dir in samples/*; do pushd $dir && pnpm --ignore-workspace i && pnpm run compile && popd; done` and seems to work just fine, for some reason it seems to be failing in the check itself though, @traeok any thoughts on this?

Looks like the `menu-item-sample` cannot find Zowe Explorer API: 
image

Maybe the `package.json` for that sample cannot find the API package? I think it is set up to pull from NPM though, so not sure why it wouldn't be able to find the API...

**Comment by rudyflores** [comment]
> > I ran this command locally for the failing sample check `for dir in samples/*; do pushd $dir && pnpm --ignore-workspace i && pnpm run compile && popd; done` and seems to work just fine, for some reason it seems to be failing in the check itself though, @traeok any thoughts on this?
> 
> Looks like the `menu-item-sample` cannot find Zowe Explorer API: image
> 
> Maybe the `package.json` for that sample cannot find the API package? I think it is set up to pull from NPM though, so not sure why it wouldn't be able to find the API...

Actually I see that it is symlinking the API package, could this present an issue if we don't bundle the API or build before trying to access it?

image

**Comment by rudyflores** [comment]
> > Actually I see that it is symlinking the API package, could this present an issue if we don't bundle the API or build before trying to access it?
> 
> @rudyflores I noticed that we are pulling it from NPM on `next`, but in this PR we are using the symlink. We should pull ZE API from NPM instead; otherwise, users will have to build the API first before using the samples

I noticed `main` branch does symlinking as well, how come this branch fails 🤔

**Review by t1m0thyj — COMMENTED** [review]
Noticed the circular dependency check is fixing, should we try to fix it?
image

**Comment by rudyflores** [comment]
> Heads up @JillieBeanSim @zFernand0 @t1m0thyj have a couple comments on failing checks here:
> 
> 1. I discussed with @traeok about that failing check on circular dependencies and we'll have to address this in a separate PR, feel free to add more comments on this Trae!
> 2. Theia check fails due to `build:integration` script still calling v1 profile functions, these were removed for v3 preparations to remove support for v1 profiles
> 3. Failing SonarCloud check is due to already exisiting duplications from tests being ported

@t1m0thyj See comment from here :) I go more in detail on this

**Comment by JillieBeanSim** [comment]
@rudyflores theia and checks failing due to existing duplication isn't an issue but we are fixing the circular dependencies as they arise.  Please address in this PR.

**Comment by rudyflores** [comment]
@JillieBeanSim all good to go! no more circular dependencies :)

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @rudyflores for bringing in these updates

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
