### PR TITLE
aligns with @zowe

### PR DESCRIPTION
**Pull request by Colin-Stone**
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
Placeholder. Do we want to switch VSCode to work off @zowe and @latest rather than lts-incremental?.

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Any ideas why the build is barfing regarding the download of ```@zowe/cli```

**Comment by Colin-Stone** [comment]
@MikeBauerCA I think we agreed yesterday to proceed with the switch to VSCode being based off @latest/@zowe rather than @brightside.

**Comment by zFernand0** [comment]
Before merging this PR, we should make sure profiles will continue to work even when using a plugin to securely store their credentials.

**Comment by Colin-Stone** [comment]
Closing this as getting stale but leaving branch for now

**Pull request closed without merging**
