### PR TITLE
feat : Stubbing out Zowe Explorer web extension

### PR DESCRIPTION
**Pull request by benjamin-t-santos**
## Proposed changes
These changes lay the groundwork for a Zowe Explorer web extension. It defines a new `extension.ts` to be run in browser environments, adds a new webpack CLI command to compile `extension.ts` for a browser environment, and edits the prepublish script to perform this task.  

This will allow other web extensions to be dependent on Zowe Explorer. There is no web functionality now, but this is a starting point for those changes. 
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by benjamin-t-santos** [comment]
Tried cloning this pull request ad running`yarn package && yarn install`
Finished with no errors
Correctly compiles the new extension.ts
Locally hosted the web extension in a browser - no problems.

**Comment by JillieBeanSim** [comment]
this is a great first step thanks @benjamin-t-santos.  Do you have a link or some steps you could add for us to make it run the locally hosted web extension in a browser?

**Comment by benjamin-t-santos** [comment]
> this is a great first step thanks @benjamin-t-santos. Do you have a link or some steps you could add for us to make it run the locally hosted web extension in a browser?

Yes! There are three ways to a test a web extension covered on the VSCode API docs: https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension

The first way is in the local debugger - I have not configured this in the `launch.json` but I can if desired/needed. It is not my favorite as it is not actually running out of a web browser.

The second way is running this command in a terminal:
`npx @vscode/test-web --extensionDevelopmentPath=$extensionFolderPath $testDataPath`

The last way is hosting your extension files on a local host and installing them via vscode.dev. This has a few steps but the link does a really good job explaining it.

Let me know if you have more questions. Feel free to add a vscode.window.showInformationMessage("test") or some similar line of code to the src/web/extension.ts file if you want to be sure that extension actually activates :)

**Review by JillieBeanSim — APPROVED** [review]
This is a great start @benjamin-t-santos, thank you.

**Review by zFernand0 — APPROVED** [review]
I agree that this is a good starting point!
Thanks! 👍

**Pull request merged**
