### PR TITLE
470 rename data sets and members performance fix

### PR DESCRIPTION
**Pull request by CForrest97**
Fixes rename problems found in #470 (not copy/paste)
When renaming a member, just the member is refreshed instead of the entire data set
Similary when renaming a data set, only the data set is refreshed instead of the parent node

### CODE REVIEW

**Comment by zFernand0** [comment]
Thinking purely about test refactoring: `Maybe we could capture this in a unit test?`
It may be too idealistic, however it'd be nice if we were able to restructure the tests in a way that we can isolate the specific module/function we are testing (in this case the refresh of the node instead of the parent). :smile:

**Comment by jellypuno** [comment]
I will run this PR again, I can't see the coverage on this. Please don't merge it yet.

**Comment by jellypuno** [comment]
@zFernand0 For some reason, coverage is not available :(

**Comment by zFernand0** [comment]
> For some reason, coverage is not available :(

Am I missing something here?
https://wash.zowe.org:8443/job/zowe-cli-vscode-extension/job/PR-571/8/Zowe_20Explorer_20-_20Unit_20Test_20Coverage_20Report/

If you are referring to the codecov report, it seems that the hash of the commit is no longer valid do to a force-push (not necesarely on this repo but on the base/master branch in this case)

**Comment by Colin-Stone** [comment]
> and0 For some reason, coverage is not available :(

Because of this type of issue I always check the unit test results in the job to ensure that we don't have any reduction in coverage. The number I always check is the one that is currently 91.39%. We can allow a small deviation but I don't think it should drop below 90%

image

**Comment by jellypuno** [comment]
Thank you @Colin-Stone @zFernand0. I'm looking for the results in codecov.io but I can't find it so I was confused 😄 

But anyways, @CForrest97 Is it ok to right some test to cover this code?

Capture

**Comment by CForrest97** [comment]
> Thank you @Colin-Stone @zFernand0. I'm looking for the results in codecov.io but I can't find it so I was confused 😄
> 
> But anyways, @CForrest97 Is it ok to right some test to cover this code?
> 
> Capture

Hi Jelly, I have added a couple of tests which cover these lines

**Pull request merged**
