### PR TITLE
Prepare v2.12.0 release

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — APPROVED** [review]
I've been using the "main VSIX" for a couple of days to prepare for the system demo, as well as to leverage sort/filtering in my day-to-day environment. I haven't run into any issues.

LGTM, thanks @JillieBeanSim!

**Review by rudyflores — DISMISSED** [review]
Created a PR against this branch for a bug I found with writing to credential manager, seems like if setting the secure setting to off it wouldn't set the override to `false` https://github.com/zowe/vscode-extension-for-zowe/pull/2535

**Comment by adam-wolfe** [comment]
Issue with sorting PDS members in descending order: https://github.com/zowe/vscode-extension-for-zowe/issues/2536

**Review by rudyflores — APPROVED** [review]
LGTM! Thanks to everyone that helped review the last minute finds on bugfixes!

**Review by zFernand0 — CHANGES_REQUESTED** [review]
Seems like we are ready to go.
LGTM! 😋 

The only reason for requesting changes it to give Ana and others a chance to look over the changelog updates (which will be our release notes eventually)
👀 @anaxceron

**Review by anaxceron — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
