### PR TITLE
2.11.1 release

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

prepare 2.11.1 patch release

## Release Notes

Milestone: 2.11.1

Changelog: n/a

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks @JillieBeanSim!

**Comment by JillieBeanSim** [comment]
@traeok please double check the CHANGELOG for correctness and for fixes to actually exist on this branch.  I saw the fix for submit JCL that I put in and thought I had done it against main, sure enough I had and when checking if it had been brought over the changes weren't in the code like in [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2453/files)

**Comment by traeok** [comment]
> @traeok please double check the CHANGELOG for correctness and for fixes to actually exist on this branch. I saw the fix for submit JCL that I put in and thought I had done it against main, sure enough I had and when checking if it had been brought over the changes weren't in the code like in [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2453/files)

@JillieBeanSim sorry about that, I did not realize that I added the entry back to the changelog while rebasing from `main` to `maintenance` in #2481. But I am still curious, would we not want to merge this "submit JCL" fix into `maintenance` as well? I was under the impression that we would also copy these fixes into `maintenance`.

**Review by traeok — APPROVED** [review]

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim sorry about that, I did not realize that I added the entry back to the changelog while rebasing from `main` to `maintenance` in #2481. But, I'm a bit confused - wouldn't we want to merge this "submit JCL" fix into `maintenance` as well? I was under the impression that we would also copy these fixes into `maintenance`.

Hey @traeok no worries, I thought maybe someone brought it over but when checking for the appropriate code changes they weren't there.  I kept that PR against main for 2.12.0 because it wasn't a high priority fix and got merged in before we discussed the 2.11.1 with the included fixes that were high priority.  2.12.0 is in just a couple weeks so nothing to worry about that should slow the 2.11.1 fix release, what do you think?

**Comment by traeok** [comment]
> no worries, I thought maybe someone brought it over but when checking for the appropriate code changes they weren't there. I kept that PR against main for 2.12.0 because it wasn't a high priority fix and got merged in before we discussed the 2.11.1 with the included fixes that were high priority. 2.12.0 is in just a couple weeks so nothing to worry about that should slow the 2.11.1 fix release, what do you think?

@JillieBeanSim Oh ok, I was thinking of `maintenance` as a branch for bug fixes. I think it could be a bit cumbersome to port all the fixes into maintenance after merging into main, so I think its fine to leave it for high-priority fixes/patch releases.

Tested this PR and everything is working as intended, just needs one more review 👍

**Review by t1m0thyj — DISMISSED** [review]

**Review by rudyflores — DISMISSED** [review]
Could we include this fix as well in this release? https://github.com/zowe/vscode-extension-for-zowe/pull/2501 

This fix is crucial since we want web users to also be able to load the edit attributes view

**Review by traeok — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]

**Comment by adam-wolfe** [comment]
I noticed that the changelog does not include:
`- Fixed submitting local JCL using command pallet option `Zowe Explorer: Submit JCL` by adding a check for chosen profile returned to continue the action. [#1625](https://github.com/zowe/vscode-extension-for-zowe/issues/1625)`

This was added in #2474. Should this be in the changelog for 2.11.1?

**Comment by JillieBeanSim** [comment]
> I noticed that the changelog does not include: `- Fixed submitting local JCL using command pallet option 'Zowe Explorer: Submit JCL' by adding a check for chosen profile returned to continue the action. [#1625](https://github.com/zowe/vscode-extension-for-zowe/issues/1625)`
> 
> This was added to the changelog in #2474. Should this be in the changelog for 2.11.1?

@adam-wolfe he had accidentally grabbed the changelog from main but the code changes from [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2453) aren't on this branch so removed the changelog item

**Comment by adam-wolfe** [comment]
> > I noticed that the changelog does not include: `- Fixed submitting local JCL using command pallet option 'Zowe Explorer: Submit JCL' by adding a check for chosen profile returned to continue the action. [#1625](https://github.com/zowe/vscode-extension-for-zowe/issues/1625)`
> > This was added to the changelog in #2474. Should this be in the changelog for 2.11.1?
> 
> @adam-wolfe he had accidentally grabbed the changelog from main but the code changes from [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/2453) aren't on this branch so removed the changelog item

Gotcha, thanks @JillieBeanSim

**Review by awharn — APPROVED** [review]

**Review by rudyflores — APPROVED** [review]

**Pull request merged**
