### PR TITLE
fix(ds/sort): Fallback to sorting by name when values are equal

### PR DESCRIPTION
**Pull request by traeok**
_If we would prefer to keep this for a potential 2.12.1 release, then I will add a changelog. Otherwise, I think we can keep this as `no-changelog` as the feature will be released with 2.12._

---

## Proposed changes

I've cleaned up the sorting function a bit so that it falls back to sorting by name when 2 node values are equal.

In addition, I've adjusted the date checks slightly to also use Day.js (consistent with the rest of the date processing for this feature) for easier date comparison.

## Release Notes

Milestone: 2.12.0 (or 2.12.1)

Changelog:

- Fixed an issue where sorting functionality did not consider the sort direction when values were equal.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Review by zFernand0 — COMMENTED** [review]
Seems like this would work.
testing briefly before approving.

**Review by adam-wolfe — DISMISSED** [review]
LGTM. Thanks Trae!

**Comment by adam-wolfe** [comment]
One minor issue I am seeing that may be related to this is that if a member has no user ID, and you sort by User ID in the descending order, the member without a user ID will switch to the top and bottom of the list when you collapse and expand the PDS.

**Comment by traeok** [comment]
> One minor issue I am seeing that may be related to this is that if a member has no user ID, and you sort by User ID in the descending order, the member without a user ID will switch to the top and bottom of the list when you collapse and expand the PDS.

Thanks for catching this, I've addressed this in [9235f28](https://github.com/zowe/vscode-extension-for-zowe/pull/2538/commits/9235f28b8bff80ad1d6816c881c1f7d2385888cc)

**Review by rudyflores — DISMISSED** [review]

**Review by adam-wolfe — APPROVED** [review]
Looks good.

**Comment by traeok** [comment]
I found an issue with how we generally build children in `ZoweDatasetNode` - we were only checking for `dsname` as part of the "existing node" check, where we should fallback to look for the `member` variable when `dsname` isn't present. Otherwise, the check for an existing PDS member node will always yield undefined. See 2da3995 for the change that was made.

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Thanks for addressing the comments

**Review by adam-wolfe — APPROVED** [review]

**Pull request merged**
