### PR TITLE
update isTheia check to reduce false positives

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Update isTheia check to reduce false positives.

## Release Notes

Milestone: 2.6.0

Changelog: Updated check for Theia environment to reduce false positives in different environments.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
cherry picked commit with audit fix https://github.com/zowe/vscode-extension-for-zowe/pull/2051/commits/53aebe11d068f09a665443cb5db348f7247003de

**Comment by zFernand0** [comment]
> cherry picked commit with audit fix [53aebe1](https://github.com/zowe/vscode-extension-for-zowe/commit/53aebe11d068f09a665443cb5db348f7247003de)

Now that there is a fixed version of the FTP plugin on NPM, should we try to update it to `2.1.2` and remove the resolution?

**Review by rudyflores — DISMISSED** [review]
LGTM! I will have to re-evaluate the code here as well since for PR #2073 I will be refactoring some of this code as well.

Thanks @JillieBeanSim !

**Review by traeok — APPROVED** [review]
LGTM! Thanks @JillieBeanSim 😄

**Pull request merged**
