### PR TITLE
Quick fix for Issue 1088: Error in retrieving jobs when using profiles with tokens

### PR DESCRIPTION
**Pull request by jellypuno**
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

## Proposed changes

Quick fix for Issue #1088 1088: Error in retrieving jobs when using profiles with tokens

- If JOBID is clicked then the Jobs will search for the JobID

- For profiles that doesn't have a user, a value of * is set to the owner during initialization

Untitled

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

There's an error that I found in the FTP extension and I posted more information in the issue itself

### CODE REVIEW

**Review by katelynienaber — APPROVED** [review]
Works like a dream! From favorites too. Thanks @jellypuno

**Review by JillieBeanSim — COMMENTED** [review]
@jellypuno I am getting some weird behavior on this branch, I have the profile that matches with base profile working but now all of my other profiles are coming back as inactive :(
this may deal with the last PR that just got merged in, I only tested the profile I was having issues with and not others sorry

**Comment by jellypuno** [comment]
@JillieBeanSim Can you try to disable your other extensions, if they are still enabled?

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim Can you try to disable your other extensions, if they are still enabled?

I did have to disable ftp extension as no profiles would load while I had it enabled, and not just disable I had to uninstall the ftp cli.  but the above mentioned issue is also happening with another zosmf profile I have on a diff host than the one the base profile covers and no rse profiles will work

**Comment by jellypuno** [comment]
@JillieBeanSim I see. ok. let me try it out

**Comment by jellypuno** [comment]
@JillieBeanSim I'm trying it out and it is not happening for me. What is inside your zosmf profile?

**Comment by JillieBeanSim** [comment]
hey @jellypuno I think I had something cached in vs code, restarted vs code and don't see the issue anymore *whew sorry for raising the alarm

**Comment by jellypuno** [comment]
@JillieBeanSim That's great news!

**Review by JillieBeanSim — APPROVED** [review]
@jellypuno this LGTM, thanks for putting in the fix.  

Glad it saved the other approval as I accidentally hit re-request on wrong name

**Comment by jellypuno** [comment]
Thank you for testing and approving this @JillieBeanSim  🎉

**Pull request merged**
