### PR TITLE
fix(cicd): Update deployment workflow

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

Add the `install` and `build` steps in the deployment workflow

## Release Notes

Milestone: N/A

Changelog: N/A

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
Screenshot 2023-10-10 at 9 57 42 AM
@zFernand0 is it normal for the changelog check to fail this way?

**Review by traeok — DISMISSED** [review]
thanks @zFernand0 👍

**Comment by zFernand0** [comment]
> Screenshot 2023-10-10 at 9 57 42 AM zFernand0 is it normal for the changelog check to fail this way?

yeah, I was able to reproduce it locally😋 
still investigating

It seems like this happened in the PR before merging (#2424) but I mistakenly assumed this was due to no changelog, or something to that effect.

**Comment by zFernand0** [comment]
In order to fix this, we will have to add the ability for the check_changelog action to support pnpm since we `npx only-allow pnpm`  on preinstall.
This commit (cb07fa1fff0d01bb99cf688016f992379c2a3c8c) is a good example of what"m about to suggest in a PR to the GH Action 😋 

FWIW, I tested with the `npx only-allow pnpm`, but something must be still running that (or I had a caching problem) but npx command still didn't work 😋

**Comment by zFernand0** [comment]
Changelog check back to normal
https://github.com/zowe/vscode-extension-for-zowe/actions/runs/6471143280/job/17568932624
Thanks @awharn and @traeok for the quick turnaround 😋

**Review by JillieBeanSim — APPROVED** [review]

**Comment by zFernand0** [comment]
image

---

This is similar to what happened with the changelog action

Working on a quick fix 😋

**Pull request merged**
