### PR TITLE
Issue #904: Implement Allocate Like in Explorer

### PR DESCRIPTION
**Pull request by katelynienaber**
## Proposed changes

[Issue #904](https://github.com/zowe/vscode-extension-for-zowe/issues/904): Added Allocate Like command to data set context menus & command palette.

If the data set specified by the user to copy from doesn't exist, an error from the API will be shown.

allocateLike

## Release Notes

Milestone: 1.9
Changelog: Added Allocate Like command to data set context menus & command palette

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `npm run vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by katelynienaber** [comment]
Failures are due to some dependency issues...

**Comment by zdmullen** [comment]
So one question with this-- what if users don't have the proper release of zOSMF? From the documentation I can see that allocate like is available "V2R3 and V2R4 at 2020/4 with APAR PH22030." 

As this is the case, if a user has an older version of zOSMF, will the function be grayed out? Is there even a check for that? 

From what I can imagine, we should determine what the error message is when the Rest call is not available, and document this particular scenario. Thoughts?

**Comment by katelynienaber** [comment]
> So one question with this-- what if users don't have the proper release of zOSMF? From the documentation I can see that allocate like is available "V2R3 and V2R4 at 2020/4 with APAR PH22030."
> 
> As this is the case, if a user has an older version of zOSMF, will the function be grayed out? Is there even a check for that?
> 
> From what I can imagine, we should determine what the error message is when the Rest call is not available, and document this particular scenario. Thoughts?

Unfortunately it seems that if we try to send a REST request with an invalid field name, it just gives us error 500:
image

I tried this with the CLI system tests as well as with Postman.

I did NOT try to send a request with more than just the faulty "like" field. I didn't, because if you are allocating like, this is the only parameter you will use. All other parameters are related to data set properties. Please let me know if you think this is a faulty assumption and I will try again :)

Alex mentioned that: "a sysprog would check the zosmf logs and see exactly to what is related..." but if the user is not a sysprog then they might not know what is going on.

Maybe we could add a note to the error? Like if allocateLike returns 500, we say something like:
**Note: This command requires zOSMF v2.4.0 or higher**

**Comment by Alexandru-Dumitru** [comment]
@katelynienaber Your assumption was good. I think we should not go down the rabbit hole of interpreting the errors on behalf of the user. Looking in the documentation for that specific RC and Reason, I got this (page 573):
```
rc: 4 
reason: 13
message: Incorrect parameter was specified.
description: The request contained one or more parameters that are not valid.
```
If they do this basic root cause analysis they should be fine, in my opinion.
Info extracted from: https://www-01.ibm.com/servers/resourcelink/svc00100.nsf/pages/zOSV2R4sc278420/$file/izua700_v2r4.pdf

**Comment by jelaplan** [comment]
Wrt to the 500 error, I'm not sure if you will add some nuance or take Alex advise to not go down the rabbit hole.  I'm a fan of trying to improve because the error messages are so unhelpful. We are trying to modernize the MF experience so 1960s messages don't fit.  

A simple improvement is to state that the command is not available on your Mainframe system and contact your system team to update your version of zOSMF TO V2.4.0+.  That way they could stop trying to make it work.

**Comment by katelynienaber** [comment]
Hi John,

I will probably go with Alex's method, for 2 reasons.

First, the 500 error is very general and just means the server was unable
to complete the request. The user could get this error for some other
reason, and our clarifying message would maybe tell the user the wrong way
to fix it.

Also, we would have to keep updating our error messages whenever IBM added
something new. For example, if the user IS able to use the allocateLike
command, but has some other problem with their request/connection to zOSMF,
we would still tell them that they need a different version of zOSMF to use
the command.

So ideally IBM should update their own error messages so they make sense to
newbies :)

Thanks,
Katelyn Nienaber
Software Engineer | Mainframe Division
CA Technologies, A Broadcom Company
Phone: +420 226 207 737 ext. 7737
CA CZ, s.r.o. | V Parku 2316/12 Chodov | Praha 4, 148 00 Czech Republic
Katelyn.Nienaber@broadcom.com | broadcom.com
Identification No. 25694073, registered in the Commercial Register
maintained by the Municipal Court in Prague in Section C, Insert No. 61808


Dne po 17. 8. 2020 16:11 uživatel John laPlante <notifications@github.com>
napsal:

**Comment by katelynienaber** [comment]
> I'm not sure I love the label in the right+click, Allocate Like (New File with Same Attributes), but it is the clearest. LGTM

I'm also not super pleased with how long it is...if you guys prefer something from @jelaplan's list, I can change it :)

- Allocate Like (Copy File Type)
- Allocate Like (Copy File Format)
- Allocate Like (New File with Same File Format)
- Allocate Like (Copy DS Characteristics)
- Allocate Like (Copy File Details)
- Allocate Like (Copy File Attributes)
- Allocate Like (New File with Same Attributes)
- Allocate Like (New Dataset)
- Create New Dataset Modelled on This
- New Dataset with the Same Format
- Create New Dataset Like This One

**Comment by jellypuno** [comment]
@katelynienaber I'm trying to run build but I am having failures. Do I need to install something? I have the latest version of Zowe CLI.

image

**Review by crawr — COMMENTED** [review]
Functionality works great for me for sequential and PDS, both in VSCode and in Theia.

However, I see that the method is also implemented in the context menu of data set members. I think this should be removed since you don't really allocate members, you simply create a new one under an allocated PDS.

**Comment by jellypuno** [comment]
> Functionality works great for me for sequential and PDS, both in VSCode and in Theia.
> 
> However, I see that the method is also implemented in the context menu of data set members. I think this should be removed since you don't really allocate members, you simply create a new one under an allocated PDS.

I agree. An error message appears when you try to allocate like under members

**Comment by jellypuno** [comment]
I found several issues:
1. Delete datasets (PD and PDS) are not working. It is working in master
2. Errors in Integration tests as well connected to delete.

**Comment by katelynienaber** [comment]
> I found several issues:
> 
> 1. Delete datasets (PD and PDS) are not working. It is working in master
> 2. Errors in Integration tests as well connected to delete.

This should be fixed now..somehow master got merged into this branch but without the fix for delete.

**Comment by katelynienaber** [comment]
> Functionality works great for me for sequential and PDS, both in VSCode and in Theia.
> 
> However, I see that the method is also implemented in the context menu of data set members. I think this should be removed since you don't really allocate members, you simply create a new one under an allocated PDS.

2nd push removes the Allocate Like option from the member context menu :)

**Comment by jellypuno** [comment]
Delete is working as expected. Thanks for fixing. I found 1 more.

- Allocating through favorites doesn't work

AllocLike

**Comment by katelynienaber** [comment]
> Delete is working as expected. Thanks for fixing. I found 1 more.
> 
> * Allocating through favorites doesn't work

Fixed!

**Review by AndrewTwydell — APPROVED** [review]
LGTM 👍

**Review by crawr — APPROVED** [review]
Thanks for addressing my comment re: members. Allocating under favorites worked for me.

**Pull request merged**
