### PR TITLE
[next] Set user and password as secure after prompting

### LINKED ISSUE #1288: Implement `zowe config secure` to store credentials
TBD: Implement `zowe config secure` to store credentials

### PR DESCRIPTION
**Pull request by crawr**
Signed-off-by: Richelle Anne Craw <richelleanne.craw@broadcom.com>

## Proposed changes

Fixes #1288 

Previously, the user and password prompt only stores the credentials for the session. 

This PR uses the config set API to store user and password as secure when the fields are defined as such in the config file. 

teamconfigsecure

## Release Notes

Milestone: vNext

Changelog: Set user and password as secure after prompting

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jellypuno — DISMISSED** [review]
works great!

**Review by JillieBeanSim — COMMENTED** [review]
@crawr how are we handling multiple lpars in the config file now?

I tried something similar to this where `zosmf2` has a different host with it's own secure fields but it tries to use the base profile secure creds to authenticate which fails
image

**Comment by crawr** [comment]
Thanks for showing me that use case @JillieBeanSim . This should be fixed with the latest commit.

This PR will store credentials securely if the service profile contains the user and password in the secure array. 
If your service profile does not have any fields in the secure array, the user will be prompted for credentials for each session. 
In your example, `zosmf` will be prompted for each session, and `zosmf2` credentials will be stored in the vault.

An enhancement is planned for this due to the `auto-store` [feature](https://github.com/zowe/imperative/pull/684) being implemented by the CLI squad. In this enhancement, if auto-store is true and the base profile contains user and password in the secure array, once you enter credentials for `zosmf`, they will be stored under the base profile location in the vault.
We will handle this in a different PR under issue #1541 .

**Review by jellypuno — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
Thanks for the update @crawr, so it seems that right now it will only handle a single secured set of credentials but the catch/update creds helps incase the user is using multiple lpars with secured creds atm.  looking forward to the `auto-share` update.

**Pull request merged**
