### PR TITLE
Feature/multi select/context menu/uss

### PR DESCRIPTION
**Pull request by KutluOzel-b**
## Proposed changes

Added multiple selection to USS view context menu 

-  pull from mainframe
- add to fav
- refresh directory
- toggle binary / toggle text 
- delete node 

Fix error in check fav files when deleting node

## Release Notes

Milestone:

https://github.com/zowe/vscode-extension-for-zowe/issues/1428

completed USS view part 

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x ] There is coverage for the code that I have added
- [ x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
@KutluOzel-b it looks like we have an issue with the DCO signoff, steps to fix are here https://github.com/zowe/vscode-extension-for-zowe/pull/1882/checks?check_run_id=7528132239

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
Since the multi-select is an enhancement, I tagged this one for 2.3.0 instead of the hot fix release 2.2.1.  Left as Request changes just so we don't merge it in before the hot fix release items

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
With multi-delete I believe in dataset tree user is presented with a single confirmation message with all listed vs a confirmation for each file.  The delete of multiple or single is hit and miss, was not prompted for confirmation with 2 directories selected
Screen Shot 2022-08-15 at 1 12 02 PM

With multiselect toggle binary I notice a rejected promise error in the debug console, but functionality seems to be working.

**Comment by KutluOzel-b** [comment]
> With multi-delete I believe in dataset tree user is presented with a single confirmation message with all listed vs a confirmation for each file. The delete of multiple or single is hit and miss, was not prompted for confirmation with 2 directories selected, tried to delete multiple times but nothing happened. Screen Shot 2022-08-15 at 1 12 02 PM
> 
> With multiselect toggle binary I notice a rejected promise error in the debug console, but functionality seems to be working.

Thank you @JillieBeanSim good catch :+1: . I made the proper modifications. Could you please take a look if those are met now ? 

Thanks in advance ☺️

**Comment by zFernand0** [comment]
Regarding the DCO signoff...
Fixing the DCO is proving to be a bit more difficult in this case.
It seems like going forward this won't be an issue anymore.

However, for this instance, I propose we Squash this PR once it's ready to be merged.

Why is this so complicated? 
The DCO issue happened before the master to main rename.
The fact that we do not rebase branches (instead we `Update branch` i.e. `git pull`), causes the commit history to be intertwined.
In order to fix the DCO, we need to do a rebase which will try to converge both histories (master and main) into one.

**Comment by JillieBeanSim** [comment]
@zFernand0 @KutluOzel-b the DCO looks to be fixed so don't think we need to squash, all tests are passing.  I will have this reviewed by next scrum.  Thanks all for your work on this!

**Review by JillieBeanSim — APPROVED** [review]
LGTM! Thanks @KutluOzel-b for the updates, this enhancement is awesome!

**Comment by zFernand0** [comment]
the changes LGTM, however IDK if I'm allowed to approve this PR 😋

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
