### PR TITLE
Bug Fix: Create/Update Profile Esc Error on Host Input

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Bug fix to return expected error message `No valid value for z/OS URL. Operation Cancelled` instead of shown error when a user escapes the host text box during creation or updating of a profile.

image

## Release Notes

Milestone: 1.18

Changelog: Bug fix to return expected error message `No valid value for z/OS URL. Operation Cancelled` instead of shown error when a user escapes the host text box during creation or updating of a profile.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## GIF

create-update-esc-fix

### CODE REVIEW

**Comment by jellypuno** [comment]
@JillieBeanSim dataset and jobs is also fixed? They are experiencing this problem as well

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim dataset and jobs is also fixed? They are experiencing this problem as well

Where is this happening in datasets and jobs?  This fix will be reflected in Create and Update profile across all trees.

**Review by lauren-li — APPROVED** [review]
This PR looks good to me! In manual testing, it got rid of the errors I was seeing in 1.17.0 when cancelling in the middle of updating a profile, and also provided the appropriate info message when cancelling in the middle of creating a profile. This was true for all three views (Data Sets, USS, and Jobs). All unit tests are passing. My integration tests are still acting up, but @JillieBeanSim was kind enough to run them for me and show that all expected integration tests were passing. (@jellypuno feel free to double-check behind us!)

Thanks @JillieBeanSim for this fix!

**Review by lauren-li — APPROVED** [review]
This looks good to me still! Thanks @JillieBeanSim for the fix!

**Review by crawr — APPROVED** [review]
LGTM. I tested this manually and the functionality works for me. Theia tests also passed for me locally. Thanks @JillieBeanSim

**Pull request merged**
