### PR TITLE
Added cli dependency to api

### PR DESCRIPTION
**Pull request by phaumer**
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>

## Proposed changes

Fix for https://github.com/zowe/vscode-extension-for-zowe/issues/1410. This could be published as 1.18.1.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

To test this you must update the version number in <https://github.com/zowe/vscode-extension-for-zowe/blob/added-cli-dependency-to-api/packages/zowe-explorer-api/package.json> and build it yourself and include the resulting tar file as a file dependency. Otherwise it will continue using the package from npm or your node_modules. This is another pain point related to https://github.com/zowe/vscode-extension-for-zowe/issues/1444

### CODE REVIEW

**Review by AndrewTwydell — APPROVED** [review]
This has resolved the Zowe CLI dependency error I was getting before with the CICS extension build! 👍🏼 

Thanks @phaumer! 😃

**Review by lauren-li — COMMENTED** [review]
Following the instructions in this PR description's "Further Comments" section, I was able to successfully build the Zowe Explorer API tgz file and use it as a dependency for the Zowe CICS extension (`autoread-regions` branch).

However, when running the `yarn package` command, I noticed that the `yarn.lock` file gets updated to include the Zowe CLI dependency. Should that be included as part of this PR? I got errors (FTP extension) when trying to package the tgz without changing the API's `package.json` version number (which I know we are avoiding to prevent prematurely triggering the deploy script).
- Would it make sense to just discard the `package.json` change after running `yarn package`, and just commit the updated `yarn.lock` file into this PR?

Thanks @phaumer for addressing the issue so quickly!

**Comment by phaumer** [comment]
@lauren-li I did not expect the lock file to be updated as we already had that dependency in the parent package.json. This fix just copied it down so that a standalone npm distribution will also work. 

Can you post your specific diff that you see? Running yarn does not change the file for me.

**Comment by lauren-li** [comment]
@phaumer It might be a version difference due to the `^`. I just noticed that the differences (additions) I got in `yarn.lock` are of dependencies that were already in the file, but just a higher version:

Screen Shot 2021-08-18 at 1 50 45 PM

**Comment by phaumer** [comment]
I added that so that the extenders can work with a newer version, but did not want to switch for us.

**Review by lauren-li — APPROVED** [review]
This PR looks good to me now. With the `^` removed, I am still able to successfully build the Zowe Explorer API tgz file and use it as a dependency for the Zowe CICS extension. I no longer get the changed `yarn.lock` file (although I did also have to update the Zowe Explorer and FTP extension packages to use Zowe Explorer API 1.18.1 - however, all of these version numbers should be incremented in sync with each other as part of the next release preparation PR). All expected unit and integration tests are passing.

@AndrewTwydell also tested this PR again with the latest update, and it is still working well for him. Thanks Andrew!

Thanks @phaumer for the update!

**Pull request merged**
