### PR TITLE
fix(uss/datasets): Reset VSCode multi-select flag after Hide Profile in multi-selection

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This should resolve the bug where VSCode still thinks there is a multi-selection active, even though the nodes in the previous selection were deleted. This typically happens when a user uses "Hide Profile" in a multi-select operation, as it removes the nodes that were previously a part of that selection.

## Release Notes

Milestone: 2.6.1

Changelog:

- Resolves an issue where VSCode did not provide all context menu options for a profile node.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Review by zFernand0 — CHANGES_REQUESTED** [review]
It seems like this works fine for USS and Jobs, but I'm seeing some strange behavior for Datasets 😢 
Here is a quick GIF:
temp

**Comment by traeok** [comment]
> It seems like this works fine for USS and Jobs, but I'm seeing some strange behavior for Datasets 😢 Here is a quick GIF: temp [ temp ](https://user-images.githubusercontent.com/37381190/217015979-ca05a29c-2cf0-4433-9129-c734bc1bc41a.gif) [ ](https://user-images.githubusercontent.com/37381190/217015979-ca05a29c-2cf0-4433-9129-c734bc1bc41a.gif)

🤯 oh wow, that was unexpected. Maybe this is related to #2097 ? I tried to replicate the same steps but am not having this problem when running the build directly from the branch. I will try again with the VSIX file this time and verify.

**Comment by zFernand0** [comment]
> 🤯 oh wow, that was unexpected. Maybe this is related to #2098 ? I tried the same steps but cannot replicate this problem when building from the branch. I also tried this w/ the VSIX and the behavior is working as expected in my environment.

It might be related 😱 
I'm happy to test both PRs combined if you would like me to do so! 😋 
Otherwise, we can sync-up offline 😉

**Comment by traeok** [comment]
> UPDATE: It is related. Testing both PRs together fixes the problem for me 💯

Great, thanks for confirming @zFernand0 !

**Review by zFernand0 — APPROVED** [review]
My label duplication was resolved after testing with #2098.
This PR LGTM! 😋

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Thanks for fixing the merge conflicts! 🥳

**Pull request merged**
