### PR TITLE
feat(ds): Add data set template for generic partitioned data set extended template

### LINKED ISSUE #2600: Add data set creation template for COBOL source codes and compiler listings
**Is your feature request related to a problem? Please describe.**

There are no data set templates to create PDSE data sets to hold a large number of COBOL source code, copybooks, and compiler listings.

**Describe the solution you'd like**

- Provide a default COBOL source code data set creation template that creates a PDSE type of data set to hold a large number of COBOL source codes and copybooks
- Provide a default compiler listing data set creation template that can store the COBOL compiler listings.

### PR DESCRIPTION
**Pull request by patricktiu**
## Proposed changes
- Provide a default COBOL source code data set creation template that creates a PDSE type of data set to hold a large number of COBOL source codes and copybooks
- Provide a default compiler listing data set creation template that can store the COBOL compiler listings

resolve #2600

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

depends on https://github.com/zowe/zowe-cli/pull/1973 PR to be merged which includes new enum values in CreateDataSetTypeEnum

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
Hey @patricktiu thanks for the contribution.  I believe the cli team will not be accepting the proposed changes.  With Zowe Explorer being a UI based product we like the idea of having a new template for creating a PDSE type of data set and exposing that type of capability.  We would like to keep the naming of this new template similar to the naming convention in place, like `Partitioned Data Set: PDSE` with some default PDSE attributes.  We should be able to move forward even without the CLI changes I believe.

Screen Shot 2023-12-12 at 1 14 44 PM

**Comment by patricktiu** [comment]
Hi @JillieBeanSim, 

I will change the code to bring in the two new templates using the existing `zowe.CreateDataSetTypeEnum.DATA_SET_BLANK` enum value without the dependency with the PR in https://github.com/zowe/zowe-cli/pull/1973

Screenshot 2023-12-13 at 1 49 02 PM

**Comment by zFernand0** [comment]
I'm wondering if everyone out there will know that the COBOL and Listing options are PDS/E (`dsntype: library`).

@patricktiu,
Given that the only difference between the two is either the `lrecl` and the `dirblk`,
what are your thoughts on just having a single template called `PDS/E` ?

**Comment by patricktiu** [comment]
Hi @zFernand0, 

The original design is to use FBA format for the Listing data set but since this format is not supported by the CLI yet.  I have to change it to FB.  Once the FBA record format is supported, The Listing data set attributes can be set to recfm=FBA, lrecl=133, and blksize=23930.  The user must make sure the block size is a multiple of record length. I think it is still helpful to have separate templates.

Screenshot 2023-12-14 at 11 01 48 AM

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
Hey @patricktiu, thanks for updating the contribution.  For the built in Zowe Explorer default templates, we would like to keep the naming convention generic but also similar to the existing.  Adding one more template with a generic name like `Partitioned Data Set: Extended` which would match the existing would be good.  Zowe Explorer does offer the option to save custom templates so no reason to add multiple, we would mainly like to easily show users they have the ability to create PDSEs too.

Screen Shot 2023-12-15 at 8 50 07 AM

**Comment by patricktiu** [comment]
Hi @JillieBeanSim & @zFernand0 

Since you both make the same recommendation to have one generic template, I am removing the Listing template and renaming the COBOL template to `Partitioned Data Set: Extended`
pdse

**Review by zFernand0 — APPROVED** [review]

**Review by JillieBeanSim — COMMENTED** [review]
The changes look great @patricktiu. Would you mind adding some more unit tests to bring the coverage up to a passing level? Thanks

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @patricktiu for this new feature

**Review by zFernand0 — APPROVED** [review]

**Review by traeok — APPROVED** [review]
LGTM, thanks @patricktiu! Left a comment regarding assertions in the tests, but not a required change - just wanted to mention for awareness 🙂

**Pull request merged**
