### PR TITLE
[next] Extender load on registration

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

built off of PR https://github.com/zowe/vscode-extension-for-zowe/pull/1435

Fixes the loading of extender profiles upon activation/registration with Zowe Explorer

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by lauren-li — COMMENTED** [review]
Overall, this PR (and the ones it is built on top of) is a good improvement over the current `next` branch. All unit and expected system tests are passing. The extender profiles generally load upon activation for both old and new style profiles. The only exception I found was that for new-style profiles, if I only follow the user/password prompts upon typing `zowe config init` in Zowe CLI, and do not add anything else to the config file,  the extender profiles do not load on Zowe Explorer/extender activation (only the z/OSMF profile loads). However, once I add a hostname into the config file and reload the VS Code window, all extender profile types load without issue upon activation.

Additional profile-related functionality tested for both old and new style profiles included create, update, hide/add existing, Check Credentials, and delete.

One potential regression I found when comparing with the current `next` branch: 
- If I am using the new-style profiles and have incorrect credentials, the "Check Credentials" message comes up, but when I click on the "Check Credentials" button, it seems I am prompted for almost every field *except* my credentials (e.g. base path, protocol, etc.). See gif below:
        
    ze-checkCredsNext

    - On the current `next` branch, for new style profiles, clicking the "Check Credentials" button actually prompts me for user/password. Although clicking "Save" results in an error since it looks for the new-style profile in the profile type's folder (old-style behavior), I can still update and use the credentials for my current session via "Check Credentials".
    - Based on the behavior of other profile create/update/delete functions at this time, we might just want to rewire this button to open the config file when new-style profiles are being used. This PR can either implement this, or if not, return the functionality of the "Check Credentials" button to prompt for user/password again.
    
Thanks @JillieBeanSim for your extensive work on this so far!

**Comment by JillieBeanSim** [comment]
> One potential regression I found when comparing with the current `next` branch:
> 
> * If I am using the new-style profiles and have incorrect credentials, the "Check Credentials" message comes up, but when I click on the "Check Credentials" button, it seems I am prompted for almost every field _except_ my credentials (e.g. base path, protocol, etc.). See gif below:
>   ze-checkCredsNext
>   
>   * On the current `next` branch, for new style profiles, clicking the "Check Credentials" button actually prompts me for user/password. Although clicking "Save" results in an error since it looks for the new-style profile in the profile type's folder (old-style behavior), I can still update and use the credentials for my current session via "Check Credentials".
>   * Based on the behavior of other profile create/update/delete functions at this time, we might just want to rewire this button to open the config file when new-style profiles are being used. This PR can either implement this, or if not, return the functionality of the "Check Credentials" button to prompt for user/password again.
> 
> Thanks @JillieBeanSim for your extensive work on this so far!

@lauren-li is this regression only on this branch or also on previous branches with refactor and update from main?

**Comment by lauren-li** [comment]
> @lauren-li is this regression only on this branch or also on previous branches with refactor and update from main? It will be good to know when this regression happened to help fix it.

I see this in PR #1429,  as well (Refactor use of profiles cache). But I was thinking for now, it might make sense to update one of the PRs so that the "Check Credentials" button opens the config file when new style profiles are being used (similar to what the add/update/delete functions on the `next` branch currently do).

**Comment by JillieBeanSim** [comment]
> > @lauren-li is this regression only on this branch or also on previous branches with refactor and update from main? It will be good to know when this regression happened to help fix it.
> 
> I see this in PR #1429, as well (Refactor use of profiles cache). But I was thinking for now, it might make sense to update one of the PRs so that the "Check Credentials" button opens the config file when new style profiles are being used (similar to what the add/update/delete functions on the `next` branch currently do).

@lauren-li could I get the steps used to reproduce this.  I went back over to the branch #1429 and if I run `zowe config init --global` and don't enter user or pass I get prompted for all missing args, including user, pass, protocol, and so on since I only have port and ru saved in my config file.  This code hasn't changed since `next` branch.  I also get this error after inputting the user & pass on prompt after the search filter is entered (this happens on all trees).  I do not get this error on the `next` branch, so I will look into that but I do get the prompting behavior on `next` branch
image

When I entered the wrong password running the command `zowe config secure --global` I don't get the pop up at all, only receive `no data sets` under the session name in the tree after entering the filter search.  I get this same behavior on the `next` branch.

**Comment by JillieBeanSim** [comment]
@lauren-li if you want to test #1429 & #1435 for consistency with `next` branch that would be good and I can look into the missing host issue for extenders on this branch

**Comment by JillieBeanSim** [comment]
The prompting for extra values and the pop-up or error message for incorrect credentials saved in config file need to be handled in separate stories since I see them happening on `next` branch as well.  I can create these stories.

**Comment by lauren-li** [comment]
> @lauren-li could I get the steps used to reproduce this. I went back over to the branch #1429 and if I run zowe config init --global and don't enter user or pass I get prompted for all missing args, including user, pass, protocol, and so on since I only have port and ru saved in my config file.

@JillieBeanSim Starting from scratch (i.e. no new-style config file):
1. Create a global new-style config file:
    1. In the Terminal, enter `zowe config init --global`.
    2. Follow the prompts, entering **incorrect** credentials. (I only get prompted for user and password.) This is to simulate having incorrect credentials, e.g. because of an expired password.
    3. If you don't get prompted for host/port/rejectUnauthorized information, open the new config file to add that information in.
1. On this PR branch in VS Code, run `yarn`, and then use the Extension Development Host to run it in debug mode.
1. Select the profile with incorrect credentials, and use it to run a search.
1. Receive the "Check Credentials" message, and click the "Check Credentials" button.
1. Observe the resulting prompts. (Mine look like the gif I posted in my earlier [comment](https://github.com/zowe/vscode-extension-for-zowe/pull/1448#pullrequestreview-736056139))

**Comment by JillieBeanSim** [comment]
created issue to capture some of the scenarios we came across while testing `next` & PR branches https://github.com/zowe/vscode-extension-for-zowe/issues/1456

**Review by lauren-li — APPROVED** [review]
This PR looks good to me! All unit and expected integration tests are passing. Manual testing showed that generally, the extender profiles are now loading on activation for both old and new-style profiles. The exception I saw [earlier](https://github.com/zowe/vscode-extension-for-zowe/pull/1448#pullrequestreview-736056139) involving the missing hostname for new-style profiles will be addressed in issue #1456, as will some of the other `next` branch issues found while testing that were unrelated to this PR. (We may want to split that story up into smaller issues.)

Additional profile-related functionality tested in this PR for both old and new style profiles included create, update, hide/add existing, Check Credentials, and delete.

Thanks @JillieBeanSim for your hard work on this PR!

**Review by lauren-li — APPROVED** [review]

**Review by jellypuno — APPROVED** [review]
looks good. works well. I have failing unit tests but it might be my set-up

**Pull request merged**
