### PR TITLE
Issue #988: update job logs ability

### PR DESCRIPTION
**Pull request by nickImbirev**
## Proposed changes

A refresh particular job command was added to refresh the information about spool files and get the latest spool file content.

## Release Notes

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

## Further comments

We have to basically provide a fresh vscode.URI after each refresh of the job to get up to date spool files, because VSCode will cache our requests without it and there is no other way to manipulate cached data.

### CODE REVIEW

**Review by rudyflores — COMMENTED** [review]
Great work with this implementation @nickImbirev ! 

it seems to be passing all the tests successfully but the only thing I noticed was that your branch is 12 commits behind the master branch, would you be able to pull these new commits into your branch and update this PR? That way I should be able to run the tests again and check for any regressions on the latest changes :)

**Review by rudyflores — COMMENTED** [review]
Thanks for updating your PR, after testing your feature I had a question if a spool files contents is not meant to reload upon clicking the "refresh job" button when it is open in the editor since when I open the file and close it, it does show the latest changes.

Before:
Screen Shot 2021-06-21 at 3 04 27 PM

After closing the file and opening it again:
Screen Shot 2021-06-21 at 3 04 41 PM

**Comment by nickImbirev** [comment]
> Thanks for updating your PR, after testing your feature I had a question if a spool files contents is not meant to reload upon clicking the "refresh job" button when it is open in the editor since when I open the file and close it, it does show the latest changes.

Yep, I understand, what you are saying.

Right now, we have an **uncontrollable** printing of the spool files content in the job tree. For the most cases, it will be cached by the internal VSCode cache and the outdated content will be showed. There is nothing we can do about it, without any big breaking changes :(
The idea of this update is to give users **ability to control**, when they want to see the updated content of the job spool files (and check this job for existence). So, after the `refreshJob` command is executed - there will be the up to date content in the opened tab (if possible) in 100% of the cases.

**Review by crawr — COMMENTED** [review]
Thanks @nickImbirev for your work on this.

Based on my initial tests with a job that was in `ACTIVE` state, it was able to pull the proper updated spool files as the job ran. However, even after the job has ended, the status of the job remained `ACTIVE` while I was expecting it to be `CC 0000` or whatever its final CC will be. I had to refresh at the profile level to update the job status.

Do you think this could/should be handled in this PR or should this be a separate issue?

**Review by rudyflores — APPROVED** [review]
After running integration and unit tests all cases seem to be passing! it also seems to be refreshing the spool files inside job folders as expected after proper testing (without considering the limitation you mentioned in the previous reply which can be perhaps be looked at later on).

**Comment by nickImbirev** [comment]
> Based on my initial tests with a job that was in `ACTIVE` state, it was able to pull the roper updated spool files as the job ran. However, even after the job has ended, the status of the job remained `ACTIVE` while I was expecting it to be `CC 0000` or whatever its final CC will be. I had to refresh at the profile level to update the job status.

Thank you for reviewing it @crawr! I see, what you are saying, but I do not think it is an issue. 

It is just how refresh stuff in ZE works: when you are refreshing the tree node - you are refreshing children, but not the node itself. For example, when you are refreshing jobs in profile - the profile node itself does not became updated.

I believe this can be fixed, but it will require a lot of stuff to be updated accordingly, which is much bigger than the PR goal.

**Review by crawr — APPROVED** [review]
LGTM. Thanks @nickImbirev !

@jandadav Would you like to test this based on the issue you opened?

**Comment by jandadav** [comment]
@crawr 🍰 Awesome 🍰 How can I get the code to my vscode and what do I do to test it? Is there a doc or smt? 🙇‍♂️ Thanks

**Pull request merged**
