### PR TITLE
Display message in status bar #213

### PR DESCRIPTION
**Pull request by anokhikastiaIBM**
[#213]Display messages in status bar

**Description** of the Issue: When editing a dataset in VS Code, a notification appears every time it saves that says "Dataset uploaded successfully." The frequency of these notifications seems undesirable when making a lot of edits, as they keep on popping up.

The status bar should be at the bottom of the screen instead. This would make the info less distracting, while still visible for users who want to see it.

**Changes**: The only change that I made was to the file action.ts on line 1358. When a file is changed, the function saveFile is called when the text document is being saved. A message "DataSet uploaded successfully" (uploadResponse.commandResponse) shows up. I changed to setStatusBarMessage. 

**Preview** of the changes:

[Zowe 213.pdf](https://github.com/zowe/vscode-extension-for-zowe/files/7213811/Zowe.213.pdf)
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by lauren-li** [comment]
@anokhikastiaIBM Thanks for working on this! Consider also implementing this change for when files are saved in USS, as well.

**Comment by katelynienaber** [comment]
@anokhikastiaIBM This is working for me, lmk when it is ready for review and I can approve it :)

**Comment by anokhikastiaIBM** [comment]
@katelynienaber I see that certain tests are failing. Also, it's ready for review.

**Comment by katelynienaber** [comment]
@anokhikastiaIBM It looks like you need to mock function `setStatusBarMessage` and check for calls to this function in the tests, instead of function `showInformationMessage`.

**Comment by anokhikastiaIBM** [comment]
@katelynienaber I fixed the failing tests but I am unable to run the DCO. I think there is a problem with the rebase. Can you please look into it?

**Comment by katelynienaber** [comment]
Yep you forgot to commit with `git commit --signoff` during the rebase.

Try [this answer](https://stackoverflow.com/a/58599218) on stackxchange to fix it...the hash they want you to put in the command can be the hash of the commit before your failing ones.

**Comment by lauren-li** [comment]
Waiting on discussion follow-up in issue #213.

**Comment by anokhikastiaIBM** [comment]
@katelynienaber @rudyflores I put the changes on a new branch called display-msg-status-bar2 since I was having problems with rebase and committing.

**Comment by lauren-li** [comment]
> @katelynienaber @rudyflores I put the changes on a new branch called display-msg-status-bar2 since I was having problems with rebase and committing.

@anokhikastiaIBM Did you want to close this PR in favor of #1507?

**Comment by anokhikastiaIBM** [comment]
Opened a new pull request for this.

**Pull request closed without merging**
