### PR TITLE
(Fix) Uss file names case sensitivity

### PR DESCRIPTION
**Pull request by KutluOzel-b**
## Proposed changes

Fixed Bug in USS file naming case insensitivity.

Now USS files having same name but different case is giving warning to user to change local file system settings.
Prevented user to edit these files ( only allow editing the file in a FIFO way )  

## Release Notes

https://github.com/zowe/vscode-extension-for-zowe/issues/1484

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

### CODE REVIEW

**Review by JillieBeanSim — COMMENTED** [review]
@KutluOzel-b @zFernand0 I thought we discussed a message with a button to continue for this issue? this approach is just showing an information message telling user to change something on their OS settings, not sure if that is the best approach.

**Comment by JillieBeanSim** [comment]
@KutluOzel-b I wonder if we remove the `.toUppercase()` from the USS line in `onWillSave..` if it won't solve the issue?
https://github.com/zowe/vscode-extension-for-zowe/blob/1ef590236f3bc447ffc8c35755b093873f366aa2/packages/zowe-explorer/src/extension.ts#L290

**Comment by KutluOzel-b** [comment]
> @KutluOzel-b I wonder if we remove the `.toUppercase()` instances from the USS line in `onWillSave..` if it won't solve the issue? I have noticed that when testing different scenarios of this caseSensitive issue that it is always saved as all uppercase.
> 
> https://github.com/zowe/vscode-extension-for-zowe/blob/1ef590236f3bc447ffc8c35755b093873f366aa2/packages/zowe-explorer/src/extension.ts#L290

Thank you for your input @JillieBeanSim . I think saving a file in a case sensitive way will continue to lead this bug. The problem is we can't save two files (depending on the OS file system rule) that having same name whether they have capital / lower case differences. As a result the most recent file created is overriding previous one and we loose control on local temp file (copy of the mainframe file ) we have created.

**Review by JillieBeanSim — APPROVED** [review]
Thanks @KutluOzel-b for the fix, sorry I had so many questions and all.

**Pull request merged**
