### PR TITLE
Fix to fetch profiles for registered types

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Fix to issue @t1m0thyj raised for errors on a profile of a type not registered with cli or zowe explorer in config file

## Release Notes

Milestone: 2.4.1

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
Looks like the change broke theia testing again, will look into it

**Review by t1m0thyj — DISMISSED** [review]
Thanks for the quick fix, verified that this works for me 👍 Happy to retest if additional changes are needed for Theia.

**Review by zFernand0 — COMMENTED** [review]
Questions/Comments:
- What is the purpose of having a `fetchAllProfiles` available in the zowe-explorer-api npm package available for extenders if the only profiles it will retrieve are profile types registered to Zowe Explorer?
- While it's true that these lines are already covered by some old/previous test, it will be ideal to add regression tests for quick bug-fixes going forward. I believe adding such tests is better than trying to achieve a coverage percentage.

However, I'm not opposed to approving this PR and letting 2.4.1 go out 🥲

**Review by zFernand0 — DISMISSED** [review]
😋 

---
**Update:** 
- I agree with working around this imperative issue: https://github.com/zowe/imperative/issues/645

**Review by t1m0thyj — APPROVED** [review]

**Pull request merged**
