### PR TITLE
[next] Login & Logout with config file

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

This PR bumps us to "@zowe/cli": "7.0.0-next.202201261615"

Config files now follow Zowe CLI naming, where the global is `zowe.config.json` and team/user is `zowe.config.user.json`

Will now write to the config file for login and remove `tokenType` and `tokenValue` from the config file on logout.  `tokenValue` is stored as secure field.

Unless the service profile is free of properties, comparison of profiles for merging still follow V1 rules where the host and port have to match between the base profile and the service profiles. If the service profile is free of properties it will use all of the properties within the base profile.

## Release Notes

Milestone: vNext

Changelog: Added login and logout capabilities using the right click actions for team config files.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

login-logout-ze-config

### CODE REVIEW

**Review by crawr — COMMENTED** [review]
I might be missing something but I am not able to perform the login from this branch.

Here is a snippet of my config file after I used the login command and provided my user/pwd:
```json
        "zosmf": {
            "type": "zosmf",
            "properties": {},
            "secure": []
        },
        "base": {
            "type": "base",
            "properties": {
                "host": "myhost.net",
                "port": 443,
                "basePath": "api/v1",
                "rejectUnauthorized": false,
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "user",
                "password",
                "tokenValue"
            ]
        }
```

It added the tokenType and tokenValue fields but I received the following error message afterwards.

**Comment by JillieBeanSim** [comment]
@crawr the error message isn't a good one since it refers the the `forEach` so I will look into that but this does follow the v1 profile comparison that was already in place to keep from having unwanted merging to happen.  So the base and service profiles will need to have matching host and port still.

**Comment by JillieBeanSim** [comment]
I was able to recreate it.  It has to do with the zftp profile type being in the profilesByType but not in the config file.  Let me try to just bypass a type that isn't in the config file.

**Comment by JillieBeanSim** [comment]
@crawr I updated the description to include
```
Unless the service profile is free of properties, comparison of profiles for merging still follow V1 rules where the host and port have to match between the base profile and the service profiles. If the service profile is free of properties it will use all of the properties within the base profile.
```
 so your config file you have in place, shown above, will work fine :slightly_smiling_face:

**Review by rudyflores — APPROVED** [review]
Tested auth login/logout in this PR with z/OSMF and Base profile with v1 and v2 profiles and it seems to be working as intended! I also ran the unit/integration tests and they both seem to be fine as well. 

Thanks for your work on this @JillieBeanSim !

**Review by rudyflores — APPROVED** [review]
after re-reviewing this with the audit fixes LGTM!

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
