### PR TITLE
Fix for check creds bug

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

fix for #2262 check credentials loop when attempting to cancel the Check Creds (now `Update Credentials`) popup

*Note* Duplication is on test files

## Release Notes

Milestone: 2.9.2

Changelog: Fixed loop when user selects Cancel on the Check Credentials message.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
How did patch coverage drop from 100% in commit https://github.com/zowe/vscode-extension-for-zowe/pull/2382/commits/f1e216e451c2549d7b11abef17a383dbac5148e8 to 74.22% in following commit that only added CHANGELOG and updated localization?
Screen Shot 2023-07-17 at 1 29 35 PM

**Review by traeok — DISMISSED** [review]
I'm running into a 401 error when trying to access my test LPAR w/ invalid credentials:

image

The "Update Credentials" prompt does not appear. I also noticed that there was an error with the `zowe.ds.pattern` command, so I've included that message in the screenshot as well.

**Review by traeok — COMMENTED** [review]
I noticed that while the "Check credentials" loop is gone, it still tries to process a request and I get a 401 before the search prompt is dismissed/entered:

image

This happens in all trees. However, the "Update credentials" dialog does appear, and selecting "Cancel" works as intended and the dialog does not re-appear like it did before:

image

**Review by traeok — COMMENTED** [review]
I'm running into an issue where the Data Sets and Job trees will prompt for credentials twice if the node is expanded with invalid credentials. It only seems to happen if I do the following:

1. Right-click -> "Update Credentials" on a session and provide fake/invalid credentials. 
2. Expand the session with a filter already set (either on Data Sets or Jobs)
3. Notice the prompt will appear twice

With the USS tree, this does not occur. It might have to do with the timing of when the session node is expanded and when the request is executed.

FixCheckCredsBug

**Comment by JillieBeanSim** [comment]
> I'm running into an issue where the Data Sets and Job trees will prompt for credentials twice if the node is expanded with invalid credentials. It only seems to happen if I do the following:
> 
> 1. Right-click -> "Update Credentials" on a session and provide fake/invalid credentials.
> 2. Expand the session with a filter already set (either on Data Sets or Jobs)
> 3. Notice the prompt will appear twice
> 
> With the USS tree, this does not occur. It might have to do with the timing of when the session node is expanded and when the request is executed.
> 
> FixCheckCredsBug

@traeok from what I see in the video The first is from clicking the session node causing an expand of tree then the second is from the search filter.  The PR is to address the loop caused by search filter.  This is why I moved the expanding of the tree to end of methods since last comment.

**Comment by traeok** [comment]
> from what I see in the video The double is from clicking the session node causing an expand of tree not from the search filter. The PR is to address the loop caused by search filter. This is why I moved the expanding of the tree to end of methods since last comment.

Ah okay, maybe this case should be addressed as a separate issue then? In terms of the search filter causing the loop, that appears to be resolved. If so I can approve so we can get this into 2.9.2 👍

**Comment by JillieBeanSim** [comment]
> > from what I see in the video The double is from clicking the session node causing an expand of tree not from the search filter. The PR is to address the loop caused by search filter. This is why I moved the expanding of the tree to end of methods since last comment.
> 
> @JillieBeanSim Ah okay, maybe this case should be addressed as a separate issue then? In terms of the search filter causing the loop, that appears to be resolved. If so I can approve so we can get this into 2.9.2 👍

let me check, could also be from a previous search still attached to node.  If search fails we shouldn't attach the search criteria to the node, and maybe we are 😢

**Comment by JillieBeanSim** [comment]
@traeok it's the search being added when failing let me fix other trees too

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/0dc84c5a-e0ce-4123-aa9e-aef12fd30d62

**Comment by JillieBeanSim** [comment]
The other trees don't act like the data sets tree acted in video. pushed fix for that tree.  Thanks @traeok, the videos definitely helped.

**Review by traeok — COMMENTED** [review]
The data set tree is fixed, thanks @JillieBeanSim !

I did find that the jobs tree does it sometimes, but it seems like it is related to the same scenario as the data sets (applying filter on expanded session node even if credentials are invalid), so it might be a similar fix.

FixCheckCredsBugJobs

**Comment by JillieBeanSim** [comment]
@traeok I couldn't do the same as ds tree as they aren't handled the same but see the second call is coming from the syncsession call.  I don't believe that is required with watcher and the prompt method stores updates in allProfiles array.

**Comment by JillieBeanSim** [comment]
This is what I am seeing in Jobs tree, on initial search with already incorrect credentials I only get prompted once with cancel.  If I update credentials do a successful search then change creds to be incorrect then I will see 2 pop ups.  This is still better than the loop we are seeing, but cannot locate the second call being initiated.

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/10455acf-464c-4247-a478-4916401ab913

**Comment by JillieBeanSim** [comment]
@zFernand0 & @traeok I tested back to 2.8.x and see double prompt in jobs tree with tested scenarios, so was existing before the bad loop was introduced.  We should get this fix out and look at fixing old issues when we address the work we wanted to do with the trees and getting them handled the same way across all 3.  What do you think?

**Review by zFernand0 — APPROVED** [review]
Happy to get this PR merged in today (if we want to) 😋

**Review by traeok — APPROVED** [review]
Sorry for the delay; was out of office.

Sounds good, I think that its best to merge this fix and handle the jobs tree bug as a separate issue - LGTM, thanks @JillieBeanSim 😃

**Pull request merged**
