### PR TITLE
Added spawn mechanism back to create .zowe if missing

### PR DESCRIPTION
**Pull request by phaumer**
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>

This is a quick hack for https://github.com/zowe/vscode-extension-for-zowe/issues/514
Would like to learn how to do this properly.  Would imperative have to be extended? I see a challenge that this will not work once we add webpack support, unless we explicitly exclude the file ImperativeInit.js from the webpack bundle. (@lauren-li )

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Pushed a more appropriate location for the initialization. Prior to your added code block there is the check for the security modules. It checks for the imperative settings file to be present and if not throws an error. I have now included your spawnSync code here. 
This seems to be the logical location since the security step is always performed and if an error is thrown indicating that imperative.json is not present and consequently re-initalized that will be fine.
I left your original code in commented out. If this all works fine in your scenarios please delete and re commit

**Comment by phaumer** [comment]
Thanks. That is a much better place and I like that it is now called only on failure, which should be speeding up startup for n+1.

**Comment by zFernand0** [comment]
Moving this PR to the v1.2.x branch :)

**Comment by zFernand0** [comment]
Please see #517

**Comment by zFernand0** [comment]
We can delete the `call-imperative-init` branch after merging #517

**Pull request closed without merging**
