### PR TITLE
Fix secure credential management initialization issue

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Fix activation issues with Zowe Explorer seen in Theia and Eclipse Che

Milestone: 2.4.0

Changelog: Fixed activation and Refresh Extension issues in web based editors, ie. Theia.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by phaumer — CHANGES_REQUESTED** [review]
@JillieBeanSim thanks a lot. The activation is now going through in Eclipse Che. 

I see two remaining problems to fix:

(1) When loading a workspace for the first time I still get this warning message. This message is not useful for the end-user. They will not know what the problem is and why it was trying to read the `file ''`.  We need to provide a meaningful message such as `No global Zowe team configuration found. Use Zowe Explorer to create one.`



(2) I started Che with a Git repository that had a project-level Zowe config file. After the repo was loaded I was not able to use the Zowe Explorer `Refresh Data Sets View` button to get these projects listed. I would not see the project ones in the list to select them, only could create a new team-level one. I had to reload the full browser page and they would show up. Somehow the Refresh button does not load the project-level ones from the workspace.

**Comment by phaumer** [comment]
@JillieBeanSim thanks. (1) is resolved. Only problem left is (2) that project team config in my git repo is not recognized until a full browser reload.

**Review by rudyflores — APPROVED** [review]

**Comment by phaumer** [comment]
Testing this one more time I see that now the code runs an `await vscode.commands.executeCommand("workbench.action.reloadWindow");` when clicking the dialog button when creating a global team configuration, which reloads the entire browser and all its extensions. However, it will then find the project-level profiles in addition to the global ones. 

The remaining problem is that when the user does not want to create a global team config and only wants to use the project-level one then there is no indication for the user that a reload is required. Any idea how to approach that?

Otherwise, I think for now this is an acceptable workaround that can be merged as it improves the situation and fixes several issues. We should create a new issue for the next release to add supporting project configs at workspace creation as well as not doing a reloadWindow.

**Comment by JillieBeanSim** [comment]
@phaumer the issue https://github.com/zowe/vscode-extension-for-zowe/issues/1984 for the opening of the workspace with config problem.

**Pull request merged**
