### PR TITLE
Preference to Specify Temp Folder

### PR DESCRIPTION
**Pull request by adambattenburg**
Issue Number: #97

Adds preference to specify temp directory. In order change the temp folder location, add below to preferences.

```
  "Zowe-Temp-Folder-Location": {
    "folderPath": "/path/to/directory"
  }
```

If no folder is specified, it will default to resource folder used now.

### CODE REVIEW

**Comment by Colin-Stone** [comment]
So assuming we set this via settings and as there isn't anything already in there how should we communicate with the user how to specify this value? I suppose we would need to use the README?.

**Comment by adambattenburg** [comment]
I think it needs to be added to the README. I can add it as part of this PR?

However, this would only apply to users which need the advanced functionality. For regular users, it continues to specify `temp` under `resources`.

**Comment by Colin-Stone** [comment]
> I think it needs to be added to the README. I can add it as part of this PR?
> 
> However, this would only apply to users which need the advanced functionality. For regular users, it continues to specify `temp` under `resources`.

Understood. I think we need a section in the README for configuration and possibly a sub-section for Advanced users with health warning. I simply need to know how to create it which should suffice. If you would add that it would be great

**Comment by adambattenburg** [comment]
@Colin-Stone I restructured to the README to move settings that edit `settings` to a different section. Feel free to revert to the old style if you prefer.

**Comment by Colin-Stone** [comment]
> @Colin-Stone I restructured to the README to move preferences that edit `settings` to a different section. Feel free to revert to the old style if you prefer.

That's okay but we need to tell users how to do it somewhere i.e. 
```
  "Zowe-Temp-Folder-Location": {
    "folderPath": "/path/to/directory"
  }
```

**Comment by adambattenburg** [comment]
I've added the example in the README. It should have a default just like the Dataset settings, but I agree explicitly putting it in the README is better. 

Concerning the integration tests, which one fails for you? I get all passing on my end.

**Comment by Colin-Stone** [comment]
> I've added the example in the README. It should have a default just like the Dataset settings, but I agree explicitly putting it in the README is better.
> 
> Concerning the integration tests, which one fails for you? I get all passing on my end. I just had Lauren run the tests on her machine, and it was all good for her as well. Maybe cleaning and re-adding the testing environment helps?

1) Extension Integration Tests
       Deactivate
         should clean up the local files when deactivate is invoked:
     TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
      at Object.fs.mkdirSync (fs.js:867:3)
      at Object.<anonymous> (/Users/stonecc/git/vscode-extension-for-zowe/__tests__/integrationTests/extension.test.ts:180:20)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/stonecc/git/vscode-extension-for-zowe/out/__tests__/integrationTests/extension.test.js:14:58)

base.js:240
  2) Extension Integration Tests - USS
       Deactivate
         should clean up the local files when deactivate is invoked:
     TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
      at Object.fs.mkdirSync (fs.js:867:3)
      at Object.<anonymous> (/Users/stonecc/git/vscode-extension-for-zowe/__tests__/integrationTests/extension.test.ts:594:20)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/stonecc/git/vscode-extension-for-zowe/out/__tests__/integrationTests/extension.test.js:14:58)

base.js:240

I will try again with the latest changes clearing everything out

**Comment by Colin-Stone** [comment]
> I've added the example in the README. It should have a default just like the Dataset settings, but I agree explicitly putting it in the README is better.
> 
> Concerning the integration tests, which one fails for you? I get all passing on my end. I just had Lauren run the tests on her machine, and it was all good for her as well. Maybe cleaning and re-adding the testing environment helps?

1) Extension Integration Tests
       Deactivate
         should clean up the local files when deactivate is invoked:
     TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
      at Object.fs.mkdirSync (fs.js:867:3)
      at Object.<anonymous> (/Users/stonecc/git/vscode-extension-for-zowe/__tests__/integrationTests/extension.test.ts:180:20)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/stonecc/git/vscode-extension-for-zowe/out/__tests__/integrationTests/extension.test.js:14:58)

base.js:240
  2) Extension Integration Tests - USS
       Deactivate
         should clean up the local files when deactivate is invoked:
     TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
      at Object.fs.mkdirSync (fs.js:867:3)
      at Object.<anonymous> (/Users/stonecc/git/vscode-extension-for-zowe/__tests__/integrationTests/extension.test.ts:594:20)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/stonecc/git/vscode-extension-for-zowe/out/__tests__/integrationTests/extension.test.js:14:58)

base.js:240

I will try again with the latest changes clearing everything out.. No the same thing. My suspicion is that because I tried it out it's now in a different state and the integration tests run in the place as the extension ran

**Comment by adambattenburg** [comment]
Good catch Colin. I had forgotten that I reassigned variables marked with `const` in our tests. Everything passes now after changing the folder setting.

**Pull request merged**
