### PR TITLE
177 rework readme file

### PR DESCRIPTION
**Pull request by Pranay154**
Updated readme file based on spec layer out by Colin

### CODE REVIEW

**Comment by zFernand0** [comment]
Hi @Pranay154,
I see you added your sign-off to the first commit in the branch. Please remember that going forward, you have to sign-off every commit. Apologies for the inconveniences. 
If you want, you can give [this](https://github.com/zowe/vscode-extension-for-zowe/pull/281/checks?check_run_id=274807383
) a try
image

*Please Do NOT click the `Set DCO to pass` button*

**Comment by zFernand0** [comment]
Also, I can help with the vulnerability fixes : )

**Comment by zFernand0** [comment]
I'm afraid the DCO recommendation will not be of any help here since history was re-written (i.e. force-push) after a merge commit.
I'd recommend either of the following:
- `git rebase` to the commit that had the issue, maybe [adding the `--signoff` flag](https://stackoverflow.com/questions/25570947/how-to-use-git-interactive-rebase-for-signing-off-a-series-of-commits) could help
- Squash the PR at merge time and don't worry about any subsequent DCOs
- Squash the branch into a new one, and create a new PR

**Comment by Pranay154** [comment]
Closing PR due to DCO issues, created a new one #283

**Pull request closed without merging**
