### PR TITLE
Tree view refresh (fix PR #404)

### LINKED ISSUE #398: Tree view is not refreshed for PDS member actions
The tree view is not updated when the following actions are performed on a PDS:
- Upload Member
- Delete Member

Note: This applies to both Theia and VSCode

### PR DESCRIPTION
**Pull request by katelynienaber**
Adding tree view refresh if member is added/deleted (including favorites, USS file view, and unit tests)

Signed-off-by: katelynienaber <katelyn.nienaber@broadcom.com>
Fixes #398

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Hi Kateyln. Can you connect the issue to this PR please?. I'm struggling to understand the overall objective and cannot find an open issue. 
The delete dataset function for example was refreshed simply by removing the local file. So by refreshing the parent means that piece of code could then be removed.

**Comment by katelynienaber** [comment]
> Hi Kateyln. Can you connect the issue to this PR please?. I'm struggling to understand the overall objective and cannot find an open issue.
> The delete dataset function for example was refreshed simply by removing the local file. So by refreshing the parent means that piece of code could then be removed.

The issue is [#398](https://github.com/zowe/vscode-extension-for-zowe/issues/398)

**Comment by zFernand0** [comment]
The view gets refresh properly when performing the actions, however I do get an error message:
image

**Comment by katelynienaber** [comment]
I missed a condition. It should be fixed now...

**Pull request merged**
