### PR TITLE
Add options to edit config via `+` button

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

v1 profiles in place has same options as before:

v1-profile

Screen Shot 2022-08-04 at 5 23 53 PM

v2 profiles in place have new options: 

v2-profile

if `Edit Team Configuration File` is chosen with only a project or global level in place the existing config will open, if both are in place the user will be presented with the option 

v2-profile

## Release Notes

Milestone: 2.3.0

Changelog: Added option to edit team configuration file via the + button for easy access.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by kristinochka** [comment]
I just tried this branch and seeing an issue:

**Comment by kristinochka** [comment]
I just tried this branch and seeing an issue:
I have both global and project config files. After I click "Create a new Team Configuration File" it opens the existing one, and then the plus button stops working.

**Comment by kristinochka** [comment]
https://user-images.githubusercontent.com/14590297/184699917-0cc357e7-db9f-4dcf-8cc2-11b6bd444fcb.mov

**Comment by kristinochka** [comment]
If both global and project config files exist having "Create a new Team Configuration File" seems redundant because it's doing the same action as "Edit Team Configuration Files". 
What do you think about the below?

- If no menus exist have the menu be named **Create a New Team Configuration File**
- If any configuration files exist **Update Team Configuration Files** and then route them accordingly. The menus under that could say something like "Update global" or "Create project" or could stay the same.

**Comment by JillieBeanSim** [comment]
> If both global and project config files exist having "Create a new Team Configuration File" seems redundant because it's doing the same action as "Edit Team Configuration Files". What do you think about the below?
> 
> * If no menus exist have the menu be named **Create a New Team Configuration File**
> * If any configuration files exist **Update Team Configuration Files** and then route them accordingly. The menus under that could say something like "Update global" or "Create project" or could stay the same.

If a new Zowe Explorer extender has recently been installed the `Create new team config` option actually will merge the new extender info into the schema and appropriate config file, assuming they passed meta data in the initForZowe call.

I will look into the error shown and issue with `+` button mentioned above.

**Comment by kristinochka** [comment]
I guess this is where we need design input. What would be the least confusing User Experience? How can these menus be self-explanatory?
Create a **New Team Configuration File** refers to creating a **new json file**. That’s what I would expect that button to do based on the name. Afterwards, users edit that file to add individual profiles.
Would it make sense to call the merge function from a button labelled  “Edit Team Configuration File”? End user doesn’t need to know the implementation details of schema merging.

**Comment by JillieBeanSim** [comment]
> I guess this is where we need design input. What would be the least confusing User Experience? How can these menus be self-explanatory? Create a **New Team Configuration File** refers to creating a **new json file**. That’s what I would expect that button to do based on the name. Afterwards, users edit that file to add individual profiles. Would it make sense to call the merge function from a button labelled “Edit Team Configuration File”? End user doesn’t need to know the implementation details of schema merging.

@kristinochka if you are wanting to discuss changing the way `create new team config` works a new issue will need to be created and design discussed there.  this issue is to add new functionality to open existing config files.

**Comment by kristinochka** [comment]
I don’t think there should major changes to how `create new team config` works. Can be a matter of labeling this button differently based on what profiles already exist. This is step 2 of fixing the [original](https://github.com/zowe/vscode-extension-for-zowe/issues/1876) issue with adding new UI/UX changes to update config files. Up to you how you want to handle this.

**Review by rudyflores — APPROVED** [review]
Created a team config profile, followed up with clicking the + button and clicked on the new edit tab and it seems to be working as intended! 

Thanks @JillieBeanSim !

**Comment by kristinochka** [comment]
Just realized the + button breakage happens only when Z Open Editor is installed. Thanks @rudyflores for pointing that out. When I disable ZOE no issues with the + button.

**Review by zFernand0 — APPROVED** [review]
Thanks for updating the readme : )
No issues on my end 😋 
Also, thanks for keeping the PR simple and easy to review 😉

**Pull request merged**
