### PR TITLE
Fix Issue 644 - Added function to validate Dataset Name

### PR DESCRIPTION
**Pull request by billpereira**
## Proposed changes

On Issue 644 was requested a feature to validate dataset names before sending the request to create a dsn and then see an error message.
On this PR was added 2 functions to validate the dataset name and qualifiers that may also validate member name in future.
To implement that showInputBox was changed to createInputBox

## Release Notes
Validate dataset name before send request to create it.

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ x] PR Description is included
- [x ] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ x] There is coverage for the code that I have added
- [x ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments
With the change from showInputBox to createInputBox, i got the follow error on test:
  -Extension Unit Tests › tests the createFile for prompt credentials error
    TypeError: vscode.window.createInputBox is not a function
And i couldn't find how to fix/adapt the test

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by dkelosky** [comment]
I commented on #644, but I think we may not handle all code pages with this proposed fix.  Perhaps I should have commented here instead 😞

**Comment by jellypuno** [comment]
> Based on @dkelosky comments, @jellypuno do you think i should still focus on this issue?

@billpereira seems like it. Maybe we should pause this PR and wait for further notice from @dkelosky .

**Comment by dkelosky** [comment]
Hi Bill - we'll get some comments from @zFernand0 too.  As we mentioned in our chat, I think your code is very clean an achieves the initial request.  But, I think that this change might cause problems with alternate code pages.  So, perhaps this can be closed for the time being?

**Comment by billpereira** [comment]
i'm ok with that...

**Comment by dkelosky** [comment]
Thanks for your understanding @billpereira; hopefully this was a worthwhile for you.  We'll close this for now pending code page support for data sets.

**Pull request closed without merging**
