### PR TITLE
Add doc for prmoptCredentials() api

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

Added documentation on `promptCredentials()`

## Release Notes

Milestone: V2

Changelog: Added documentation on `promptCredentials()`

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by zFernand0** [comment]
Related to #1696

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @zFernand0

**Review by JamesBauman — APPROVED** [review]
The edits LGTM..   However, the entire article needs a deep grammar review.  Perhaps... we can open an issue to perform a deep grammar review and i can complete the review as time avails itself.

**Comment by JillieBeanSim** [comment]
> The edits LGTM.. However, the entire article needs a deep grammar review. Perhaps... we can open an issue to perform a deep grammar review and i can complete the review as time avails itself.

Thanks @JamesBauman, feel free to create the issue in the repo or add it in the existing [issue](https://github.com/zowe/vscode-extension-for-zowe/issues/1696) as a reminder to take a second glance over the doc and update the grammar.

**Pull request merged**
