### PR TITLE
Fix: Use nls message bundle instead of file format

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Fixes issue #944 (Validate profile error message replaced by "Failed to load message bundle" message)
Error message now shows as expected:
Screen Shot 2020-07-15 at 2 20 46 PM

## Release Notes

Milestone: 1.8

Changelog: (This is a fix for an issue on master branch; thus, I don't believe it needs its own Changelog entry.)

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing (N/A but all unit tests passing)
- [ ] I have added integration test and it is passing (N/A but all current integration tests passing)
- [ ] There is coverage for the code that I have added (No code added)
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate) (N/A)
- [ ] Any PR dependencies have been merged and published (if appropriate) (N/A)

## Further comments

N/A

### CODE REVIEW

**Comment by lauren-li** [comment]
@zFernand0 Does `./out/__tests__/__theia__/*.theia.test.js` need to be included in the webpacked extension? I see the Theia tests failing:
Screen Shot 2020-07-15 at 2 28 59 PM

And it appears that the build command we use webpacks the extension, which doesn't include `__tests__` in its `out` folder:
Screen Shot 2020-07-15 at 2 28 27 PM

Should I include `__tests__` in the webpacked extension's `out` folder? Or maybe, this script could instead use a version of the build command that includes the `__tests__` folder in the `out` folder?

**Comment by zdmullen** [comment]
Do we want to do a 1.7.2 release for this? We could open a PR against the 1.7.x branch to do this. What do you think @zFernand0?

**Comment by JillieBeanSim** [comment]
> Do we want to do a 1.7.2 release for this? We could open a PR against the 1.7.x branch to do this. What do you think @zFernand0?

Hey @zdmullen the webpack work is on the master branch for 1.8 release

**Comment by lauren-li** [comment]
@zdmullen Issue #944 only affects the code post-Webpack-merge, so this PR #945 should stay with the 1.8 release. (Basically, this should have gone into the master branch at the same time as the rest of the Webpack work. I think it accidentally got missed when PR #860 got merged in.)

**Comment by zFernand0** [comment]
Thanks @zdmullen and sorry for mentioning 1.7.2 before.
@lauren-li, You are correct that this will just need to go out with 1.8.0.
Thanks for confirming.

**Pull request merged**
