### PR TITLE
[vNext] Change activation event to onStartupFinished

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Change activation event to onStartupFinished

## Release Notes

Milestone: vNext

Changelog: ZE & zFTP ext: Updated activation event to `onStartupFinished`

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks @JillieBeanSim !

It might just be a coincidence during testing, but Zowe Explorer seems to be loading faster with this activation event too 😁

**Review by rudyflores — DISMISSED** [review]
As Trae said, activation time was definitely improved with this change, thanks @JillieBeanSim !

**Review by t1m0thyj — CHANGES_REQUESTED** [review]
Thanks for changing the activation event 😁 

Can we remove the `--allow-star-activation` flag from the "package" script in package.json? I don't think it's needed anymore with this change 🎉

**Review by traeok — APPROVED** [review]

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @JillieBeanSim!

**Comment by zFernand0** [comment]
LGTM!

**Pull request merged**
