### PR TITLE
Issue #1380: Fix USS search and update profile errors for profiles without user/pass stored

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Fixes issue #1380 by getting the synced session during USS search. Recreate/testing steps for this PR are included in the description for #1380.

## Release Notes

Milestone: 1.17.0

Changelog: Fixed USS search and update profile errors for profiles without user/password stored #1380.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by lauren-li** [comment]
Note for reviewers: I noticed in the current release 1.16.1, the following behavior is also present and can be addressed separately:
If you use a no-credentials profile to do a search (USS or Data Sets) and click “Do not save” after entering your credentials at the prompts, and then try to expand your favorites for that same no-credentials profile, it will ask for your credentials again.

**Comment by jellypuno** [comment]
> Note for reviewers @JillieBeanSim @jellypuno: I noticed in the current release 1.16.1, the following behavior is also present and can be addressed separately:
> If you use a no-credentials profile to do a search (USS or Data Sets) and click “Do not save” after entering your credentials at the prompts, and then try to expand your favorites for that same no-credentials profile, it will ask for your credentials again.

Do we have an issue created for this one?

**Comment by lauren-li** [comment]
> > Note for reviewers @JillieBeanSim @jellypuno: I noticed in the current release 1.16.1, the following behavior is also present and can be addressed separately:
> > If you use a no-credentials profile to do a search (USS or Data Sets) and click “Do not save” after entering your credentials at the prompts, and then try to expand your favorites for that same no-credentials profile, it will ask for your credentials again.
> 
> Do we have an issue created for this one?

@jellypuno We do now! #1393 (Avoid re-prompting for credentials when using the same unsaved-credentials profile between Favorites and non-Favorites)

**Review by JillieBeanSim — APPROVED** [review]
LGTM! Thanks @lauren-li for the quick fix! All expected tests and checks are passing =)

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
