### PR TITLE
Fix Issue 1049 - Migrate from deprecated test runner for integration tests

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Issue #1049: Migrate from deprecated `vscode` dependency to `vscode-test` per VS Code's [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode)

**NOTE FOR REVIEWERS:** If you are testing the `update-testrunner` branch, you should delete your `node_modules` folder (I deleted mine at both the top level and under `packages/zowe-explorer`), and then re-run `yarn` at the top level. (You may have to restart VS Code to get rid of "errors" after doing this.)

## Release Notes

Milestone: 2.0

Changelog: Migrate from deprecated `vscode` test runner to `vscode-test`.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [x] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by lauren-li** [comment]
@crawr Thank you for offering to test this! The Theia tests may need some additional updates, but I'm not sure since I am having trouble running them locally on `master` branch, as well as this PR branch. Could you please give this branch a try and see if the Theia tests will run locally on your machine?

**Comment by zFernand0** [comment]
Ran into a few unexpected Integration tests failures, but test runner seems to work fine! : )

**Comment by lauren-li** [comment]
Thank you for testing this, @zFernand0! Did you mean that the integration test failures you encountered were different from what you see in master branch? When I ran the integration tests, I got the same results for this branch and master branch.

**Review by crawr — COMMENTED** [review]
Hey Lauren, this looks good! I was able to run the Theia tests locally on my machine and they all passed. I even tried without the headless option and I saw the ZE activated successfully in the browser.

**Comment by lauren-li** [comment]
Awesome, thank you for testing this, @crawr!

**Review by zFernand0 — APPROVED** [review]

**Review by crawr — APPROVED** [review]

**Comment by zFernand0** [comment]
Audit failed due to low vulnerability. However, the command/pipeline should have ignored anything below moderate severity.
This should be good to merge.

**Review by jellypuno — APPROVED** [review]
Looks good!

**Pull request merged**
