### PR TITLE
fix(sort/ds): Coerce invalid PDS date values to `null` during parsing

### LINKED ISSUE #2552: Sorting by date/time shows "current" date for members without ISPF stats
When I open a PDS that has members that do not have ISPF stats, the sorting feature in ZOWE Explorer will show the "current" date for such members.

**To Reproduce**

1. Open a PDS with members that do not have ISPF stats
2. Sort them by 'Date Modified'

**Expected behavior**

Members without ISPF stats do not show the date/time greyed out text at all

**Screenshots**

image

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This PR fixes a bug where Day.js interpreted an `undefined` value as a valid date (same behavior as `dayjs()` or `Date.now()`) instead of coercing the invalid/missing date parameter to null.

image

Fixes #2552 

## Release Notes

Milestone: 2.12.1

Changelog:
- Fixed issue where sort PDS feature applied the date description to members without a valid date. #2552 

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by adam-wolfe** [comment]
If I have a member with no date modified and sort by date modified in descending order, I see it's position in the member list toggling between first and last when I collapse and re-expand the PDS.

pr2553Issue

**Comment by traeok** [comment]
> If I have a member with no date modified and sort by date modified in descending order, I see it's position in the member list toggling between first and last when I collapse and re-expand the PDS.

I've addressed this in 60a50c2 - I wasn't sure where users would prefer the single node to end up, but for now, a node will be moved to the bottom of the list in the "Ascending" direction and pulled to the top of the list for "Descending."

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by adam-wolfe — APPROVED** [review]
LGTM

**Pull request merged**
