### PR TITLE
Issue #310: Adding star icon for favorites

### PR DESCRIPTION
**Pull request by katelynienaber**
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>

## Proposed changes

Replaced the old Favorites icon with a new star icon.

## Release Notes

Milestone: Backlog

Changelog: Created new star icon for Favorites

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

## Further comments

**Perhaps this should NOT close the linked issue!!!** There was more discussion there unrelated to this particular icon...

### CODE REVIEW

**Comment by jellypuno** [comment]
@katelynienaber I've added this change in PR #787 but I can remove it if you are already doing it.

**Comment by katelynienaber** [comment]
> @katelynienaber I've added this change in PR #787 but I can remove it if you are already doing it. I emailed you the icons for light and dark.

Okay. I will leave this open because @zdmullen mentioned we should keep more issues separate.

I emailed you back :D

**Comment by jellypuno** [comment]
@katelynienaber let me know if the icons are added and I can review this PR

**Comment by katelynienaber** [comment]
@jellypuno  yes they are in there!

**Comment by jellypuno** [comment]
@zFernand0 @crawr This PR looks good and has enough approvals. I will merge it now.

**Pull request merged**
