### PR TITLE
Fix issue 1078: Tree Refresh button does not pick up extenders' profile updates

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Addresses issue #1078 (Tree Refresh button does not pick up extenders' profile updates)
- Fills in the profile type parameter of the `getProfiles()` call in `refreshTree()`.

Reviewers can use the below process to check that there aren't regressions with z/OSMF profiles, and to test that the fix works for extenders' profiles:
1. Be sure the profile is added in the Data Sets tree view. (This fix should apply for any tree view, but I am just using the Data Sets view for simplicity here.)
1. Edit the profile information via CLI, or by editing the profile's yaml file directly. For example, change the profile's port number.
1. Click the Refresh arrow button in the Data Sets view.
1. Click on the "Edit" icon for profile, and see that the profile's information (e.g. port number) should be changed.

## Release Notes

Milestone: 1.11

Changelog: Update profile information for all profile types when the tree Refresh buttons are clicked.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by lauren-li** [comment]
This PR has been updated with the latest `master` branch, and merge conflicts with #1064 have been resolved. It is ready for review.

**Review by zFernand0 — APPROVED** [review]
LGTM!
Thank You!

**Review by JillieBeanSim — APPROVED** [review]
This LGTM! All expected checks and tests are passing and it works functionally as expected.  Thanks @lauren-li for adding this

**Review by jellypuno — APPROVED** [review]
LGTM! Thanks @lauren-li

**Pull request merged**
