### PR TITLE
Integration test for allocate like

### PR DESCRIPTION
**Pull request by katelynienaber**
Added an integration test for allocate like (should be FAILING now with error code 500 because of CLI issue)

## Release Notes

Milestone: Hotfix

Changelog: Added allocate like integration test

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by jellypuno** [comment]
Please make sure that this dataset is deleted in the post integration script

**Comment by katelynienaber** [comment]
> Please make sure that this dataset is deleted in the post integration script

Whoops, I always forget this one...

**Comment by jellypuno** [comment]
I will sync up with CLI team and check when is their next release

**Comment by katelynienaber** [comment]
TODO:
- Bump CLI version to latest
- Add back allocate like command to command palette (CTRL+SHIFT+P)

**Comment by jellypuno** [comment]
Update: the allocate like in CLI was added in 6.31.1 release.

**Comment by katelynienaber** [comment]
@jellypuno @zFernand0 does this mean that "bump CLI version to latest" has been done for ZE now?

**Comment by JillieBeanSim** [comment]
> @jellypuno @zFernand0 does this mean that "bump CLI version to latest" has been done for ZE now?

@katelynienaber isn't that bump to be done in this branch to test the integration test? It is not done on master yet.

**Comment by jellypuno** [comment]
@katelynienaber +1 on what @JillieBeanSim said.

**Comment by katelynienaber** [comment]
@JillieBeanSim I didn't know what @jellypuno's post about CLI meant. That's why I was asking.

**Comment by JillieBeanSim** [comment]
@katelynienaber the integration tests passes the first time ran and after cleaning my test environment with `posttest` & `pretest` but fails if integration tests are run consecutively without running cleanup.  Other integration tests don't require cleanup scripts to be run in between each time integration tests are run.  Could the test clean itself after running or something similar to other integration tests as to not require the `posttest` & `pretest` to be run after each instance of running integration tests?

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
@katelynienaber functionality works great, right-click and command palate.  Once the comment above is addressed and testers aren't required to run cleanup and setup scripts between each run of integration tests I think this PR will be good to go.  Thanks for your work on this.

**Comment by katelynienaber** [comment]
@JillieBeanSim Hello, this should be fixed now :)

**Review by JillieBeanSim — APPROVED** [review]
Thanks @katelynienaber for your work on this. Everything looks good now regarding this PR.

I do see some new failing integration tests, but also seeing them on master branch and commented about them in the squad slack channel
```
Extension Integration Tests
       Saving a File
         should download, change, and re-upload a PS:
     Error: cannot open file:///c%3A/Users/BillieSimmons/Documents/GitHub/PUBLIC/ZOWE/vscode-extension-for-zowe/packages/zowe-explorer/resources/temp/_D_/defaultZosmf/ZOWEBJS.CLITST5.PDS.EXT.PDS. Detail: File seems to be binary and cannot be opened as text
```
```
Extension Integration Tests
       Saving a File
         should download, change, and re-upload a PDS member:
     TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
```
```
Extension Integration Tests - USS
       Deactivate
         should clean up the local files when deactivate is invoked:

      AssertionError: expected true to equal false
      + expected - actual

      -true
      +false
```

**Review by crawr — APPROVED** [review]
LGTM. Functionality works great for me. Thanks @katelynienaber

**Pull request merged**
