### PR TITLE
VSC Compare function, not working with Favorites from Zowe Explorer

### PR DESCRIPTION
**Pull request by SanthoshiBoyina**
## Proposed changes
The feature of Visual Studio Code to compare 2 files, if the file on the mainframe has changed in the meantime, doesn't work if you open a Member under Favorites. It overrides the file automatically. In this bug fix, we are able to trigger Compare function when ETAGs are mismatched.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — COMMENTED** [review]
Hi @SanthoshiBoyina, thanks for working on resolving conflict management - looks great so far.

After a discussion w/ @t1m0thyj, I do have a concern regarding the Data Set tree. On line 523 in the `openPS` function (`dataset/actions.ts`), I noticed that we set the e-tag regardless of its value in the response:

```ts
const response = await responsePromise;
node.setEtag(response?.apiResponse?.etag);
statusMsg.dispose();
```

If a response does not return an e-tag, it will set the e-tag to null, which will cause the first save to bypass the e-tag mismatch on the mainframe.

To avoid this, we'll need to add a check to see if `response?.apiResponse?.etag` is a valid value before calling `node.setEtag`.

**Review by t1m0thyj — CHANGES_REQUESTED** [review]
Agree with @traeok's comment, here are steps for how I reproduced the issue:
1. Open a data set in preview mode by single-clicking on it in the tree
2. Make changes to the data set on the mainframe
3. Make changes to the data set locally in ZE
    This will switch the editor from preview mode (title italicized) to edit mode 👍 
    It will also reset the etag for the current node to null which we don't want 😢 
5. Save the changes and notice that no conflict is detected

IMO we should fix this before 2.12.1 to avoid potential data loss, potentially in this PR since its related to compare functionality? I also don't mind opening a separate PR to fix it if preferred 🙂

**Comment by t1m0thyj** [comment]
Based on discussion at standup, I'll open another PR against this one with the fix for etag being set to null 🙂

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! thanks for the fix

**Review by rudyflores — DISMISSED** [review]
Thanks @SanthoshiBoyina ! 

Only thing I see is some code coverage missing but not sure if this will be an issue since I know we want to get the release out?

**Review by t1m0thyj — CHANGES_REQUESTED** [review]

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @SanthoshiBoyina and @JillieBeanSim!

**Review by rudyflores — APPROVED** [review]
Nice catch @t1m0thyj !

**Pull request merged**
