### PR TITLE
Issue #718: Add back addRecall to openPS

### PR DESCRIPTION
**Pull request by katelynienaber**
Added back addRecall to function openPS and fixed unit tests to match.

[Issue #718](https://github.com/zowe/vscode-extension-for-zowe/issues/718)

### CODE REVIEW

**Comment by jellypuno** [comment]
@katelynienaber I'm weirded out with the word recall. Because there is a recall datasets PR right now and now there is this recall that I feel like is very different from each other. I am still unsure what this recall does. Is it possible to rename it? or is it similar to recall migrated datasets?

**Comment by katelynienaber** [comment]
> @katelynienaber I'm weirded out with the word recall. Because there is a recall datasets PR right now and now there is this recall that I feel like is very different from each other. I am still unsure what this recall does. Is it possible to rename it? or is it similar to recall migrated datasets?

I commented on that PR, because technically this function existed first...this is just to put it back because somehow it got removed P:

**Comment by katelynienaber** [comment]
> I'm afraid there are unit test failures in the pipeline and also a couple of integration test fail in this branch. However, the code makes sense to me. : )
> 
> @katelynienaber can you take a look?

This should be fixed :3

**Comment by zFernand0** [comment]
I'm still seeing issues on integrations tests, one specifically for the addRecall functionality (and others around opening PS and saving files)

**Comment by Pranay154** [comment]
> I'm still seeing issues on integrations tests, one specifically for the addRecall functionality (and others around opening PS and saving files)

Hey @zFernand0 , I don't know if this is to do with my environment, but first time I ran the integration test the specific addRecall test passed for me, however rerunning it, it failed. However I do get this issue from time to time on my environment, so not sure how reliable my "integration testing" is

Screenshot 2020-04-28 at 15 14 41

**Comment by katelynienaber** [comment]
Some of the integration test failures were due to a similar issue as fixed in the unit tests...will check in a sec to see if I got them all.

**Comment by zFernand0** [comment]
> > I'm still seeing issues on integrations tests, one specifically for the addRecall functionality (and others around opening PS and saving files)
> 
> Hey @zFernand0 , I don't know if this is to do with my environment, but first time I ran the integration test the specific addRecall test passed for me, however rerunning it, it failed. However I do get this issue from time to time on my environment, so not sure how reliable my "integration testing" is
> 
> Screenshot 2020-04-28 at 15 14 41

Hey @Pranay154, 
Thanks for sharing. I've also spotted a few failure on my integration tests due to deep comparisons of `Thenable` objects. but those seem to work on other people's environments, and the application does not fail due to this integration test failure. However, I don't disregard the possibility of it causing real problems in the future, hence why we should have multiple people looking at PRs.

**Pull request merged**
