### PR TITLE
Clarity added to VS Code extension dependency

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

V2 conformance item clarity
VS Code extension dependency: Extension declares Zowe Explorer as a VS Code extension dependency by including an `extensionDependencies` entry for Zowe Explorer in its package.json file if the extension uses VS Code dependent Zowe Explorer APIs.

Update 4/6/2022: removal of KeytarAPI item see [comment](https://github.com/zowe/vscode-extension-for-zowe/pull/1712#issuecomment-1090815477) below for details.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by zFernand0 — APPROVED** [review]
Thanks for making the update.
Not sure if Rose will suggest to just make this item (item-11) a best practice instead of having a conditional requirement.
Same goes for item-13 😋

**Comment by RASakach** [comment]
@JillieBeanSim @zFernand0 as mentioned during the TSC call, I would like to review these changes on a call - can we plan to do this next week?

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim @zFernand0 as mentioned during the TSC call, I would like to review these changes on a call - can we plan to do this next week?

Hey @RASakach, that sounds good to me.  Thanks

**Review by zFernand0 — DISMISSED** [review]

**Comment by RASakach** [comment]
@JillieBeanSim @zFernand0 @phaumer I've applied the revisions to the XLS file we are using to track V2 conformance changes:  https://ibm.box.com/s/4e3vvki81ds0zowrdpqu3ubitn9f51qe

As discussed the changes include the following:
(1) Removed original item 17 (Secure Credential Store entry)
(2) Reworded item 11  *note, I've shortened it a bit from the verbiage suggested by PH 
(3) Repeated item 11 in subsequent sections

- item 17 is "Required" repeat of item 11
- item 22 is "Best Practice" repeat of item 11

Please indicate "approved" if the changes look ok to you.  TYVM

**Comment by phaumer** [comment]
@RASakach thanks. For the third entry should we use the word `should` instead of `must`?

**Comment by zFernand0** [comment]
I'm fine with the changes as they are.
Thank you Rose! 🌹

**Comment by RASakach** [comment]
@phaumer I really like your suggestion and have incorporated it in the "Adds Menus" section.  I feel this slight adjustment will help to avoid confusion.  TY for the review!

VS Code extension dependency: If the extension calls the Zowe Explorer API it should declare Zowe Explorer as a VS Code extension dependency by including an extensionDependencies entry for Zowe Explorer in its package.json file. This ensures  Zowe Explorer and Zowe Explorer API are activated and initialized for proper use by its extenders

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by phaumer — APPROVED** [review]

**Pull request merged**
