### PR TITLE
Update environment check for Theia compatability

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes
Fixes issue #1009 and restores general Theia compatability.

## Release Notes

Milestone: 1.9.0

Changelog: Update environment check for Theia compatability.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by phaumer — DISMISSED** [review]
I tested this fix successfully in VS Code, Theia 1.3, and CRW 2.3 (which is Che 7.16.2)

**Review by crawr — APPROVED** [review]
Thanks for fixing this. I wonder if instead of hard-coding the value "2", will vscode detect the variable vscode.UIKind.Web instead?

I tested several of the Theia branching code that we have (copy path, merge conflict, filter prompt, etc) and they all worked as expected.

**Comment by lauren-li** [comment]
@crawr Yes, `vscode.UIKind.Web` does work. Let's use that instead.

(I didn't use it earlier because my capitalization was `uiKind` instead of `UIKind` when I was trying this, and thus it wasn't working for me. Thanks for pointing this out!)

**Comment by lauren-li** [comment]
@crawr @phaumer Thank you for testing out this PR! I have updated it according to @crawr's suggestion, and it is ready to be reviewed again.

**Review by phaumer — APPROVED** [review]
Retested and it still works.

**Review by crawr — APPROVED** [review]
LGTM!

**Pull request merged**
