### PR TITLE
Webpack with localization

### PR DESCRIPTION
**Pull request by lauren-li**
Work in progress. This branch has webpack working with localization, but integration tests need some additional work. Addresses issue #74.
- You can check wepback by running `npm run package`, renaming the resulting .vsix file to a .zip, and checking this .zip folder's contents.
  - Under the **dist** folder, there should be a single **extension.js** file and **extension.js.map** file (as opposed to .js files named after source code files). There should be several .json files as well, including .json files in a **src** folder that mirror the soure code's **src** folder hierarchy, and these are used for localization.
- You can check the localization in this branch by either installing the extension from the .vsix file built from this branch, or by just pulling the branch and running it with the Extension Development Host.
  - Localization can be tested by switching the [VS Code display language](https://code.visualstudio.com/docs/getstarted/locales) to French. The following text of the extension should be in French:
    - Hover text for the "Create New Data Set" icon. (Tests package.json i18n.)
    - QuickPick text that appears when deleting a data set. (Tests i18n for TypeScript files.)

Some notes about the files changed:
- An **i18n/fra** folder full of French language files was added as part of this PR so that localization functionality can be tested with webpack. Changed files beginning with **i18n/fra** do not need to be code-reviewed.
- Changes in **src/\*\*/*.ts** files have to do with adding and/or updating the localization config/call at the top of the file. No changes in actual code logic were made.

### CODE REVIEW

**Comment by Colin-Stone** [comment]
get an error trying to run the integration tests Error: Cannot find module './items/document' Is there something else that's needed for the build to produce these. The extension itself appears to run okay

**Comment by lauren-li** [comment]
@Colin-Stone Thanks for pointing this out! I also ran into the same issue starting yesterday, and have pushed a commit to address it.

**Comment by lauren-li** [comment]
I removed the majority of the node_modules folder from vsix generation, as webpack should already include necessary node modules in the extension.js file. The only one I left in was node_modules/vscode-nls/**, since the extension (installed from the generated vsix file) does not seem to function properly without it.

**Comparison of generated Zowe Explorer vsix file sizes:**

|vsix file generation source|Resulting vsix file size|
|-------------------------------------------------------|--------|
|Master branch                                                                  |51.6 MB|
|webpack-separate-dist, including all node_modules.    | 10.8 MB|
|webpack-separate-dist, vscode-nls node_module only | 3.8 MB |

**Comment by tjohnsonBCM** [comment]
Attempted unsuccessfully to get the integration tests working with webpack in this branch. Have summarized my findings below.

Since the integration tests depend on the extension's source code (e.g., `src/Profiles.ts`), they need to load those modules from the same place as the extension. When trying to run the integration tests against the webpacked extension, they fail because they are loading the source code from a different location that isn't webpacked (`out/*.js` instead of `dist/extension.js`).

I believe we have two options: webpack both the extension and the integration tests, or don't webpack either of them. The first option seems ideal, it would be nice to run tests with the webpacked extension to simulate the published VSIX as closely as possible.

I looked into using the NPM package [mochapack](https://www.npmjs.com/package/mochapack) to make Mocha and Webpack work together. However, I couldn't find a way to make the VS Code extension host launch webpacked tests, as it seems to require that the tests be supplied through `extensionTestsPath`.

Unless we can find a way to run the integration tests webpacked, it seems the extension may need to be built without webpack in the NPM `pretest` script. This approach seems recommended in [this GitHub comment from a Microsoft employee](https://github.com/microsoft/vscode-docs/issues/2254#issuecomment-469752205), which states that if tests for a VS Code extension depend directly on source code, they shouldn't be webpacked.

**Comment by lauren-li** [comment]
Closing this PR in favor of #860.

**Pull request closed without merging**
