### PR TITLE
Don't require ~/.zowe folder to exist

### LINKED ISSUE #514: Zowe 1.2.1 does not activate when ~/.zowe directory is not present
In Zowe Explorer v1.1.0 we had a ProfileLoader class that would actually spawn a node process to run the imperative main from node_modules to basically run Zowe CLI to create the .zowe directory in the user’s home directory and if already present read the profiles already available.  This was useful for users who do not have Zowe CLI installed as they could just use Zowe Explorer without installing the CLI. 

I see that this code got removed in this PR https://github.com/zowe/vscode-extension-for-zowe/pull/400. So now when I install Zowe Explorer without having a ~/.zowe directory activation of Zowe Explorer even fails. The only workaround it seems is installing Zowe CLI and calling any command.

image

### PR DESCRIPTION
**Pull request by zFernand0**
Signed-off-by: Timothy Johnson <timothy.johnson@broadcom.com>

Fix #514 Without spawning a process

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Concidering the build issue, is this awaiting the change to `@zowe`

**Comment by tjohnsonBCM** [comment]
Some of the mock definitions in `extension.unit.test.ts` seemed to be duplicate so I removed them. Now the coverage seems to have gone down significantly even though I didn't remove any tests. Should I restore these mock definitions?

**Comment by Colin-Stone** [comment]
> Some of the mock definitions in `extension.unit.test.ts` seemed to be duplicate so I removed them. Now the coverage seems to have gone down significantly even though I didn't remove any tests. Should I restore these mock definitions?

I think it's a false negative. The actual report from the unit tests looks the same

**Comment by zFernand0** [comment]
Thanks for fixing the tests @tjohnsonBCM

**Pull request merged**
