### PR TITLE
Issue #1297: Fixed bug when cancelling TSO command

### PR DESCRIPTION
**Pull request by katelynienaber**
Signed-off-by: Katelyn Nienaber <katelyn.nienaber@broadcom.com>

## Proposed changes

This addresses the fifth (last) point on issue #1297. It should NOT close that issue.

## Release Notes

Milestone: Backlog

Changelog: Implemented separate console windows for TSO/MVS commands

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — COMMENTED** [review]
@katelynienaber is there an issue that should be linked to this PR?
Also, should the other instance in `Issue TSO Command` that should result in `Operation cancelled` be addressed in this as well?

- escaping from command textbox

**Comment by katelynienaber** [comment]
@JillieBeanSim I think that issue should be solved separately. It seems to be caused by function `resolveQuickPickHelper`, because we only resolve the promise on `onDidAccept`, and it should be resolved `onDidHide` instead, to handle any sort of response. But this may affect other parts of the code outside of the TSO command prompt, and I don't want to be responsible for debugging all of our prompts using function `resolveQuickPickHelper` in this PR :)

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim I think that issue should be solved separately. It seems to be caused by function `resolveQuickPickHelper`, because we only resolve the promise on `onDidAccept`, and it should be resolved `onDidHide` instead, to handle any sort of response. But this may affect other parts of the code outside of the TSO command prompt, and I don't want to be responsible for debugging all of our prompts using function `resolveQuickPickHelper` in this PR :)

Ok, could you update the issue list so we don't forget that still needs to be done please.

**Comment by katelynienaber** [comment]
Yep!

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @katelynienaber for the fix

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
