### PR TITLE
Update README in this repo

### PR DESCRIPTION
**Pull request by IgorCATech**
This PR will update the README in the vscode-extension-for-zowe. 

Once this is ready, I'll proceed to update the Zowe doc.

### CODE REVIEW

**Comment by jellypuno** [comment]
- There are several lint issues. 
- and I think the relative path for the images is wrong that's why we can't see it: 
For example:
` Add Profile`
it should be 
`Add Profile`

- Typo in the first sentence:  "sytem administrators"

**Comment by crawr** [comment]
- "Create a Zowe CLI zosmf profile" I think should be level 3 or level 4 header so that it's more visible
- The "Advanced Configuration" for "Temp Folder Location" should be moved to "Usage Tips" since this is not specific to just Data sets. It is applicable to USS and Jobs as well.

**Comment by Colin-Stone** [comment]
` By default, Visual Studio Code does not highlight data set syntax. To enhance the experience of using the extension, download an extension that highlights syntax, such as [IBM Z Open Editor](https://marketplace.visualstudio.com/items?itemName=IBM.zopeneditor) or [Code4z](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.code4z-extension-pack).`

I'm not happy with this statement and it's not accurate. I would prefer we talked about the fact that the Zowe Explorer stands on it's own and **does** support syntax highlighting. We should explicitly describe that users are able to further enhance the Explorer by installing highlighting extensions such as ibm-assembler and ibm-jcl created by Dan Kelowsky. There are also many other extensions available for Cobol and other mainframe languages that augment the Zowe Explorer.

Although the Zowe Explorer can be extended with CodeZ or Z Open Editor, in my opinion I don't believe the Zowe Explorer Readme is the place to advertise corporate offerings but instead promote Open Source collaboration and Zowe.

**Comment by Colin-Stone** [comment]
This may have been in error for some time..
`functionalties` spelling?

**Comment by zFernand0** [comment]
Thanks for removing real host and port information

**Comment by IgorCATech** [comment]
@zFernand0 I'll delete the entire branch once merged

**Comment by zFernand0** [comment]
> @zFernand0 I'll delete the entire branch once merged

Wouldn't the commit history remain on master though? 
I'm fine if nobody thinks this is an issue. : )

**Comment by IgorCATech** [comment]
> > @zFernand0 I'll delete the entire branch once merged
> 
> Wouldn't the commit history remain on master though?

Can we resolve this by rebasing?

**Comment by jellypuno** [comment]
> Wouldn't the commit history remain on master though?
> I'm fine if nobody thinks this is an issue. : )

@zFernand0 I am worried about this sensitive information. If possible, it would be better if it is removed.

**Pull request merged**
