### PR TITLE
Remove redundant entry from ZE FTP vscodeignore

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Removes redundant entry from Zowe Explorer FTP extension's `.vscodeignore` file.
Aimed at addressing issue #1377 (no zftp profile type option after installed Zowe Explorer Extension for FTP version 1.16.0).

## Release Notes

Milestone: 1.16.1

Changelog: Fix Zowe Explorer Extension for FTP VS Code Marketplace release.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by phaumer** [comment]
@lauren-li did you run it? Did it work?

**Comment by lauren-li** [comment]
@phaumer I tested this using the Zowe Explorer FTP extension vsix artifact produced from the [pseudo-deploy](https://github.com/zowe/vscode-extension-for-zowe/actions/runs/980023722) that @zFernand0 triggered yesterday. It has the `out` folder containing `extension.js`, and also runs well (able to load zftp profiles) when installed from vsix artifact.

However, all the builds I tested prior to releasing 1.16.0 also worked for me.

**Comment by crawr** [comment]
I've tested the generated vsix files and I was able to create a new zFTP profile and use it successfully in all 3 trees.

The release notes and changelog is clear and it describes the situation well. Thanks @lauren-li @zFernand0

**Review by zFernand0 — APPROVED** [review]
Changes look good to me 😋 
Thank for coordinating this.
The built VSIX also worked for me 👍

**Review by crawr — APPROVED** [review]

**Pull request merged**
