### PR TITLE
Fix webview for web

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Fix an issue where edit attributes webview never loads since `useEffect` hook returns instantly since call is from a non `vscode-webview://` endpoint. 

this endpoint is specific to local VS Code only, in web environments such as che or vscode.dev this may not be the case which caused the issue.

## Release Notes

Milestone: 2.11.1

Changelog: Fixed issue with webview not loading for web users

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by zFernand0** [comment]
> In web environments such as che or vscode.dev this may not be the case which caused the issue.

I can understand the reason behind wanting to check something other than local vscode webview protocols, however removing this check may result in a security vulnerability (see an example in the [Zowe CLI Sonar Cloud scans](https://sonarcloud.io/project/issues?resolved=true&types=VULNERABILITY&sinceLeakPeriod=true&pullRequest=1808&id=zowe_zowe-cli))

We should still check if we trust the origin of the request, maybe with `window.location.origin`?

**Review by zFernand0 — CHANGES_REQUESTED** [review]
Sorry, I forgot to request changes. :yum:

**Comment by zFernand0** [comment]
Re: 
image

I believe we can worry about cognitive complexity for this webview later on.
This is definitely not something to fix in this PR

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋

**Review by traeok — APPROVED** [review]
"Edit Attributes" view is working as expected in Theia, thanks @rudyflores for this fix 👍

**Pull request merged**
