### PR TITLE
Create Project non-User config when no config exists

### LINKED ISSUE #2684: Create a new Team Configuration File should not create User Config
**Actual Behavior**
When I click the "+" button in a tree view and select the option to "Create a new Team Configuration File", it creates zowe.config.user.json instead of zowe.config.json.

**Expected Behavior**
If I don't have any team config files yet, the "Create a new Team Configuration File" action should behave the same as `zowe config init` and create a zowe.config.json file which is what we recommend for new users.

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Resolves #2684

**How to Test**
In an environment with no team config file, creating a new team config file in ZE and selecting "Project" should create a Project Config (zowe.config.json) in the current project directory.
If a Project User Config (zowe.config.user.json) already exists, then ZE should detect that it exists and open that file.

## Release Notes

Milestone: v3

Changelog: Fixed default behavior of "Create a new Team Configuration File" to create a Project Config instead of Project User Config

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @t1m0thyj

**Review by traeok — CHANGES_REQUESTED** [review]
I noticed during testing that after clicking "Create a new Team Configuration File," the prompt for selecting "Project" or "Global" config wasn't shown - instead, it created a global, non-user config.

**Comment by traeok** [comment]
> @traeok that is default behavior to create global if no global, there could be an enhancement to always ask and not assume 😄

Oh okay, I did not realize that we skip the prompt if we can't find a global config - thanks for the clarification.
The PR instructions mention not having a team configuration file before testing, so that threw me off a bit 😅

**Review by traeok — APPROVED** [review]
Confirmed that this is the default behavior for v3, sorry for the confusion.
LGTM, thanks @t1m0thyj 👍

**Comment by JillieBeanSim** [comment]
Do we want to create an enhancement to always ask instead of assuming it will be a global if none exist?

**Comment by t1m0thyj** [comment]
> Do we want to create an enhancement to always ask instead of assuming it will be a global if none exist? @t1m0thyj @traeok

Investigated this and discussed with @traeok. When no config exists, we do ask the user whether they want to create Project or Global, but only if they have a workspace currently open in VS Code. If there isn't any workspace open, we skip the prompt because there's no project folder where we can create a Project Config.

**Pull request merged**
