### PR TITLE
Fix activation issue on Che

### PR DESCRIPTION
**Pull request by rudyflores**
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>

## Proposed changes

Fix issue with activating Zowe Explorer in Che environment related with `projectDir` being set `false` which broke activation on Che. This issue was found from a change on how we handle opening a config file when a workspace is not present: https://github.com/zowe/vscode-extension-for-zowe/pull/1939

## Release Notes

Milestone: 2.4.0

Changelog: Fixed  Zowe Explorer activation issue with Che environment 

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
Thanks for fixing the issue found during testing @rudyflores

**Comment by phaumer** [comment]
@JillieBeanSim @rudyflores I still get the same error in the log. This time there is no error dialog, just activation silently crashes and the log has the same errors:

```log
r [Error]: An error was encountered while trying to read the file ''.
Error details: ENOENT: no such file or directory, open

mDetails: {
    msg: "An error was encountered while trying to read the file ''.\n" +
      'Error details: ENOENT: no such file or directory, open',
    suppressDump: true

File was saved -- determining whether the file is a USS file or Data set.
 Comparing (case insensitive) /user/settings.json against directory /projects/temp/_D_and/projects/temp/_U_
```

`/user/settings.json` looks suspicious.

**Comment by phaumer** [comment]
The latest commit fixes the activation for global configuration files now. Thanks @rudyflores.

**Review by JillieBeanSim — DISMISSED** [review]

**Comment by JillieBeanSim** [comment]
I rebased my [PR](https://github.com/zowe/vscode-extension-for-zowe/pull/1979) to main removing these changes and activation is working as expected and all unit tests pass.  If it solve our issues I think this can be closed and the work from imperative with the use of string|false can stay otherwise we will still see the issue of config profiles being loaded other than global when no workspace is open @rudyflores @zFernand0 @phaumer

**Comment by JillieBeanSim** [comment]
closing in favor of #1979 which includes these commits

**Pull request closed without merging**
