### PR TITLE
Fix: "Allocate Like" execution stops due to error

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

- Fixes bug described in #1973 to allow `allocateLike` to continue execution
- **Update:** Originally #1974 was factored into this issue, but the block size problem appears to be an issue with z/OSMF REST client.
- Also updated logic in `removeFavorite` to skip `undefined` nodes

## Release Notes

Milestone: 2.5.0

Changelog: Fixed issue where "Allocate Like" feature fails to grab dataset node during execution

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
@traeok @zFernand0 should we get a couple unit tests for scenario to bring patch percentage up?

**Review by t1m0thyj — COMMENTED** [review]
This PR fixes the error that was thrown by the Allocate Like command 👍 

It seems like blksize is still not respected. The CNTL2 data set on the right was created by right-clicking on the CNTL data set on the left and selecting "Allocate Like":
image

I believe this is not a problem with Zowe Explorer, but rather it is the way that z/OSMF behaves. The CLI command `zowe files create data-set` with the `--like` flag has the same behavior where blksize is not respected. Perhaps on #1974, we should leave a comment to document this as a known issue with z/OSMF?

My only request for changes on this PR would be to add some tests as @JillieBeanSim suggested 🙂 While increasing "project" coverage is more of a long term goal, we do want to make sure that individual PRs have adequate "patch" coverage.

**Comment by traeok** [comment]
> I believe this is not a problem with Zowe Explorer, but rather it is the way that z/OSMF behaves. The CLI command `zowe files create data-set` with the `--like` flag has the same behavior where blksize is not respected. Perhaps on #1974, we should leave a comment to document this as a known issue with z/OSMF?

Was able to validate this as we only send one attribute to the z/OSMF REST Client for the "Attribute Like" command: `{ like: 'USERNAME.DATASET.TEST' }`. Renamed and reformatted this issue to reference the anomaly bug as that's what the fix technically solves - Allocate Like should function as intended once the block size issue is fixed within z/OSMF's REST API.

> My only request for changes on this PR would be to add some tests as @JillieBeanSim suggested 🙂 While increasing "project" coverage is more of a long term goal, we do want to make sure that individual PRs have adequate "patch" coverage.

Should be good to go now 👍

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @traeok for the fix

**Pull request merged**
