### PR TITLE
fix(DS/USS): Fix TypeError when saving w/ new search pattern

### LINKED ISSUE #2597: Cannot read properties of undefined when switching directories
**Describe the bug**

When I work in a file opened in some directory. If I keep this file opened in the editor and switch in the USS panel to a different directory to work on another file, when I try to save the file I get an error and cannot save the file.
There's no way I found to move away from the error other than closing the vscode window and opening it again, as even closing the file in the editor brings it back opened and still trying to save it with the same error.

**To Reproduce**

1. Open directory1, open file, make changes, save and keep it opened.
2. Switch to directory2, open file, make changes, try to save.
3. See error

**Expected behavior**

It should not fail, it was working before.

**Screenshots**

I'll add the screenshot as soon as I can.

**Desktop (please complete the following information):**

- OS: MacOS Venura 13.6
- Zowe Explorer Version: 2.12.2

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

Fixes #2597 

## Release Notes

Milestone: 2.13.0

Changelog:

- Fixed an issue where an opened USS file or data set could not be saved once a user changes their search pattern in the Side Bar. #2597 

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Comment by traeok** [comment]
SonarCloud quality gate is failing because of old test code with duplications - these duplications were not introduced from this PR

**Review by zFernand0 — DISMISSED** [review]
I honestly didn't consider this sort of behavior before.
Thanks for fixing the issue!
LGTM! 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks for this fix @traeok!
I was able to recreate the issue with released and this PRs fixes the error 😺

**Review by SanthoshiBoyina — APPROVED** [review]
@rudyflores! Thanks for the work.

**Pull request merged**
