### PR TITLE
Fix for unsecure profile token auth

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Solves #2518 

fix for token auth when using unsecure profiles. Before if using an unsecure profile, credential prompt for basic auth appeared after logging in, now this is handled properly.

## Release Notes

Milestone: 2.12.0

Changelog: Fixed issue with token based auth for unsecure profiles

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
Heads up this PR adds also the ability to access now the TreeProviders anywhere!!! this was necessary in order to refresh the elements after clearing it's prompts after performing a logout

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
@rudyflores I love the fact that this brings in the ability to clear the search filter after logout.  I did see one thing, I was in the Data Sets tree logging out after a search and got this error about the USS tree, nothing had been previously done in the USS tree either, if that helps recreate or troubleshoot
Screen Shot 2023-10-17 at 1 46 37 PM

**Comment by rudyflores** [comment]
FYI seems like the code smells are unrelated to my changes but got placed since changes in the same file were made

**Review by traeok — CHANGES_REQUESTED** [review]
Thank you for adjusting the tree provider initialization so they are accessible from anywhere! 🎉 This will make access much easier when working within the context of a node or when working within one of our defined actions.

I ran into a small issue when using a config with the following profiles:
- `zosmf-lab:` a profile with `tokenType` defined, no secure properties
- `zosmf-dev:` a basic profile w/ no secure properties
- a base profile with `host`, `port`, `tokenType` defined; no secure properties

To preface, I also disabled "Secure Credentials" for Zowe Explorer in VS Code's extension settings.

I noticed that when clicking the search button on the, it prompts me for user and password, and once I enter them in, they are added as "user" and "password" insecure properties:
UnsecureProfileTest

However, when I right-click on the profile and click "Manage Profile", I see "Log in with authentication service" now, which was not there before.

**Review by traeok — APPROVED** [review]
My previous review was inaccurate, as I accidentally broke the config by adding a `tokenType` somewhere where it shouldn't be 😅 

With a proper config, and using unsecured profiles, the token info is added to the base profile as expected. In addition, I can search the profile without the basic auth prompt appearing. LGTM

**Review by JillieBeanSim — APPROVED** [review]

**Review by traeok — DISMISSED** [review]

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
I got this when logging out in MVS and profile did use secure credentials

**Comment by rudyflores** [comment]
All good now! grabbed solution for checking for whether the property exists before assigning it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND_assignment

**Review by zFernand0 — CHANGES_REQUESTED** [review]
the code changes make sense.
However, I'm getting an error about setting `tooltip`
image

**Review by zFernand0 — CHANGES_REQUESTED** [review]
I was able to reproduce this issue if one of the 3 trees didn't have the node added to their list.

image

**Review by zFernand0 — APPROVED** [review]
Thanks for addressing the issue
LGTM! :yum:

**Review by JillieBeanSim — APPROVED** [review]

**Pull request merged**
