### PR TITLE
fix(ds): wait until contents are received to show editor

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

In some scenarios, if data set content did not finish downloading, any subsequent clicks on the data set node will cause the editor to appear without any content. The content is then added to the local document, but because of this, it can break extensions such as the COBOL language support extension. This PR adds some logic that will wait for the dataset node to finish fetching contents before opening the editor.

This also bumps the Secrets SDK to 7.18.4 because some bug fixes were not released as intended w/ 7.18.3.

## Release Notes

Milestone: 2.11.0

Changelog:

- Fixed issue where data set content does not always appear as soon as the editor is opened. [#2427](https://github.com/zowe/vscode-extension-for-zowe/issues/2427)

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found

### CODE REVIEW

**Review by awharn — DISMISSED** [review]

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @traeok!

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @traeok

**Review by JillieBeanSim — APPROVED** [review]

**Comment by traeok** [comment]
If possible, can we wait until tomorrow (when Secrets SDK 7.18.4 is published on NPM) to get this in 2.10.1? We ran into some issues with GitHub actions in our previous builds, and 7.18.3 doesn't have the most up-to-date binaries.

**Review by t1m0thyj — DISMISSED** [review]

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
when retesting the branch after changes I am seeing the error again when clicking the filename again before it opens in data sets view. Strange thing is the number following `...openPS/` changes
Screen Shot 2023-09-05 at 8 40 49 AM

**Comment by traeok** [comment]
> when retesting the branch after changes I am seeing the error again when clicking the filename again before it opens in data sets view. Strange thing is the number following `...openPS/` changes Screen Shot 2023-09-05 at 8 40 49 AM

This happens if another action was kicked off before the last action finished. I've addressed this in f2173d5c.

Wondering if the USS tree would benefit from this fix as well? #2422

**Comment by traeok** [comment]
Upon more research, I've discovered that both USS files/folders and data set nodes do *not* pull the latest content when clicked in the tree view. If the user right-clicks on the node and selects "Pull from Mainframe," it will grab the latest contents.

To keep the same behavior between the two trees, I will leave it as-is. It might be worth considering enhancing these trees to "refresh on node clicks" as a part of a separate issue/PR.

**Review by t1m0thyj — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @traeok

**Pull request merged**
