### PR TITLE
Remove validation check before updating profile

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Bug Fix: Remove validation check before updating profile, then after updating the profile it is revalidated and the icon is updated.

## Release Notes

Milestone: 1.18.0

Changelog: Bug Fix: Remove validation check before updating profile.

update-validation-issue

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by jellypuno — APPROVED** [review]
Thanks @JillieBeanSim ! This is the fix that I've come up with as well. The only thing I notice is that if the profile is already validated and then you updated the host/port then you have to do a search before it is validated again. But I think it is not a problem

**Comment by JillieBeanSim** [comment]
> Thanks @JillieBeanSim ! This is the fix that I've come up with as well. The only thing I notice is that if the profile is already validated and then you updated the host/port then you have to do a search before it is validated again. But I think it is not a problem

Hey @jellypuno I thought of that too.  What we could do is run the validation check at the end of the method vs waiting for search or other action that would kick off validation.  What do you think?

**Review by jellypuno — APPROVED** [review]
Works great! @JillieBeanSim

**Review by phaumer — CHANGES_REQUESTED** [review]
One issue I see is that when I cancel the update with ESC I get an error message the user would not understand.

**Review by phaumer — APPROVED** [review]

**Pull request merged**
