### PR TITLE
Migrate from yarn to pnpm

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Migrate to new package manager PNPM for improved install and build times for development vs Yarn

## Release Notes

Milestone: v3.0

Changelog: Changed Yarn package manager to PNPM package manager.

## Testing this PR

For testing this PR perform the following:

- run `pnpm i --shamefully-hoist=true` (this parameter is used to maintain hositing can be set as default in npmrc) https://pnpm.io/npmrc#shamefully-hoist
- run `pnpm build`
- run `pnpm package`
- run `pnpm test`
- run `pnpm fresh-clone` (this one uses the new concurrency feature!)
- try running any npm or yarn command (this should throw an error since only pnpm commands are allowed)

Make sure to test normal ZE functionality in the dev host as well as packaged extension to make sure everything is in order as well :) 

## Metrics

`fresh-clone` command:

**Yarn**
Screen Shot 2023-08-10 at 3 08 36 PM

**PNPM**
Screen Shot 2023-08-10 at 3 08 56 PM

`install` command:

**Yarn**
Screen Shot 2023-08-10 at 3 11 10 PM

**PNPM**
Screen Shot 2023-08-10 at 3 10 17 PM

`package` command:

**Yarn**
Screen Shot 2023-08-10 at 3 13 23 PM

**PNPM**
Screen Shot 2023-08-10 at 3 14 44 PM

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
Seems like there is an audit issue with two dependencies needing an update, should we update this here or has it been already addressed and we are waiting for it to be merged into next? @JillieBeanSim @zFernand0

**Comment by rudyflores** [comment]
FYI Seems like a Theia check is failing due to integration tests failing, it's also related to a v1 profile test which seems to be missing it's function, I believe this is because we removed all v1 functions and perhaps the next branch hasn't gotten the changes from main yet.

**Comment by zFernand0** [comment]
I might be doing something wrong, or maybe I should've installed `pnpm` not via `npm`, but... 😋 
- is anyone else getting a bunch of ` ERR_PNPM_ERR_PNPM_TARBALL_INTEGRITY `?
And since I can't install, I'm not able to run the build, and other commands in the description 😢

**Comment by rudyflores** [comment]
> * ERR_PNPM_ERR_PNPM_TARBALL_INTEGRITY

I would probably do a fresh clone before installing since there may be some conflicting files from yarn

**Review by t1m0thyj — CHANGES_REQUESTED** [review]
Thanks @rudyflores for performing this migration 🙂 

So far pnpm has been working great for me when testing this branch. A few questions:
* I can't review the PR easily because there a lot of changes that seem unrelated to pnpm, like new files added in `.github/actions` and several changes made to unit tests. Perhaps the PR needs to be rebased against a different commit?
* If the `shamefully-hoist` option is required, can we add it to an `.npmrc` file in the repo so that we don't have to remember to add it on the end of all our install commands? We could probably also remove the `.yarnrc` file and migrate it to `.npmrc`.

**Comment by rudyflores** [comment]
> Thanks @rudyflores for performing this migration 🙂
> 
> So far pnpm has been working great for me when testing this branch. A few questions:
> 
> * I can't review the PR easily because there a lot of changes that seem unrelated to pnpm, like new files added in `.github/actions` and several changes made to unit tests. Perhaps the PR needs to be rebased against a different commit?
> * If the `shamefully-hoist` option is required, can we add it to an `.npmrc` file in the repo so that we don't have to remember to add it on the end of all our install commands? We could probably also remove the `.yarnrc` file and migrate it to `.npmrc` 😋

Good suggestions, I think I will have to cherry pick some commits from this PR, and do this from a new branch, seems like the conflicts I attempted to resolve coming from next caused some commits unrelated to this PR be attached, which is why all those irrelevant files are popping up. 

As for the `shamefully-hoist` I agree, this could be a good fix for this and that way the regular `pnpm install` command can be run alone without issue.

**Comment by zFernand0** [comment]
The installation worked fine for me, but only after updating/creating an `.npmrc` file with the following contents
```
registry=https://registry.npmjs.org/
@zowe:registry=https://registry.npmjs.org/
```

**Comment by rudyflores** [comment]
> 

that might be good as well, I can go ahead and update the lock file.

I might have to research the docs to see if that can be cleaned, otherwise we could always ignore the file too!

**Comment by rudyflores** [comment]
Closing this PR in favor of https://github.com/zowe/vscode-extension-for-zowe/pull/2424

**Pull request closed without merging**
