### PR TITLE
Make sure we get an archive name in the Step Outputs

### PR DESCRIPTION
**Pull request by zFernand0**
Signed-off-by: zFernand0 <fernando.rijocedeno@broadcom.com>

## Proposed changes

- Set outputs regardless of whether there is a new version or not 😋 
- Comment out the ESLint upload step

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jellypuno** [comment]
@zFernand0 we merge the snapshot PR in master. Do you think we should update this with that?

**Comment by zFernand0** [comment]
> @zFernand0 we merge the [snapshot PR ](https://github.com/zowe/vscode-extension-for-zowe/pull/1468)in master. Do you think we should update this with that?

I don't know if we want to have snapshots on a `v1.zz.x` branch.

Side-comment: If we don't plan to have another hotfix before 1.19.0 goes out, we should merge this PR into master to avoid possible duplication of GH Draft Releases.

**Comment by jellypuno** [comment]
> > @zFernand0 we merge the [snapshot PR ](https://github.com/zowe/vscode-extension-for-zowe/pull/1468)in master. Do you think we should update this with that?
> 
> I don't know if we want to have snapshots on a `v1.zz.x` branch.
> 
> Side-comment: If we don't plan to have another hotfix before 1.19.0 goes out, we should merge this PR into master to avoid possible duplication of GH Draft Releases.

ok. so how about this, I can merge this to 1.18.x now then open a PR to master and add the `snapshot` condition in `Create github releases` (cause we encountered an issue there 😄 ) @JillieBeanSim @zFernand0 what do you think?

**Comment by crawr** [comment]
@zFernand0 since 1.18.1 has already been released, does this PR need to be updated with the base branch `master` instead?

**Comment by zFernand0** [comment]
I think I'm with Richelle on this.
As long as we don't plan to have a 1.18.2, we should be fine to change the base to `master` and just let it go : )

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim Maybe we can add a condition in `Create Github Releases` to not execute is the version has a `snapshot` on it. We can push that in this PR 😄

@zFernand0 I am not sure how to add the check needed in the `Upload the Zowe Explorer Assets` to avoid trying to upload with the `SNAPSHOT` in the versionName.  It just failed since it wasn't built and published.  Don't want it to fail but mainly to just output about not uploading to GitHub https://github.com/zowe/vscode-extension-for-zowe/actions/runs/1186664028

**Comment by JillieBeanSim** [comment]
@zFernand0 would something like this work to not create the release and run the uploads if `SNAPSHOT` is in the version name?

```
- name: Check version is bumped
        if: |
          ${{ !contains(steps.get_gh_version.outputs.tag, fromJson(steps.get_version.outputs.top_package).version) }} && 
          ${{ !contains("SNAPSHOT", fromJson(steps.get_version.outputs.top_package).version))}}
        run: echo "::set-output name=version_bumped::true"
        id: check_project
```

**Comment by zFernand0** [comment]
> ```
>           ${{ !contains("SNAPSHOT", fromJson(steps.get_version.outputs.top_package).version))}}
> ```

That should work! 😋

**Comment by JillieBeanSim** [comment]
> That should work! 😋

If you don't mind, I could push that change into your branch @zFernand0

**Comment by zFernand0** [comment]
> I could push that change into your branch
sure thing! 😋 
Please go ahead! : )

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @zFernand0

**Review by JillieBeanSim — APPROVED** [review]

**Comment by JillieBeanSim** [comment]
pushed the audit fix after merging master in for tar resolution from 6.1.2 => 6.1.9
image

**Review by jellypuno — APPROVED** [review]
LGTM!

**Comment by JillieBeanSim** [comment]
@zFernand0 looks like my addition broke it =(
https://github.com/zowe/vscode-extension-for-zowe/actions/runs/1189528202
image

**Comment by zFernand0** [comment]
(－‸ლ)
I think it might be a little picky about the double quotes :yum:
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions

**Comment by JillieBeanSim** [comment]
> `(－‸ლ)`
> I think it might be a little picky about the double quotes 😋
> https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#functions

looks like the contains may be backwards as well looking at the link `contains(search, item) ex. contains('Hello world', 'llo')` thanks for sharing the link, this is exactly what I was looking for and couldn't find lol

**Pull request merged**
