### PR TITLE
Issue a TSO Command

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

Be able to issue a TSO command using Zowe Explorer

## Release Notes

Milestone: 1.14.0

Changelog:  Added `Issue TSO Command` UI capability via right-click action on tree session and also available in the command palate. New API `ICommand` with `issueTsoCommand()` and `issueMvsCommand()`  for consumption by Zowe Explorer Extenders.

**NOTE** see https://github.com/zowe/vscode-extension-for-zowe/pull/1245#issuecomment-818762322 for information about new TSO integration test

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [x] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

For `zosmf` profiles there is a check for a `tso` profile, if non exist the user is prompted for `account number`, if one exists it will be automatically used for the `account number`, and if multiple exist the user will be presented with a list of tso profiles to choose from for the `account number`.  

For extenders, I have a check for the new API `ICommand` and if it is not existing I have an Error message that it is `Not implemented yet.`

tso-command-ZE

With the request to have the validation check change the icon automatically, I have run into an issue since this is available via all 3 trees and I do have the validation setting the icon but this is only showing when the session is clicked on after and not automatically, also a second validation is not run for that session.

tso-command-ZE-validation

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
MVS integration test fixed and new TSO integration test added

There is a change in the `testProfileData.examples.ts` which will need to be reflected in `testProfileData.ts` for tsoProfileName, this will allow the TSO integration test to access the named tso profile for account number needed for tso session with zosmf profile.
image

**Comment by JillieBeanSim** [comment]
ZE-integration-mvs-tso

**Comment by lauren-li** [comment]
@JillieBeanSim I'm not all the way done looking through the code for this yet, but it is functionally looking very good so far, and all unit/expected integration tests are passing. A couple small things I was wondering about:

- Would it make sense to check/ask for account number before the command?
- Do we want the "Not implemented yet" message to specify the extender or profile type that isn't supported? When we display "Not implemented yet", it kind of looks like we're trying to say this hasn't been implemented at all in Zowe Explorer yet (rather than for a specific extender). Perhaps this is something we want to create a reusable message for (for other new functionality we add in the future) - in which case it might be out of scope for this PR.

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim I'm not all the way done looking through the code for this yet, but it is functionally looking very good so far, and all unit/expected integration tests are passing. A couple small things I was wondering about:
> 
> * Would it make sense to check/ask for account number before the command?
> * Do we want the "Not implemented yet" message to specify the extender or profile type that isn't supported? When we display "Not implemented yet", it kind of looks like we're trying to say this hasn't been implemented at all in Zowe Explorer yet (rather than for a specific extender). Perhaps this is something we want to create a reusable message for (for other new functionality we add in the future) - in which case it might be out of scope for this PR.

These comments have been addressed for this PR, but having the `not implemented` message with profile type as reusable across Zowe Explorer would need to be done separately as the arguments sent to Error Handling function and everything that calls it would need to be rewritten to pass the whole profile: IProfileLoaded (to include type)  vs just profile.name so that would be a huge change.  I have it displaying with the profile type for MVS and TSO commands for now if extender hasn't brought in the new ICommandApi
image

I moved the prompt for acctNum to before the command, but this prompt is specific to `zosmf` profiles at this moment as FTP doesn't have it implemented yet and RSE doesn't require it.  Without being able to able to test other scenarios I am leaving it up to the extender to obtain their account number if needed in their API file vs unnecessarily prompting for it if not needed and confusing the user.  If a time comes that we may need to extend this scenario we can address it in the future.

**Comment by jellypuno** [comment]
This is amazing! Thank you for working on this @JillieBeanSim . I just skimmed through the code and tested the functionality itself and it looks good for me. I think there are additional features that I would like to see in the future. I can open a separate issue for that.

1. Enable users to create TSO profiles **or** save the account number in a buffer so I don't have to input it every time I want to issue a TSO command.
2. Separating the persisted MVS and TSO commands. So far, they are combined and it confuses me sometimes.

But overall, it works for me. Thank you!

**Review by jellypuno — APPROVED** [review]

**Comment by JillieBeanSim** [comment]
> This is amazing! Thank you for working on this @JillieBeanSim . I just skimmed through the code and tested the functionality itself and it looks good for me. I think there are additional features that I would like to see in the future. I can open a separate issue for that.
> 
> 1. Enable users to create TSO profiles **or** save the account number in a buffer so I don't have to input it every time I want to issue a TSO command.
> 2. Separating the persisted MVS and TSO commands. So far, they are combined and it confuses me sometimes.
> 
> But overall, it works for me. Thank you!

@jellypuno by persisted MVS & TSO commands do you mean the output window?  I just noticed the dropdown will have 2 of the same `Zowe Commands` where 1 is MVS and the other is TSO.  I totally didn't notice that before and thought I was doing something good reusing the code vs having it duplicated lol.  We can totally fix that in a hot fix or next release.

**Review by lauren-li — APPROVED** [review]
> I moved the prompt for acctNum to before the command prompt, but this prompt is specific to zosmf profiles at this moment as FTP doesn't have it implemented yet and RSE doesn't require it. Without being able to test other scenarios I am leaving it up to the extender to obtain their account number if needed in their API file vs unnecessarily prompting for it if not needed and confusing the user. If a time comes that we may need to extend this scenario we can address it in the future.

This sounds good to me. Thanks @JillieBeanSim for addressing my comments!

I also agree we probably want to separate the persisted commands for MVS vs TSO (i.e. the ones that appear in the dropdown), as well as their outputs, but I think it's fine to do this in a future PR. The TSO command functionality itself seems to be working very well. All unit and expected integration tests (plus the command submission test) are still passing for me.

This PR looks good to me!

**Pull request merged**
