### PR TITLE
Issue #1279b: Context menu group name standardization - dev

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

This PR contains `package.json` changes to standardize context group naming within Zowe Explorer as agreed upon in PR #1332 (First draft of menu command guidance).
Part B of addressing issue #1279 (Standardize Zowe Explorer context menus and document for extenders).

See comment #1279 (comment) for proposed Zowe Explorer command groups.

## Release Notes

Milestone: 1.16.0

Changelog: Minor updates to Zowe Explorer context menu groupings to standardize organization.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by IgorCATech — COMMENTED** [review]
Nothing much for me to review here. 
The only thing I've found was, in the package.i18n.json file, Line 40. Can we upper-case the rest of the first letters in all words?  "Create New File or Directory". This way we are consistent with the way the other options titles look.

And, maybe, we can chunk Line 70 for the sake of readability. The instruction is too complex, and rather not very clear, and can be divided for easier consumption. For example:

To enable the Secure Credentials Store plugin, type `Zowe-Plugin` value in the entry field. 

I don't understand what exactly 'specify @zowe/cli to describe a keytar-based solution' means. 
If that's an alternative way of enabling SCS, then we can word the instruction in the following way: 

"To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field." 

Also, what does "...stored in the clear" mean? :) Does it mean that if you don't enable SCS, your credentials are store in plain text? If yes, we should make it clear for our users. In this case, the description will be: 

"To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field. If you do not use SCS, your username and password are stored in plain text" 

or

 "To enable the Secure Credentials Store plugin, type `Zowe-Plugin` or `@zowe/cli` in the entry field. If you do not use SCS, your username and password are stored in plain text and are less protected"

**Review by katelynienaber — CHANGES_REQUESTED** [review]
Hello! Thank you for organizing this :)

- The Copy/Paste DS/Member commands looks funny being in a group on their own, since only one of these commands will ever show up at a time. They seem to fit in with Allocate Like, as copying commands. I would prefer to put Copy in with this category and remove either `01_zowe_mvsCreate` or `06_zowe_mvsCutCopyPaste` altogether.
- Refresh shows up in the `00_zowe_jobsMainframeInteraction` section of the context menu, but when I right-click on a profile in DS or USS tree, Refresh isn't there.
- The only thing you can do with a job in Favorites, is remove it. Maybe it was like this before, but it seems pointless to have a job in Favorites at all, if you will have to search for the job outside of Favorites anyway to do any action. If this was always like this, could we at least open an issue to address it?

**Comment by lauren-li** [comment]
> The only thing I've found was, in the package.i18n.json file, Line 40. Can we upper-case the rest of the first letters in all words? "Create New File or Directory". This way we are consistent with the way the other options titles look.

@IgorCATech It turns out this string was not being used. ("Create File" and "Create New Directory" are used instead.) As such, I have removed it from the files. Thanks for catching this!

> And, maybe, we can chunk Line 70 for the sake of readability. The instruction is too complex, and rather not very clear, and can be divided for easier consumption. For example:
> 
> To enable the Secure Credentials Store plugin, type `Zowe-Plugin` value in the entry field...
> 

This string update is out of scope for this PR. However, you have a valid point with this text being confusing. Issue #820 is dedicated to addressing this (Zowe Security: Credential Key is confusing). I think your comment would be an insightful contribution to the discussion for that issue.

**Comment by lauren-li** [comment]
> * The Copy/Paste DS/Member commands looks funny being in a group on their own, since only one of these commands will ever show up at a time. They seem to fit in with Allocate Like, as copying commands. I would prefer to put Copy in with this category and remove either `01_zowe_mvsCreate` or `06_zowe_mvsCutCopyPaste` altogether.

@katelynienaber The `cutCopyPaste` group is consistent with how VS Code (and many other applications) group their context menu items, although I think you're right that only one of these commands appears at a time depending on the context. The USS view also uses this group (the USS version of it) for its Copy Path command.

I asked one of our mainframers his opinion on grouping these commands, and he said he would actually just put all the dataset-related commands (including migrate/recall) in one group. This is different from either of our opinions, but I kind of like it. Maybe we could just lump all of them under `01_zowe_mvsSystemSpecific` (or `01_zowe_dsSystemSpecific` if we prefer to go with `ds` over `mvs`). What do you think of this suggestion? (@jellypuno @crawr and others, feel free to give your opinion on this, too!) It would look something like this:

PS:
Screen Shot 2021-06-04 at 4 50 55 AM

PDS:
Screen Shot 2021-06-04 at 4 50 41 AM

PDS member:
Screen Shot 2021-06-04 at 4 54 25 AM

> * Refresh shows up in the `00_zowe_jobsMainframeInteraction` section of the context menu, but when I right-click on a profile in DS or USS tree, Refresh isn't there.

This refresh was never a context menu item in DS or USS tree profiles. It was added specifically to the Jobs view's profiles only because the refresh is required to get a job's spool files after submitting it via the Data Sets view and opening it via clicking the job ID in the pop-up info message. If we want to add the refresh to DS/USS tree profiles, I would prefer it to be done as a separate enhancement PR.

> * The only thing you can do with a job in Favorites, is remove it. Maybe it was like this before, but it seems pointless to have a job in Favorites at all, if you will have to search for the job outside of Favorites anyway to do any action. If this was always like this, could we at least open an issue to address it?

Favorited jobs currently has the limited context menu selection you described, so I have opened issue #1341 to address this (Add normal Job context menu commands for favorited jobs).

**Comment by jellypuno** [comment]
@lauren-li I like it! 👍  I would prefer to name it zowe_ds rather than zowe _mvs. But that's just me. Also, why do we have 3 dots on upload member?

**Comment by lauren-li** [comment]
> @lauren-li I like it! 👍 I would prefer to name it zowe_ds rather than zowe _mvs. But that's just me. Also, why do we have 3 dots on upload member?

@jellypuno Actually, I also prefer `ds` over `mvs`. I will push a commit to update this, as I have already revised PR #1332 with this change.

The 3 dots on upload member indicates that an additional interface (the file picker) is associated with the command. (Similar to `Save As...` in VS Code.)

**Comment by lauren-li** [comment]
@jellypuno I updated this PR to use `zowe_ds` instead of `zowe_mvs` as we discussed (commit 2ed222c).

@katelynienaber Since you approved PR #1332 (First draft of menu command guidance), which describes the menu groups that are currently implemented in this PR, does that mean you're ok with this PR, as well? I have not made any updates to the way Data Set items are grouped, aside from implementing Richelle's suggestion to put migrate/recall in the `dsModification` group rather than its own group.

**Review by jellypuno — DISMISSED** [review]

**Comment by lauren-li** [comment]
Per today's Zowe Explorer scrum discussion, the `*cutCopyPaste` category will be removed. Data set Copy/Paste will be moved under `dsCreate`, and USS Copy Path will be moved under `ussSystemSpecific` as it copies the filepath on from the USS system.

This change will also be reflected in the corresponding documentation PR #1332.

**Comment by lauren-li** [comment]
@IgorCATech The gifs in the following sections of the [Zowe Explorer readme](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md) show content that will be affected by this PR:
- [Rename Data Sets](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#rename-data-sets)
- [Copy Data Set Members](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#copy-data-set-members)
- [Create data sets and specify the parameters](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#create-data-sets-and-specify-the-parameters)
- [Delete a data set member and a data set](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#delete-a-data-set-member-and-a-data-set)
- [Allocate Like](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#allocate-like)

The gifs in the readme sections listed below are currently out-of-date (even before this PR) due to icons that were removed in an earlier version of Zowe Explorer:
- [Use the save option to prevent merge conflicts](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#use-the-save-option-to-prevent-merge-conflicts)
- [View and access multiple profiles simultaneously](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/README.md#view-and-access-multiple-profiles-simultaneously)

For the [Zowe Explorer documentation](https://docs.zowe.org/stable/user-guide/ze-usage.html#usage-tips), most of the gifs (and videos) there are admittedly already outdated even with the current release of Zowe Explorer (1.15.1).

Thank you for your help in updating these!

**Comment by lauren-li** [comment]
> Per today's Zowe Explorer scrum discussion, the `*cutCopyPaste` category will be removed. Data set Copy/Paste will be moved under `dsCreate`, and USS Copy Path will be moved under `ussSystemSpecific` as it copies the filepath from the USS system.

@jellypuno @katelynienaber This PR has been updated with these changes. Can you please check to see how this PR looks to you now? Thanks in advance!

(For additional information on the `0` added to the Zowe Explorer context menu group prefixes, see https://github.com/zowe/vscode-extension-for-zowe/pull/1332#issuecomment-859125442.)

**Comment by IgorCATech** [comment]
@lauren-li Thank you for compiling this list for me! It's very helpful. I will get back to updating the doc after my vacation :)

**Review by katelynienaber — APPROVED** [review]
LGTM! Thanks for doing this :)

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
