### PR TITLE
Update master from v.1.3.x

### PR DESCRIPTION
**Pull request by zFernand0**
Pay closer attention to these files:

    Jenkinsfile
    __tests__/__unit__/extension.unit.test.ts
    __tests__/__unit__/utils/workspace.unit.test.ts
    src/ZoweUSSNode.ts
    src/dataset/dsNodeActions.ts
    src/extension.ts
    src/uss/ussNodeActions.ts
    src/utils.ts
    src/utils/workspace.ts

### CODE REVIEW

**Comment by Colin-Stone** [comment]
Is anyone else getting issues with integration tests for copy datasets?.

**Comment by zFernand0** [comment]
FYI, There is a vulnerability on the Zowe/CLI package.
Will address ASAP : )

**Comment by zFernand0** [comment]
> Is anyone else getting issues with integration tests for copy datasets?.

I'm afraid I only get the strange `Thenable` problems on my end. and a few timeouts in the `afterEach` hooks. Other than that, I don't see an issue with Copy.

**Comment by zFernand0** [comment]
Thanks for checking it out! 😸

**Pull request merged**
