### PR TITLE
Issue #968b: Group jobs’ favorites by profile and allow extenders to activate before loading profiles

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Addresses the following issues for the Jobs tree:
#968 (Favorites created by other extensions should not throw errors as the other extensions are not activated yet)
#168 (Group Favorites section based on profile)

See PR #984 (the equivalent for Data Sets) for a more detailed description of how this works.

Gif of GUI changes:
Zowe Explorer load-favs-by-profile-jobs

## Release Notes

Milestone: 1.9

Changelog: Group Jobs' favorites by profile, and load/set favorites’ profiles only when the user clicks to expand the relevant profile grouping node in the Favorites section.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

**Pre-existing issues related to Jobs favorites**
- Favorited jobs have no right-click context menu.
- Favorited searches in Jobs start out with a magnifying glass icon. After clicking on the favorited search, the icon changes to a folder icon with a validation circle. The user can then add a duplicate entry of that search to favorites settings.json and UI.
- User is able to effectively favorite the same search (for the same profile) twice - once in lowercase using the default search that occurs if they just expand the profile name, and once in uppercase (if they manually enter in the owner/prefix prompt with username and *).
- The ordering of favorited searches vs jobs can sometimes appear a bit random/inconsistent, especially when adding new favorites.

### CODE REVIEW

**Comment by jellypuno** [comment]
@lauren-li thank you for the change. I noticed something... if I remove all the favorites, the folder is not deleted. It is not a big deal because it will be gone once VSCode is restarted. I just expected it to be removed.

image

**Review by jellypuno — DISMISSED** [review]
Looks good to me. Functionality works.

**Comment by lauren-li** [comment]
> @lauren-li thank you for the change. I noticed something... if I remove all the favorites, the folder is not deleted. It is not a big deal because it will be gone once VSCode is restarted. I just expected it to be removed.
> 
> image

@jellypuno Thank you for reviewing! I agree with you on this. We can address it in a 1.9.x hotfix, as it would definitely improve the UX to immediately remove the profile node in Favorites when all its children favorites are gone. Similarly, I was also thinking to add a context menu option to the profile node allowing the user to remove it and all favorites associated with it. I am currently focusing on finishing the USS portion of this update for issues #968/#168, but would like to address removing the profile nodes from Favorites sections next.

**Review by JillieBeanSim — DISMISSED** [review]
@lauren-li thanks for your work on this! works great

**Comment by lauren-li** [comment]
Thanks for reviewing, @JillieBeanSim!

**Comment by lauren-li** [comment]
Description of the latest push:
- Updated this PR branch with the latest master branch.
- Per scrum discussion, added the line to sort profile nodes under Jobs' Favorites.
- Also added the line to sort profile nodes under DS Favorites per scrum discussion, as PR #984 for DS Favorites was already merged.

**Review by zFernand0 — APPROVED** [review]
LGTM!
Last one of the three (even though I messed up and merged USS before this one 😋 )
Looks clean!

**Pull request merged**
