### PR TITLE
Fix: Add theia checking for edit attributes

### LINKED ISSUE #1172: Do not display the Edit Attributes option in Theia
This is connected to PR #1092

### PR DESCRIPTION
**Pull request by jellypuno**
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

## Proposed changes

Fixes #1172 

Add a theia check before displaying the Edit Attributes dialog. This enhancement disables the Editing of Attributes feature in Theia environment.

theiaedit

## Release Notes

Milestone:
1.13.0
Changelog:
Disable editing of dataset attribute functionality in Theia environment

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jellypuno** [comment]
@katelynienaber I am actually not sure why do we need this change. I tested it and it is working in theia. Maybe we don't need it? maybe there's another reason?

**Comment by katelynienaber** [comment]
@jellypuno It is related to this comment: https://github.com/zowe/vscode-extension-for-zowe/pull/1092#pullrequestreview-578162120

**Comment by jellypuno** [comment]
@katelynienaber Thank you! I tested it and I am not experiencing that in Theia

@crawr I am not experiencing [this error](https://github.com/zowe/vscode-extension-for-zowe/pull/1092#pullrequestreview-578162120) anymore. I don't think we need this PR. If you are not experiencing this error anymore, please let me know. I will close this PR.

**Comment by crawr** [comment]
@jellypuno I tested this issue in Theia under v1.12.1 and it works if I use the keyboard to select the attributes instead of the mouse. So we can close this PR and issue #1172 .

However, I think we can still improve the behavior in Theia to detect even mouse selections. We can use issue #1167 to track this I think

**Comment by katelynienaber** [comment]
@crawr @jellypuno I think this is a general issue in Theia and maybe we should go over this throughout Explorer to make sure you can select things with the mouse everywhere

**Pull request closed without merging**
