### PR TITLE
Expression over statements

### PR DESCRIPTION
**Pull request by VitGottwald**
Signed-off-by: Vit Gottwald <vit.gottwald@gmail.com>

### CODE REVIEW

**Comment by crawr** [comment]
@VitGottwald can you please fill out the PR template so we know the description better?

**Comment by jellypuno** [comment]
@VitGottwald was this change tested? Can you also add a gif so that we could see what we need to test and see if there are no functional change. Thanks.

**Comment by VitGottwald** [comment]
There is no functional change. It is only a 3 line code cleanup to make the code more readable.

**Review by jellypuno — APPROVED** [review]
tested it and it works

**Review by crawr — APPROVED** [review]
Works well for me. I tested it in a Theia environment too 👍 
Thanks @VitGottwald

**Comment by crawr** [comment]
Theia tests and audit issues will be fixed in a different PR

**Pull request merged**
