### PR TITLE
Add deployment scripts

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

Add publishing steps for all packages in this repo. :yum: 

## Release Notes

Milestone: 1.11.0 : )

Changelog: Create deployment pipelines

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

### CODE REVIEW

**Comment by zFernand0** [comment]
Waiting for a PR: `Fix-github-actions -> master`

**Comment by zFernand0** [comment]
TODO:
- Automate publishing of VSCode extensions to https://open-vsx.org/

**Review by jellypuno — APPROVED** [review]
I trust you @zFernand0 😄

**Review by zdmullen — APPROVED** [review]
LGTM

**Pull request merged**
