### PR TITLE
Fix issue #1026: Handle empty profile folders in Favorites

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes
- This fix addresses issue #1026 (Handle empty profile folders in Favorites).
- This PR may also address part of issue #1020 (Unable to remove favorite profile from JOBS tree).

**Changes:**
(The following applies to all 3 trees - Data sets, USS, and Jobs.)
- Automatically remove a profile node in Favorites section when it becomes empty (i.e. the last favorited item under it is removed)
- Right-clicking on a profile node in Favorites provides an option for the user to manually remove that profile node (and its favorited items) from Favorites. (Provides a confirmation dialog.)

**Check for regressions:**
- If you delete a profile that has favorited items, the profile node in Favorites should also be removed (i.e. the same behavior as in `master` branch).
  - (The profile node should remain in Favorites if you only "hide" the profile.)

**Screen gifs:**
- Automatic removal of profile node in Favorites when it becomes empty:
ze-remove last fav
- Context menu option to remove profile node from Favorites:
ze-userSelect remove

## Release Notes

Milestone: 1.11

Changelog: Add handling of empty profile folders in Favorites.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [x] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — COMMENTED** [review]
@lauren-li this works really good functionally across all trees.  All expected checks and tests are passing.  I approve this pull request and think it will be good to merge in once we get the CI tests fixed and passing. Once that is corrected I will click the Approve button.

Thanks for all of your hard work on this.

**Review by katelynienaber — COMMENTED** [review]
I tested it out and it works for all 3 trees 💯 

I also noticed that you can `Remove Favorite` from the context menu...if it's a favorited DS or USS node. But for favorited Job nodes, there's no context menu. Maybe we could add it for continuity?

**Comment by JillieBeanSim** [comment]
> I tested out removing favorites and using the new context menu option, and it works for all 3 trees 🥇
> 
> I also noticed that you can `Remove Favorite` from the context menu...if it's a favorited DS or USS node. But for favorited Job nodes, there's no context menu. Maybe we could add it for continuity?

Jobs favorites is already different from the others so this would be a new issue to handle getting consistency on that view.

**Comment by lauren-li** [comment]
Thanks for reviewing this, @JillieBeanSim and @katelynienaber!

>I also noticed that you can Remove Favorite from the context menu...if it's a favorited DS or USS node. But for favorited Job nodes, there's no context menu. Maybe we could add it for continuity?

This is the case in the current Marketplace release (and `master` branch) of Zowe Explorer, so I wouldn't treat it as a regression of this PR. I agree with @JillieBeanSim that we can handle it in a separate issue/PR, but actually, I thought this would already be fixed via PR #957 (Context menu & menu bar edits) once that gets merged in. (@katelynienaber correct me if I'm mistaken, though!)

**Comment by katelynienaber** [comment]
> Thanks for reviewing this, @JillieBeanSim and @katelynienaber!
> 
> > I also noticed that you can Remove Favorite from the context menu...if it's a favorited DS or USS node. But for favorited Job nodes, there's no context menu. Maybe we could add it for continuity?
> 
> This is the case in the current Marketplace release (and `master` branch) of Zowe Explorer, so I wouldn't treat it as a regression of this PR. I agree with @JillieBeanSim that we can handle it in a separate issue/PR, but actually, I thought this would already be fixed via PR #957 (Context menu & menu bar edits) once that gets merged in. (@katelynienaber correct me if I'm mistaken, though!)

Yep, I had to check but it was already handled in #957 XD So nvm about this.

**Review by katelynienaber — APPROVED** [review]
LGTM

**Review by JillieBeanSim — APPROVED** [review]
@lauren-li this looks good to me, thanks for your hard work on this

**Pull request merged**
