### PR TITLE
Theia tests: updated according to zowe-cli 6.30.0

### PR DESCRIPTION
**Pull request by deepali-hub**
## Proposed changes

Updated Theia Tests according to zowe-cli version 6.30.0.
So for running THEIA tests make sure you have `ZOWE-CLI` version `6.30.0` locally and also you have latest `vsix` in `theia/plugins` folder.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by katelynienaber — COMMENTED** [review]
I am having the same tests fail locally, as are failing on this branch on GH (the 6 failing under Checks).

Please, could you take a look at these? Maybe @crawr will have a different result?

**Comment by crawr** [comment]
I'm also encountering the issue locally, even when updating to version `6.30.0` and recreating the `zosmf_meta.yaml` file. @deepali-hub is it possible that there is an additional prompt that needs to be added in `addProfileDetails` ? I know in this new version, protocol is prompted too, and it may require more wait time after the zosURL prompt.

**Comment by deepali-hub** [comment]
@crawr With addiing new additional prompt or without adding new additional prompt tests are working for me. Just I have increased SLEEPTIME to 15000.

**Comment by crawr** [comment]
@deepali-hub I found the issue. The new protocol field is non-empty and it shows a default `https` in the input box. I added a new locator to find it and added the new prompt to the `addProfileDetails`. I had to delete/define the `zosmf_meta.yaml` file so that it reflects the same one as the one generated by CLI  `6.30.0`. The theia tests are now green on this branch :tada:

Can you please take a look at my commit and let me know if I missed anything?

**Comment by deepali-hub** [comment]
@crawr yes after deleting old `zosmf_meta.yaml` i can see protocol input box and now tests are working fine.
Thank you so much :) 🎉

**Review by crawr — APPROVED** [review]

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
