### PR TITLE
[next] feat: Port `master` into `next`

### PR DESCRIPTION
**Pull request by zFernand0**
## Proposed changes

Port changes from master 😋 

## Release Notes

( N/A ? )

Milestone:  vNext.202202

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [x] I have added necessary documentation (if appropriate)
- [x] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
it looks like this one also included the updates in https://github.com/zowe/vscode-extension-for-zowe/pull/1653.  not sure if we should just let this one PR bring in all?

**Comment by zFernand0** [comment]
> it looks like this one also included the updates in #1653. not sure if we should just let this one PR bring in all?

I'm fine either way 😋 
That's why I made it it's own commit in case we wanted to remove that specific PR from this port 😄

**Comment by zFernand0** [comment]
I believe that if we decide to merge #1653 before this one, the only change in this PR would be that the lines changed will be less. 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @zFernand0

**Review by JillieBeanSim — DISMISSED** [review]

**Comment by zFernand0** [comment]
Seems like this PR is quite similar to https://github.com/zowe/vscode-extension-for-zowe/pull/1657
🎉 Do we want to maybe merge this one and see if there are changes left in the other one ?
🚀 Or should we just close this one in favor of https://github.com/zowe/vscode-extension-for-zowe/pull/1657

**Comment by zFernand0** [comment]
Will wait for #1668 (and maybe #1657) to be merged before updating this PR again 😋

**Comment by zFernand0** [comment]
Going forward, ze-build won't be duplicated (push and pull_request)

Only for this time, see the last non-skipped build in:
- [ze-build: port-master-prs](https://github.com/zowe/vscode-extension-for-zowe/actions/workflows/zowe-explorer-ci.yml?query=branch%3Aport-master-prs)
- [zftp-build: port-master-prs](https://github.com/zowe/vscode-extension-for-zowe/actions/workflows/zowe-explorer-ftp-ci.yml?query=branch%3Aport-master-prs) 
- [ze-thaia-build: port-master-prs](https://github.com/zowe/vscode-extension-for-zowe/actions/workflows/theia-zowe-explorer-ci.yml?query=branch%3Aport-master-prs)

**Review by JillieBeanSim — DISMISSED** [review]

**Comment by zFernand0** [comment]
"Whoops, I did it again" 🎵 
For the last set of builds, please see the merge commit checks
image

**Review by JillieBeanSim — APPROVED** [review]
Thanks @zFernand0 for pulling in all of the changes on `master` branch.

**Review by rudyflores — APPROVED** [review]
LGTM! Thanks Fernando for porting these changes!

**Pull request merged**
