### PR TITLE
Put back the AppScan configure file for security scan

### PR DESCRIPTION
**Pull request by raymondyanli**
Signed-off-by: Raymond Li <raymondyanli@gmail.com>

## Proposed changes

Zowe security scan needs to be done regularly in our internal pipeline. we are using AppScan Source for security scan. In order to run a scan, a configure file is required which is zowe-vscode-extension.ppf for vscode-extension-for-zowe. this configure file was added there a while ago, but it seems no longer exists there now. 

This PR is adding the configure file back to repo.
 
## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zFernand0** [comment]
Sounds like this file needs to be at the root of the repo.
it used to be there before the monorepo restructure and now lives under [packages/zowe-explorer](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/zowe-vscode-extension.ppf) 

Would you mind also removing it from there?

**Review by zFernand0 — DISMISSED** [review]
LGTM

**Comment by zFernand0** [comment]
Not sure where a178124 came from, but it's something the initial deployment pipeline wasn't able to do because of an issue it ran into. 
That said, I don't see a problem with updating these files on any PR, given that all 3 packages are already available `@1.12.0`

**Review by zFernand0 — DISMISSED** [review]

**Review by zFernand0 — DISMISSED** [review]

**Comment by zFernand0** [comment]
Failures due to version mismatch between internal dependencies.
Will clean the history of this PR (and remove a178124 from history)

**Review by zFernand0 — APPROVED** [review]

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
