### PR TITLE
Retain focus when submitting JCL files from editor right-click action

### LINKED ISSUE #2616: Submit as JCL fails for files opened in editor from MVS
**Describe the bug**

if file is opened from MVS tree then Submit as JCL selected in editor right-click last active text in VSC file explorer seems to be presented as the file for submission seen in confirmation box.  This is a regression from Submit as JCL initial work.

**To Reproduce**

1. Have file opened in editor from VSC tree view/workspace
2. Go to MVS tree and open a JCL file in editor
3. Right-Click file in editor 
4. Select `Submit as JCL` 
5. See file focus change in background while presented with profile for submission
6. See incorrect file name in confirmation box

**Expected behavior**

The file that was right-clicked on and Submit as JCL is chosen to be the file up for submission

**Screenshots**

**Desktop (please complete the following information):**

- OS: macos
- Zowe Explorer Version: latest
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Fixes #2616 

There was an existing issue when submitting JCL from the editor right-click option `Submit JCL`, if the use performed this action the JCL file focused in the editor will lose it's focus after clicking on `Submit JCL` which would cause the wrong job to be focused. This PR addresses that same issue.

## Release Notes

Milestone: v2.14.0
Changelog: Fixed issue with `Submit JCL` losing focus on JCL being submitted, causing the wrong job submission.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — APPROVED** [review]
LGTM, thanks @rudyflores!

---

One thing I noticed is that if you only have one profile set, then it will still prompt the user for a profile in the quick pick. It seems a bit redundant to show a quick pick with only one option, but that could be investigated as a future enhancement.

image

**Comment by rudyflores** [comment]
> LGTM, thanks @rudyflores!
> 
> Something I noticed: if you only have one profile set, it will still prompt the user for a profile in the quick pick. It seems a bit redundant to show a quick pick with only one option - in addition, we could probably determine the profile from the path of our on-disk temp. files, but those items could be implemented as part of a future enhancement.
> 
> image

Interesting find! And I agree this could be addressed in the future for better UX, do we have an issue made for that finding?

**Comment by traeok** [comment]
> Interesting find! And I agree this could be addressed in the future for better UX, do we have an issue made for that finding?

Filed as #2628 👍

**Review by JillieBeanSim — APPROVED** [review]
This works great! thanks for the fix @rudyflores

**Pull request merged**
