### PR TITLE
Fix "Log out from API ML" missing from Manage Profile menu

### LINKED ISSUE #2633: Log out from API ML is not available anymore with Manage Profile menu
**Describe the bug**

After using the "Manage Profile -> Log in to authentication service" option for the z/OSMF type of the profile and successful login, the "Log out" option does not appear anymore after the introduction of "Manage Profile" menu.

**To Reproduce**

1. Right click on the API ML type of profile in the Zowe Explorer Data Sets / USS / Jobs view (for me - "zosmf-apiml")
2. Select "Manage Profile".
3. Use "Log in to authentication service" item.
4. After login is successful, return to "Manage Profile" menu for the same profile and notice that only "Log in" is still available and not "Log out" (see screenshot below).

**Expected behavior**

After successful login to API ML using Zowe Explorer, it is expected to be able to logout using ZE too. For now the only way is to use Zowe CLI for that.

**Screenshots**

image

**Desktop:**

- OS: macOS 14.2
- Zowe Explorer Version: 2.13.0
- Zowe CLI Version: 7.18.8
- Are you using Secure Credential Store? Yes

**Additional info**

Base profile in the Team config:

```json
"base": {
            "type": "base",
            "properties": {
                "host": "apiml.services.net",
                "protocol": "https",
                "port": 60080,
                "rejectUnauthorized": true,
                "tokenType": "apimlAuthenticationToken"
            },
            "secure": [
                "tokenValue"
            ]
        },
```

Actual z/OSMF profile:

```json
"zosmf-apiml": {
    "type": "zosmf",
    "properties": {
        "basePath": "/ibmzosmf/api/v1"
    }
}
```

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

Fixes #2633. The patch was made in Imperative, so the only changes in this PR are to update the Zowe CLI package and fix unit tests that broke locally after updating to Node 20.

## Release Notes

Milestone: 2.14.0

Changelog: N/A since this bug fix is already listed in the changelog

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @t1m0thyj for the quick fix

**Review by zFernand0 — DISMISSED** [review]
LGTM! 😋

**Review by adam-wolfe — APPROVED** [review]
LGTM

**Review by zFernand0 — APPROVED** [review]
thanks for addressing the possible scenario of tokenType being `undefined`.
And sorry for giving you a hard time about negating an optional-chaining operator. (offline)

LGTM! 😋

**Review by awharn — APPROVED** [review]

**Pull request merged**
