### PR TITLE
fix(jobs): Job tree not creating new nodes after submitting job

### LINKED ISSUE #2370: Tree refresh options broken in Jobs tree
**Describe the bug**

tree will not refresh with multiple options: view refresh, right-click refresh on session, close and open session, & redo search filter all broken and won't update tree

**To Reproduce**

1. open a search filter in Jobs view
2. submit job
3. try to refresh jobs view to show new job submitted
4. see it won't update with any way available

**Expected behavior**

video of behavior in v2.9.0

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/8a866bf2-aade-4172-9ec1-311daf81dc4f

**Desktop (please complete the following information):**

- OS: mac
- Zowe Explorer Version: 2.9.1
- (Optional) Zowe CLI Version:
- (Optional) Are you using Secure Credential Store?

**Additional context**

### PR DESCRIPTION
**Pull request by traeok**
## Proposed changes

This PR should fix the issue where job nodes are not being created after submitting a job and then clicking "Refresh".
To verify, open a session in the jobs tree and search for a filter. Once searched, go to the data sets tree and submit a job. Come back to the jobs session and right click -> select "Refresh." The new job should appear in the list of children.

Fixes #2370 and #2376 

## Release Notes

Milestone: 2.9.2

Changelog:

- Fix bug in 2.9.1 where job session nodes were not updated with new nodes.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
Thanks @traeok for jumping on this bug so fast.  I do notice it adds to bottom of list now vs how it was handled in 2.9.0 but glad it's updating the trees again.

I see some overlap in this PR and https://github.com/zowe/vscode-extension-for-zowe/pull/2363 with 'No Jobs Found' return.  Wonder if we should sync the 2, FYI @rudyflores

**Comment by traeok** [comment]
> Thanks @traeok for jumping on this bug so fast. I do notice it adds to bottom of list now vs how it was handled in 2.9.0 but glad it's updating the trees again.

No problem! Sorry for not catching this previously when making changes to `getChildren` 😅 

Regarding adding to the bottom of the list, this can be addressed in this PR as well - I might have missed a step with the sorting, and I should be able to replicate 2.9.0's behavior.

> I see some overlap in this PR and #2363 with 'No Jobs Found' return. Wonder if we should sync the 2, FYI @rudyflores

I actually added that as a last-minute fix because we were not returning early when the API returned w/ 0 jobs. Would definitely be glad to merge in 2363 and then rebase my branch 👍

**Comment by JillieBeanSim** [comment]
audit fix PR against maintenance https://github.com/zowe/vscode-extension-for-zowe/pull/2372

**Review by t1m0thyj — DISMISSED** [review]
LGTM, thanks @traeok!

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
I am seeing a breakage on this PR branch vs 2.9.1 in marketplace when search criteria changes

v2.9.1 

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/ad3306fd-13af-4d26-ab51-6e6e434a30fe

PR branch

https://github.com/zowe/vscode-extension-for-zowe/assets/49491949/7a7cce2c-4e0f-4758-b5fd-9059e9dde4a7

**Comment by traeok** [comment]
> I am seeing a breakage on this PR branch vs 2.9.1 in marketplace when search criteria changes
> 
> v2.9.1
> (snip)
> PR branch
> (snip)

@JillieBeanSim , do you mind confirming whether this was resolved with commit [d9133f4](https://github.com/zowe/vscode-extension-for-zowe/pull/2371/commits/d9133f4bba1fb1ec1e48957c94e2faf2e449809b)? The filtering logic had a few oversights. Thanks!

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks for fixing the regression @traeok!

**Review by zFernand0 — APPROVED** [review]
Thanks for fixing, it's definitely a smoother workflow. No need to refresh Zowe Explorer 😋 
LGTM! 😋

**Pull request merged**
