### PR TITLE
Enable/Disable validation for all trees

### PR DESCRIPTION
**Pull request by rudyflores**
## Proposed changes

Solves https://github.com/zowe/vscode-extension-for-zowe/issues/2570

Disable/enable validation for profile in all trees when clicking disable/enable validation in the `Manage Profile` menu

## Sample

https://github.com/zowe/vscode-extension-for-zowe/assets/68666202/7ff97942-51b0-4ce9-91fa-71183b615fba

## Release Notes

Milestone: v2.13.0

Changelog: Add support for enabling/disabling a Zowe profile across all trees

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by traeok — CHANGES_REQUESTED** [review]
I like these per-tree options, should help with personalizing the Zowe Explorer UX a bit more 😋 

I'm running into an issue where disabling the profile validation for one tree ends up disabling it for all trees. Here's a GIF showing this behavior:

ZE-Validation-PerTree

**Comment by rudyflores** [comment]
> I like these per-tree options, should help with personalizing the Zowe Explorer UX a bit more 😋
> 
> I'm running into an issue where disabling the profile validation for one tree ends up disabling it for all trees. Here's a GIF showing this behavior:
> 
> ZE-Validation-PerTree [ ZE-Validation-PerTree ](https://user-images.githubusercontent.com/86500639/283504137-876c2f49-508e-42a0-afb2-41408805bb4d.gif) [ ](https://user-images.githubusercontent.com/86500639/283504137-876c2f49-508e-42a0-afb2-41408805bb4d.gif)

Interesting, if you click disable profile and disable only for one profile and then check the profile in another tree in the `Manage Profile` menu it will show the profile as enabled (which is what we want) but seems to actually behave differently, looking into this rn...

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks for addressing the issue @rudyflores

**Review by traeok — APPROVED** [review]
LGTM, thanks @rudyflores!

**Pull request merged**
