### PR TITLE
Issue 928 bug fix USS Save

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>
https://github.com/zowe/vscode-extension-for-zowe/issues/928

## Proposed changes

Pass etag to putContent()/putContents() so if the file has changed on the mainframe while editing with zosmf profile the etag compare should not match and the compare pop up should show allowing the user to overwrite what's on the host or not.

## Release Notes

Milestone:
1.7.x or 1.8.0

Changelog:
Bug Fix: Pass etag as to not automatically overwrite changes between local and the mainframe.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by phaumer** [comment]
@zFernand0 @dkelosky as this is a breaking bug I recommend that we should actually merge this into the v1.7.x branch and publish it as a fix as we are getting reports from users who cannot save on USS anymore.

**Comment by phaumer** [comment]
@dkelosky NP. As these are Extensibility API calls, changing the parameters of these can break potential extenders. So we need govern those kind of changes differently in the future perhaps.

**Comment by dkelosky** [comment]
@phaumer, I agree. 

Ironically, the challenge with the original PR was that ‘putContents’ isn’t easily extendable because it doesn’t take an option object. I introduced an optional API extender method ‘putContent’ which takes an object and conditionally check if the new method exists before calling it and marked the old method for depreciation. 

In this  segment of code though, I wasn’t careful enough in my conditional checking and calling the old method. 

Will you implement ‘putContent’ in your RSE and FTP extension?

**Comment by lauren-li** [comment]
This PR looks good to me! Issue #928 appears to be resolved in manual testing with this PR. Unit tests all passing.
I get 3 failing integration tests, but they are also failing in the master branch for me:

```
1) mvsCommands integration test
       Submit an MVS command
         should submit a command:
```

 ```
 2) DatasetTree Integration Tests
       removeFavorite()
         should remove the selected favorite search from the treeView:
```

```
3) Extension Integration Tests
       Tests for Deleting Data Sets
         should delete a data set if user verified:
```

@JillieBeanSim @dkelosky I would approve this PR, but I'm holding off on it because I think we might want to switch the base branch of this PR to be a hotfix branch (1.7.x) rather than master, seeing as it's a bugfix. Especially if there are things like Webpack going into the master branch. What do you all think?

**Comment by dkelosky** [comment]
That makes sense - @zFernand0?

**Comment by zFernand0** [comment]
For those who were not able to attend the Zowe Explorer standup today, the final outcome is:
- Merge #929, #888 #926 into master ASAP
- Migrate the merge commits to the v1.7.x branch
  - At the same time, #860 can be merged into master
- Release a v1.7.1


For integration tests problems, please see a compilation  of all the comments in #892 

For unit tests coverage, please see #931

**Comment by lauren-li** [comment]
@zFernand0 Thank you for that comment clarifying the order of operations! Very helpful.

**Comment by zFernand0** [comment]
@dkelosky Should we limit the codecov upload to a single instance (combination on node version and system)?
It gets all funky when it tries to upload so many reports to codecov :(

**Comment by phaumer** [comment]
@dkelosky that was discussed before and we had decided to make that change for 2.0 and just add missing parameters as optional in the mean-time.  I should have probably made the decision rationale explicit in code comments to communicate to everyone. Instead of creating a new method, though, why not override the current one with alternative signatures?

**Comment by dkelosky** [comment]
I decided to make the new method because it was inconsistent with the others:  `ZosmfMvsApi.putContents`, `ZosmfMvsApi.getContents`, and `ZosmfUssApi.getContents` all took an option object from Zowe CLL.  

`ZosmfUssApi.putContents` was the only different one taking a list arguments.   Perhaps I could have gone another direction, but my initial reasoning was to make them more consistent.  Do you agree?

**Comment by phaumer** [comment]
I agree(d), but it was not breaking anything. So we had thought to do that for 2.0 as a breaking change. There was an earlier PR about this from someone else and the resolution was not to do it, yet.  That's how the whole discussion around the need for governance started in the first place.

I guess, now that it is out there anyway we should start switching in the extensions once etag support is working again.

**Comment by dkelosky** [comment]
Gotcha - I missed that previous discussion.  I intended to do this transparently without breaking anything and being backward compatible (obviously I failed for this code path).  I'll keep a closer eye out for this in the future.

Thanks,

**Pull request merged**
