### PR TITLE
Add pop up message for Che refresh issue

### PR DESCRIPTION
**Pull request by rudyflores**
Signed-off-by: Rudy Flores <68666202+rudyflores@users.noreply.github.com>

## Proposed changes

Added a pop up error message when a silent refresh is performed on Che after creating a team config file.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by rudyflores** [comment]
[An issue was filed with imperative ](https://github.com/zowe/imperative/issues/824) so we can solve this issue once those changes are performed, for now this PR will add an error message to better inform users about what is the issue.

**Review by JillieBeanSim — APPROVED** [review]
I thought we wanted to have the try/catch around the entire activation so anything that fails during activation wont break extenders that require Zowe Explorer in their package.json

**Comment by kristinochka** [comment]
Yes, we discussed preventing activation from breaking. I remember from testing this a few days ago in Che when user creates a V2 profile with secure fields, ZE breaks completely, extenders don't activate and user can't edit the profile from ZE menus, they have to find the profile via the command line to fix the activation.

**Comment by kristinochka** [comment]
This is the related ticket: https://github.com/zowe/vscode-extension-for-zowe/issues/1807

**Review by zFernand0 — COMMENTED** [review]
These changes LGTM!
Happy to formally approve the PR if needed 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM thanks @rudyflores

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
