### PR TITLE
Bug fix to prompt for creds when issuing MVS command

### PR DESCRIPTION
**Pull request by JillieBeanSim**
Signed-off-by: Billie Simmons <49491949+JillieBeanSim@users.noreply.github.com>

## Proposed changes

address issue https://github.com/zowe/vscode-extension-for-zowe/issues/1168 to prompt for creds with profiles missing creds when issuing MVS commands via right click action.

prompt-creds-commands

## Release Notes

Milestone: 1.13.1 or higher

Changelog: Bug fix to prompt for creds on profiles without when issuing MVS commands via right click action.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by katelynienaber — CHANGES_REQUESTED** [review]
If I have a profile with no creds (as described in the issue) and I try to Issue MVS Command, I now get prompted.

But if I cancel the prompt, it continues on and asks me which profile I'd like to use with my MVS command.

I'd expect the command to be canceled when I refuse to input my password (since it won't work anyway without creds).

issueMvsGif

**Review by lauren-li — COMMENTED** [review]
This looks good to me! All unit and expected integration tests are passing. Functionally, this PR resolves the linked issue and I now get prompted for creds when trying to right-click a credential-less profile and issue an MVS command. The issue @katelynienaber mentioned earlier about Issue Command continuing even after no creds are input also appears to be fixed.

The only thing, which I'm not sure is in-scope for this PR, is that the profile validation check doesn't seem to update the profile's status circle (unlike with data set search). This seems to be the case whether or not credentials entered at the prompt are saved, and also happens if the profile's status was invalid from earlier credential-less actions but then the user enters their creds when issuing the command. I attached an example gif below. If this is considered out-of-scope for this PR, then I will go ahead and approve this PR.

ze-issueCmdStatus

**Comment by JillieBeanSim** [comment]
@lauren-li since this validation behavior is pre-existing I wasn't planning on fixing it in this PR.  I can look into it with the TSO command implementation since I will also need to have that command do the same so I could easily add that solution to MVS command.

**Comment by lauren-li** [comment]
@JillieBeanSim Sounds good. I'll add my approval for this PR then. :)

**Review by lauren-li — APPROVED** [review]

**Review by jellypuno — APPROVED** [review]
Looks good!

**Pull request merged**
