### PR TITLE
Disallowed multi-word profile names in job search.

### PR DESCRIPTION
**Pull request by katelynienaber**
Please check and see if this is what you need.

image

Signed-off-by: katelynienaber <katelyn.nienaber@broadcom.com>

### CODE REVIEW

**Comment by Colin-Stone** [comment]
What defect does this relate to?. The code relates to the user enter an owner id but the text added describes a profile.

**Comment by katelynienaber** [comment]
> What defect does this relate to?. The code relates to the user enter an owner id but the text added describes a profile.

This was in relation to issue [#263](https://github.com/zowe/vscode-extension-for-zowe/issues/263). Sorry didn't notice there was no reference number.

**Comment by Colin-Stone** [comment]
Thanks @katelynienaber, so maybe the text should be different ?. Owner rather than profile?.

**Comment by katelynienaber** [comment]
> Sorry but I had missed the fact that no localize appears around the text you have updated so it hasn't being translated you should probably have put `validateInput: (value: string) => (value.match(/ /g) ? localize("jobs.enter.valid.owner", "Please enter a valid owner name (no spaces allowed).") : "")`

Should I also add this localize function to my edits on pull request [#434](https://github.com/zowe/vscode-extension-for-zowe/pull/434)?

**Pull request merged**
