### PR TITLE
Move the extension to import the latest version of the CLI

### PR DESCRIPTION
**Pull request by zFernand0**
Changed all references of `brightside` to `zowe`. :smile:

### CODE REVIEW

**Comment by zFernand0** [comment]
This PR should be one of the last ones to go in (If not the last one) for the issues on the GA milestone.
That way others can continue working without much interruptions before the GA 1.0.0 release : )

**Comment by jellypuno** [comment]
@zFernand0  With this we can also use the latest SCS?

**Comment by zFernand0** [comment]
> @zFernand0 With this we can also use the latest SCS?

@jellypuno, that's correct. Please let me know if you find any oddities. : )

**Comment by zFernand0** [comment]
In order to merge this, we need a few things ported into the `@latest` versions of imperative and CLI.
https://github.com/zowe/zowe-cli/issues/596 related to #349

**Comment by zFernand0** [comment]
Feature postponed.
Closing

**Pull request closed without merging**
