### PR TITLE
Check Credentials error disappearing too quickly bug fix

### PR DESCRIPTION
**Pull request by JillieBeanSim**
## Proposed changes

Standardized the popups for `Check Credentials` and `Save Credentials` with VS Code's standard message with buttons that require user interaction as to not get lost in the notifications

## Release Notes

Milestone: 1.19.0

Changelog: Bug fix for the Check Credentials popup error disappearing too quickly.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

check-creds-bugfix

### CODE REVIEW

**Comment by katelynienaber** [comment]
Looks great!

Small nitpicky thing, there's an extra space in the dialog, at `profilename  are valid`:
image

@jellypuno if you're feeling pressed for time with merging everything I can approve it anyway. It's a really small thing.

**Comment by jellypuno** [comment]
> Looks great!
> 
> Small nitpicky thing, there's an extra space in the dialog, at `profilename are`:
> image
> 
> @jellypuno if you're feeling pressed for time with merging everything I can approve it anyway. It's a really small thing.

@katelynienaber #goodfirstissue 😆

**Comment by katelynienaber** [comment]
@jellypuno I opened new issue for extra space [here](https://github.com/zowe/vscode-extension-for-zowe/issues/1494).

**Comment by JillieBeanSim** [comment]
> @jellypuno I opened new issue for extra space [here](https://github.com/zowe/vscode-extension-for-zowe/issues/1494).

Thanks @katelynienaber I didn't touch that part of the code, wonder if it's more noticeable with the new pop up confirmation

**Review by jellypuno — APPROVED** [review]

**Review by katelynienaber — APPROVED** [review]
LGTM

**Pull request merged**
