### PR TITLE
USS add create and remove node functionality

### PR DESCRIPTION
**Pull request by kristinochka**
Related to: https://github.com/zowe/vscode-extension-for-zowe/issues/36

image
Delete node
create file

### CODE REVIEW

**Comment by MikeBauerCA** [comment]
Just from the commit list, I am very eager to try this functionality! Thank you for the contribution!!

**Comment by kristinochka** [comment]
@MikeBauerCA I have signed all my commits now so the checks are passing. Please, take a look.

**Comment by MikeBauerCA** [comment]
@Colin-Stone @ChrisBoehmCA could you please review this PR?

**Comment by ChrisBoehmCA** [comment]
Hi

Pretty cool stuff! Thanks for the changes. 

I noticed a few things. When creating a USS directory or file, the text in the background says "Name of Member". It should probably say Name of USS File  or Name of USS Directory depending on which thing the user clicked. 

I'm also getting this error sometimes when deleting USS directories, but then the delete seems to succeed as the files are gone. In fact if I delete a directory with nested directories, I get this error twice from one click of "Delete". Ever seen this? I wonder if it's coming from the call to delete or the call to refresh the directory after the delete? 

image

**Comment by Colin-Stone** [comment]
Shouldn't be adding the extra slash being prepended to the directory. This is because of a flaw in the zosmf API and corrupts the saved value. URLEncodoing is an option

**Comment by kristinochka** [comment]
@ChrisBoehmCA I made a fix Collin suggested, could you try again? The issue should be gone.

**Comment by ChrisBoehmCA** [comment]
Thanks. 
I still got the error a few times deleting directories though, but can't reliably reproduce it. I got it a few times when I first started and then have been trying to reproduce it for a while to no avail. I guess it's a timing based thing where if a refresh  (or something) is already happening when I delete, it causes an error. But it doesn't seem like an issue with deleting itself because I've tried many times now without the error. 

I noticed that if you delete a file or folder at the top level, the view doesn't refresh until you manually click the refresh button. But for folders nested deeper it automatically refreshes. could this be fixed? 

Also it seems like there's no way to add a new file or directory to the top level folder you specify. For example if I enter /u/users/myuser I can't create /u/users/myuser/myfile.txt by right clicking on the profile name.  I guess you can get around this by specifying the parent directory though

**Comment by Colin-Stone** [comment]
I'm happy with these changes, thanks Kristina.

I saw some few issues with directory refresh similar to what Chris described but I don't feel is related to these changes.

I vote we should Approve and Publish

**Pull request merged**
