### PR TITLE
fix uss etag issue

### PR DESCRIPTION
**Pull request by tiantn**
Signed-off-by: tiantn <tiantn@cn.ibm.com>

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by tiantn** [comment]
fix #1732

**Review by std4lqi — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]

**Comment by mmoore96** [comment]
@tiantn @std4lqi  
Thank you, @tiantn, for making this fix.
I was able to build the pre-production Zowe master and test it my-self.
It is working so much better. I am not longer getting as many errors.

However, there is an edge case in which you can still throw an error that is not expected:
Open a .java file
Make an edit and save it (which is successful).
Right click on the .java file in the USS section and select "Pull from Mainframe."
Edit the .java file again and save it. <----This results in a merge conflict error (used to be 412 error)
You can select "Pull from Mainframe" again and then try to make an edit and it will save successfully.

As a user, I should not have to pull from the mainframe in order to avoid this error. This causes my code changes to be removed and is a headache.

I do understand that there is a chance someone else has made a change to the file since your last pull. However, in my experience there is quite rare unless two people are working on the same file which does not happen very often. We have our own directories/pds' that we edit our own version of a program in. You could argue that if the same user used tn3270 to make a change then went back to zowe and started writing code then that would be problematic. However, the user should know that they need to pull from mainframe first.

I think a good solution to fix this problem would be to ask to user if they would like to override the save conflict.

Thank you!

**Comment by tiantn** [comment]
Hi @mmoore96 , thank you for giving us the feadbacks and good advices.

**Comment by mmoore96** [comment]
Thank you, @tiantn, 

I think that is a good workaround for the interim. However, shouldn't the issue be fixed? When I edit Datasets, I do not get this error. 
I am not sure how the logic was implemented but there seems like there is a bug in USS that is not in Datasets. 
It seems like the merge conflict logic for USS files should be similar to datasets. 

In the meantime, could a JSON setting be added where merge conflicts can be ignored and changes from zowe override the mainframe's copy?

Thank you!

**Comment by mmoore96** [comment]
@tiantn 
I have been looking over the code and making my own changes to try and get this fixed. 
I have found a few things:
1. The current merge conflict logic does not actually work. 
I made a change to a file on the mainframe in USS and I had a copy prior to the edit on Zowe. I made a change and went to submit it and it was successful. But we would expect that a merge conflict error would be thrown.

2. The current implementation for putContents is deprecated. I have changed the code to use putContent. It works without any issues.

### From ZoweExplorerApi.ts:
```typescript
/**
         * Uploads the file at the given path. Use for Save.
         *
         * @deprecated
         * @param {string} inputFilePath
         * @param {string} ussFilePath
         * @param {boolean} [binary]
         *      Indicates if a conversion should be attempted or treated as binary.
         * @param {string} [localEncoding]
         *      Optional encoding that can be used by an implementation to overwrite defaults
         * @param {string} [etag]
         * @param {boolean} [returnEtag]
         * @returns {Promise<zowe.IZosFilesResponse>}
         */
        putContents(inputFilePath: string, ussFilePath: string, binary?: boolean, localEncoding?: string, etag?: string, returnEtag?: boolean): Promise<zowe.IZosFilesResponse>;
        /**
         * Uploads the file at the given path. Use for Save.
         *
         * @param {string} inputFilePath
         * @param {string} ussFilePath
         * @param {zowe.IUploadOptions} [options]
         * @returns {Promise<zowe.IZosFilesResponse>}
         */
        putContent?(inputFilePath: string, ussFilePath: string, options?: zowe.IUploadOptions): Promise<zowe.IZosFilesResponse>;
```
### Current code:
```typescript
 public async putContents(
        inputFilePath: string,
        ussFilePath: string,
        binary?: boolean,
        localEncoding?: string,
        etag?: string,
        returnEtag?: boolean
    ): Promise<zowe.IZosFilesResponse> {
```

### My changes:
```typescript
public async putContent(
        inputFilePath: string,
        ussFilePath: string,
        options: IUploadOptions
    ): Promise<zowe.IZosFilesResponse> {
```

3. Clicking on an already opened member in USS does not perform the same way as Datasets.
When I click on a member in USS it performs a pull from mainframe. However, in Datasets this only occurs iff the file has not been opened.

 
## Reason for Failure
After debugging Zowe Explorer, I have found the reason for the unexpected behavior:
1. There is a mismatch between the etag generated when a file was pulled from the mainframe vs. the etag generated (via AppData/temp) when the user is trying to save a file to the mainframe. 

## Example:
etag while pulling file:
`aae07e719efee348b52aaf26f9398ef2a30b5537`

Make a change and then try to save: 
`da39a3ee5e6b4b0d3255bfef95601890afd80709`

Which results in an error being thrown:
`Save conflict. Please pull the latest content from mainframe first.`

## My thoughts:
I noticed a lot of inconsistences in the actions.ts file between Datasets vs. USS. Some of theses has to do with how etags are set via IUploadOptions. I think this could also be the culprit. 

At this point, I have stepped through this program and tried to fix this etag issue but it still persists. I am not super familiar with all the code in Zowe Explorer so please correct my analysis if I am mistaken.

I wanted to give you this information to see what you thought and if you could offer any more guidance or recommendations. 


Thank you!

**Comment by tiantn** [comment]
Hi @mmoore96, thank you for providing these information. It is really helpful. @std4lqi and I work together today. And we have some findings.

```
1.The current merge conflict logic does not actually work.
I made a change to a file on the mainframe in USS and I had a copy prior to the edit on Zowe. I made a change and saved it and it was updated on the mainframe successfully. But we would expect that a merge conflict error would be thrown.
```
For this, we found the code have a bug when return the etag. It returns a wrong type etag. See picture below,
图片
After corrected, now it can work well.

```
2.The current implementation for putContents is deprecated. I have changed the code to use putContent. It works without any issues.
```
Yes, we noticed this and will using the new next  time.

```
3.Clicking on an already opened member in USS does not perform the same way as Datasets.
When I click on a member in USS it performs a pull from mainframe. However, in Datasets this only occurs iff the file has not been opened.
```
For the third, we can't recreate the situation. May need more details on this.

```
There is a mismatch between the etag generated when a file was pulled from the mainframe vs. the etag generated (via AppData/temp) when the user is trying to save a file to the mainframe.
```
For the etag mismatch, the known issue is CR/CRLF different between local vscode file and mainframe. Could you help confirm if your issue is in the same situation? Thank you very much!

Thank you again @std4lqi and @mmoore96 to help debug, analysis and test. ❤️

**Comment by mmoore96** [comment]
@tiantn 
Thank you for this explanation. I have been working on further testing. The fix you described does not stop the erroneous save conflict from being thrown. 
I have logged the etags during my testing. I am working on a fox that will use the AppData directory to store off etag after a user saves to the Mainframe. I will provide more details hopefully tomorrow.

**Comment by mmoore96** [comment]
@tiantn @std4lqi 
## Problems:
1. When clicking on a USS member after it is already opened, it does not perform a "Pull from mainframe" like it does on Datasets.

I logged variables and etags below for testing

When clicking on a file in uss after it has all ready been opened gets you the following log:
```Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
```
Right clicking on the file and selecting "Pull from mainframe" get you this following log:

```
ERROR message from extension Zowe Explorer FTP Extension: We are at getContents
Downloading USS file '/u/[User#]/javatest/EXPGM5.java' to local file 'c:\[Users]\[user#]\.vscode\extensions\zowe.vscode-extension-for-zowe-2.0.2-SNAPSHOT\resources\temp\_U_\zftp_GMM\u\[User#]\javatest\EXPGM5.java' in transfer mode 'ascii
Successfully downloaded 3413 bytes of content from /u/[User#]/javatest/EXPGM5.java
ERROR message from extension Zowe Explorer FTP Extension: We are at hashFile
ERROR message from extension Zowe Explorer FTP Extension: We downloaded the file. The etag from hashFile is: da39a3ee5e6b4b0d3255bfef95601890afd80709
```

When saving a file in USS to the mainframe you get the following log:
```
Message from extension Zowe Explorer FTP Extension: We are at putContents
Message from extension Zowe Explorer FTP Extension: Save with FTP: Loading the file first
Message from extension Zowe Explorer FTP Extension: We are at getContents
Downloading USS file '/u/[User#]/javatest/EXPGM5.java' to local file 'C:\[Users]\[user#]\AppData\Local\Temp\tmp-25836-jk0P1Wo4z4PA' in transfer mode 'ascii
Successfully downloaded 3413 bytes of content from /u/[User#]/javatest/EXPGM5.java
Message from extension Zowe Explorer FTP Extension: We are at hashFile
Message from extension Zowe Explorer FTP Extension: We downloaded the file. The etag from hashFile is: 64df5d9cda0fff998c3d469a48525e9472c7ed0e
Message from extension Zowe Explorer FTP Extension: We are at getContentsTag. etag is: 64df5d9cda0fff998c3d469a48525e9472c7ed0e
Message from extension Zowe Explorer FTP Extension: contentsTag: 64df5d9cda0fff998c3d469a48525e9472c7ed0e
Message from extension Zowe Explorer FTP Extension: etag: da39a3ee5e6b4b0d3255bfef95601890afd80709
Message from extension Zowe Explorer FTP Extension: Save conflict. Please pull the latest content from mainframe first.

```

Not sure if this is exspected. In datasets if I click on the same member I have open, it will pull it from the mainframe again. 


## Issue with Etag:
As you can also see from the above log, there is a discrepancy between the etag that is generated from the getContents method and the putContents. I belive this is what you are referring to about LF vs CRLF. In USS there is no extra line added to the file, however with windows there is. 

However, there is an issue with that reasoning. When the files is downloaded the either vscode directory or AppData directory it is not going to matter because in both cases there is a Carriage return at the end of the file. zFTP handles these conversions.
In addition, if this was the problem then we would get a save conflict error every time we tried to save. 


## The problem:
The issue is that the behavior of clicking on uss files (after it has been opened) runs the following:
 ```Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
Listing USS files in the directory '/u/[User#]/javatest'
Found 28 matching files
```
So in certain cases of switching from different files and saving them, there becomes a mismatch of etags. 

I have also seen that you can save a file without any etag checking being done:
```
Attempting to upload from local file 'c:\[Users]\p079584\mainframeFiles\temp\_U_\zftp_GMM\u\[user#]\javatest\Test.java' to USS file '/u/[user#]/javatest/Test.java' in transfer mode 'ascii'
Adding carriage returns to string of length 7478
ERROR message from extension Zowe Explorer FTP Extension: We are at putContents
Attempting to upload from local file 'c:\[Users]\p079584\mainframeFiles\temp\_U_\zftp_GMM\u\[user#]\javatest\Test.java' to USS file '/u/[user#]/javatest/Test.java' in transfer mode 'ascii'
Adding carriage returns to string of length 7477
ERROR message from extension Zowe Explorer FTP Extension: We are at putContents
Attempting to upload from local file 'c:\[Users]\p079584\mainframeFiles\temp\_U_\zftp_GMM\u\[user#]\javatest\Test.java' to USS file '/u/[user#]/javatest/Test.java' in transfer mode 'ascii'
Adding carriage returns to string of length 7477
ERROR message from extension Zowe Explorer FTP Extension: We are at putContents
Attempting to upload from local file 'c:\[Users]\p079584\mainframeFiles\temp\_U_\zftp_GMM\u\[user#]\javatest\Test.java' to USS file '/u/[user#]/javatest/Test.java' in transfer mode 'ascii'
Adding carriage returns to string of length 7478 
 ```

I also sometimes get stuck user messages when navigating USS:
stuckZowe

 ## The solution:

 The clicking behavior should been the same between datasets and USS. I believe this would fix the etag mismatches. 

Even the UI performs different with Datasets vs USS:

When a pull from mainframe is done on Datasets:
testzowedatasets

When a pull from mainframe is done on USS:
testzoweuss

When you first open USS and click on a member it does not do the above.
Only when you, right click and select "Pull from mainframe" does it change the file icon.

**Pull request merged**
