### PR TITLE
GIFs in docs/images updated on readme file

### PR DESCRIPTION
**Pull request by Pranay154**
Resolves #281

### CODE REVIEW

**Comment by Colin-Stone** [comment]
This is great stuff. A couple of observations..
1. Are we missing a gif for: `Integrated function
Dynamic gif showing JCL being submitted from Datasets view. Popup showing Job submitted link, click on link and see job spool output in Jobs view` ?
2. Sorry to be a pain but is it possible to start each example with a sentence about what you are about to describe?. For example
`Issue TSO Command`
You can issue TSO commands such as Allocate or Exec against a profile.
`1. Press Cmnd+Shift+P together`
3. `Press Cmnd+Shift+P together` Use Cmd
4. Maybe put Issue TSO command in it' own section called "Extras"
5. Can we have an image for Show Data Set Attributes that includes the left hand explorer side  please. Maybe even a dynamic gif

**Comment by IgorCATech** [comment]
Hello guys, 

I've just got to know that you opened this PR to update the README doc. I'm working on the Zowe Explorer doc, too. One for Zowe docs and one for VSCode Marketplace. The latter pretty much copies the README file. Given this, can I use the gifs that you created to replace the outdated ones?

**Comment by Pranay154** [comment]
Hey @IgorCATech, yes you are more than welcome to go ahead and use the GIFs!

**Comment by Colin-Stone** [comment]
Fixed up the linter issues. 

1. I think we are missing gifs for the Jobs favorites.
2. Although Imsaid we didn't need a dynamic gif for delete job I think we should have a static one that simply shows hovering over the bin.

**Comment by Pranay154** [comment]
Hey @Colin-Stone, thanks for bringing this to my attention, I will get this done right away

**Comment by Pranay154** [comment]
Opened new PR #294 due to commit issues

**Pull request closed without merging**
