### PR TITLE
FTP and API Readme updates

### PR DESCRIPTION
**Pull request by phaumer**
## Proposed changes

We did not have any incorrect READMEs for the FTP Extension and the NPM package although we were publishing these to repos such as npmjs.org and the marketplace.

## Release Notes

Milestone:

1.12

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [X] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [X] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [X] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [X] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [X] I have tested it manually and there are no regressions found
- [X] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

This is a low risk merge for 1.12 as there are no code changes. Only minor updates to package.json description and tags.

### CODE REVIEW

**Comment by phaumer** [comment]
@zFernand0 @lauren-li these are just changes to the Readme. I propose to include these for 1.12 to provide correct/better docs in the public repos we publish this to.

**Review by lauren-li — COMMENTED** [review]
Overall, I think this looks really good! I made PR #1156 against this branch with copyedit suggestions (most of them are minor punctuation/wording/formatting suggestions).

One thing I'm not sure I agree on for the Zowe Explorer FTP extension's readme is including steps to install and create a profile using the FTP plug-in for Zowe CLI. The steps are accurate, but as you mentioned in the readme, they are not necessary for getting started with the Zowe Explorer FTP extension, and I feel it makes the setup process seem more daunting and complicated than it really is, especially for a user who is new to Zowe.
- Could we instead just link users to the CLI plug-in's own installation instructions [here](https://github.com/zowe/zowe-cli-ftp-plugin#install-the-zos-ftp-plug-in) if they are interested, and stick to describing install/profile creation for the Zowe Explorer FTP extension itself in our own documentation?
- I included copyedits for this section in PR #1156 in case we want to keep it.

We may want to also have @IgorCATech take a look at this PR, since he is our docs expert, and may be able to help us standardize the language and formatting to match other Zowe documentation.

Thanks @phaumer for these much-needed readme updates!

**Comment by phaumer** [comment]
@lauren-li I merged your changes, moved the cli piece, and added a new icon. Ready to merge?

**Review by lauren-li — APPROVED** [review]
@phaumer I think this looks good to go in now! I added a few very minor copyedits to polish the PR. Thanks again for these documentation updates!

**Review by zFernand0 — APPROVED** [review]
LGTM!!

**Pull request merged**
