### PR TITLE
reuse listconnection

### PR DESCRIPTION
**Pull request by tiantn**
Signed-off-by: Tina <tiantn@cn.ibm.com>

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Comment by tiantn** [comment]
Listing files/datasets is a frequent action in ftp extension. So reuse the list ftp connection can avoid wasting time on setting up new connections to improve user experience.

**Review by std4lqi — APPROVED** [review]
It looks good to me. It should be able to improve responsiveness by reusing connection. Thanks, @tiantn !

**Comment by tiantn** [comment]
Hi @JillieBeanSim, @zFernand0, this PR is for task: Re-use of FTP sessions in #1196 . Could you help to review? Thank you!

**Comment by zFernand0** [comment]
Hey @tiantn, 
I believe the user reported that the problem was gone ? (https://github.com/zowe/vscode-extension-for-zowe/issues/1196#issuecomment-888453904) 
It sounds like [Release v1.16.0](https://github.com/zowe/vscode-extension-for-zowe/releases/tag/v1.16.0) fixed the original issue which was related to the many sessions (Started Task Control - STC) given that we terminated (called `releaseConnections`) after every call.

I'm guessing this PR intends to keep the STC alive while the extension is active.

My concern is with the "while the extension is active". The `extension.deactivate` method is called when:
- The extension is disabled, 
- The extension is uninstalled,
- VSCode is "shutting down". This is not the same as a PC shutdown/restart based on this issue:
  - https://github.com/microsoft/vscode/issues/70665
  
That being said, I'm curious if this could lead to the same problem as it was initially reported.
I haven't fully tested the PR to determine if that may be the case, but it sounds like there will be a new STC for each profile.
And if VSCode does not retain the `sessionMap` after a PC restart, the it will lead to more and more STCs.
This is just a theory though. 😋

**Comment by tiantn** [comment]
Hi @zFernand0, thank you for the comments.

Yes, the user reported problem was gone. We used a simple way (release connection after each call) to solve the problem. But for the frequent operations like list uss files/ datasets, setup the connection each time will increase the time effort. So we consider reuse the list connections.

In this PR, we don't release the list connection after each list call until the extension deactivate. So the STC at least increase 1 and at most increase 3 than before. (for mvs, uss, jes list). The STCs will disappear when extension deactivated or the timeout value reached. Though the STC number will increase, but at most 3, not a lot of STCs. While reusing the connections will improve the list response performance. So we think it is valuable.

I tested the following situations which STC will disappear.
- close VScode
- restart PC(we can consider any ftp disconnect)
- timeout value reached

And following situations will not release the STC.
- disable extension
- uninstall extension
If the list connections setup, then disable or uninstall extension, the STC won't release. But we can close VScode and restart it to release them. Or wait until timeout.

Thank you!

**Review by zFernand0 — APPROVED** [review]

**Pull request merged**
