### PR TITLE
Refactor Zowe 2.0 settings migration script

### PR DESCRIPTION
**Pull request by rudyflores**
## Release Notes

Milestone: v2.0 

Changelog: Fixed an issue where `zowe.settings.version` is added to workspace settings when no settings have been migrated.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by phaumer — DISMISSED** [review]
Thanks @rudyflores. This works great now. 

Perhaps another PR could be to warn the user at consequent startups that they still have old v1 settings that had been migrated in their settings that should be removed to avoid potential confusion. 

Minor comment about the code: you are exporting functions such as `standardizeGlobalSettings()` that are only called locally. The code reads more like javascript with global constants and functions that do not declare their return type etc. I would have created a static utility class as they help with encapsulation and I find those are also easier to read from the caller side.

**Review by zFernand0 — APPROVED** [review]
Thanks for fixing!

**Comment by rudyflores** [comment]
> 

Interesting, i'd like to make these changes before this can be merged if possible then :)

**Review by zFernand0 — APPROVED** [review]
😍 
Thanks for updating it!
I know it can feel like typing a lot more, but it's nice to be able to access it as a static method from the imported class. 😋

**Review by JillieBeanSim — APPROVED** [review]
LGTM! thanks @rudyflores for the updates to the settings migration

**Comment by phaumer** [comment]
Awesome. Thanks for making the updates @rudyflores

**Pull request merged**
