### PR TITLE
Provide profiles cache to extenders

### PR DESCRIPTION
**Pull request by phaumer**
Signed-off-by: Peter Haumer <4391934+phaumer@users.noreply.github.com>

## Proposed changes

First implementation for https://github.com/zowe/vscode-extension-for-zowe/issues/1281. Builds on PR https://github.com/zowe/vscode-extension-for-zowe/pull/1290.

See [packages/zowe-explorer-ftp-extension/src/extension.ts](packages/zowe-explorer-ftp-extension/src/extension.ts) for example for how to use it.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by phaumer** [comment]
If there is no other feedback the this one is ready to be merged. 
@AndrewTwydell were you able to try it?

**Review by lauren-li — COMMENTED** [review]
This looks good to me so far! The sample code with the Zowe Explorer FTP extension is working well in manual testing, and all unit tests are passing. (My integration tests are still acting up even on `master` branch, so Billie will have to help me out with those.)

As mentioned in the code comments, the sample code in the FTP extension should be removed before merging. I am also curious what @AndrewTwydell's experience was using the changes/documentation in this PR with the Zowe Explorer CICS extension. From my discussion with him earlier, it seems he had a positive experience, but Andrew feel free to comment and keep me honest! :smile:

Thanks @phaumer for making Zowe Explorer's profilesCache available to extenders!

**Comment by phaumer** [comment]
@lauren-li thanks for reminding me. I removed the sample code now.

**Comment by AndrewTwydell** [comment]
Getting the following error when using a local copy of the zowe-explorer-api dependency in the following format:
```
"@zowe/zowe-explorer-api": "/Users/...../vscode-extension-for-zowe/dist/zowe-zowe-explorer-api-1.17.0.tgz",
```

Screenshot 2021-07-28 at 16 32 56

FYI - @phaumer @lauren-li

**Comment by phaumer** [comment]
@AndrewTwydell this might not be the reason, but when you create a local build to load as a file I would update the version number to make sure your version actually replaces actually the published version in your node_modules.

**Comment by phaumer** [comment]
@AndrewTwydell I think I found the issue and added a commit. Can you try again?

**Comment by AndrewTwydell** [comment]
@phaumer I'm no longer getting the error, all good now 😄 Thanks for all your work on this, it really makes extending with the CICS Explorer so much easier!

**Review by AndrewTwydell — APPROVED** [review]
LGTM! 

Really appreciate this work - it's made profile access so much easier, so thank you!

Final question... We discussed adding the functionality to tell the profile cache to load other profile types (CICS in our case). I assume this will be done at a later date and not included in this PR?

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! Thanks for your work on this @phaumer.  All expected tests and checks are also passing =)

**Review by JillieBeanSim — APPROVED** [review]

**Review by lauren-li — APPROVED** [review]
This looks good to me now! I added some minor edits to the docs/code sample (it was missing a `}`), but the functionality is still working well, and all unit and expected integration tests are still passing.

Thanks @phaumer for the fix, and thanks @AndrewTwydell for testing this out with the CICS extension!

**Pull request merged**
