### PR TITLE
[Issue #1560] Fix input cancelling messaging

### LINKED ISSUE #1560: TSO error message doesnt appear
If escape when prompted for a command `operation cancelled` info message doesn't pop up...[possible solution here](https://github.com/zowe/vscode-extension-for-zowe/pull/1479#issuecomment-919110641)

### PR DESCRIPTION
**Pull request by roman-kupriyanov**
## Proposed changes

This one fixes #1560. 
_(The issue itself is opened for TSO command execution feature initially, but this bugfix affects a helper function, which is used in many places, and as a result it also fixes the cancelling cases for other commands (e.g. Issue MVS command, filter selections and etc.)_

Added an `onDidHide` handler for `resolveQuickPickHelper`, which always return `undefined` result. 

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

The API doc says:
> There are several reasons why this UI might have to be hidden and the extension will be notified through QuickInput.onDidHide. (Examples include: an explicit call to QuickInput.hide, the user pressing Esc, some other input UI opening, etc.)

This means the informational message will be shown in the cases above, including if some other input will appear in the middle of TSO command issuing.

Also, a current implementation already contains `No selection made.` message, which appears when a choice from the picker is falsy (`undefined` in a case of cancelling through `Esc`). The issue however specifies that `Operation cancelled.` is expected.
Should the message be changed or even, should the cancelling event itself be distinguished from others somehow to show operation cancelled message exactly in this case?

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
@roman-kupriyanov I think just changing the info message to `Operation cancelled` or extending the existing one to `No selection made. Operation cancelled.` in the TsoCommandHandler.ts line 211 would suffice for the issue to be closed.  Pressing escape on this instance does cancel the operation so we are good on that. Thanks for working on this.

**Comment by roman-kupriyanov** [comment]
Hey @JillieBeanSim, thanks a lot for looking at this 😊 

> just changing the info message to `Operation cancelled` or extending the existing one to `No selection made. Operation cancelled.` in the TsoCommandHandler.ts line 211 would suffice for the issue to be closed.

What about other cases, when the `resolveQuickPickHelper` is used? I suppose, changing that commonly used helper function is fixing not only the TSO issue command, but other calls too, where `No selection made.` was not shown as well. For example:

- _MvsCommandHandler.ts_: a similar message is used:
  https://github.com/zowe/vscode-extension-for-zowe/blob/f215d6dc1d79f57abda110007a4f9e9e5cc1a0df/packages/zowe-explorer/src/command/MvsCommandHandler.ts#L207
- _DatasetTree.ts_: same message for filter selection:
  https://github.com/zowe/vscode-extension-for-zowe/blob/f215d6dc1d79f57abda110007a4f9e9e5cc1a0df/packages/zowe-explorer/src/dataset/DatasetTree.ts#L914
- And many more.. There is actually an entire list of them:
  
  image

Should I change the message for them too? Or maybe to create another issue to cover all other commands similarly, but in another PR?

**Comment by JillieBeanSim** [comment]
@roman-kupriyanov I would create a new issue and capture what you have in the comment here so it can be looked at and see what is being presented to the user and what we want presented to the user in each case.  What do you think of that idea?

**Comment by roman-kupriyanov** [comment]
> I would create a new issue and capture what you have in the comment here so it can be looked at and see what is being presented to the user and what we want presented to the user in each case. What do you think of that idea?

@JillieBeanSim sounds good to me as well. I will open a new one, thanks 😉

**Review by JillieBeanSim — APPROVED** [review]
LGTM @roman-kupriyanov! thanks for working on this and creating the follow up issue.  If you wouldn't mind, could you add a link in this PR for that once it's created? Thanks.

**Review by rudyflores — APPROVED** [review]
LGTM! I have tested issuing a TSO command and escaping in order to view to cancellation message pop-up. The unit/integration tests seem to all be passing as well! Thanks for your work on this @roman-kupriyanov !

**Comment by JillieBeanSim** [comment]
@roman-kupriyanov you are good to go to create the follow up PR to bring this into the `next` branch now :slightly_smiling_face:

**Pull request merged**
