### PR TITLE
Issue #968c: Group USS favorites by profile and allow extenders to activate before loading profiles

### PR DESCRIPTION
**Pull request by lauren-li**
## Proposed changes

Addresses the following issues for the USS tree:
#968 (Favorites created by other extensions should not throw errors as the other extensions are not activated yet)
#168 (Group Favorites section based on profile)

See PR #984 (the equivalent for Data Sets) for a more detailed description of how this works.

Gif of GUI changes:
Zowe Explorer load-favs-by-profile-uss2

## Release Notes

Milestone: 1.9

Changelog:  Group USS favorites by profile, and load/set favorites’ profiles only when the user clicks to expand the relevant profile grouping node in the Favorites section.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [x] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [x] There is coverage for the code that I have added
- [x] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

**Pre-existing issues related to USS/USS favorites:**
- Favorited searches in DS, USS, and Jobs start out with a magnifying glass icon. After clicking on the favorited search, the icon changes to a folder icon with a validation circle. The user can then add a duplicate entry of that search to favorites settings.json and UI.
- USS profile does not validate if you just click on a profile (session) name that doesn't have a search associated with it. But it does validate if you click on a profile name that does have a search associated with it.
- When the user Cancels out of USS Upload dialog, the following error appears: “Error running command zowe.uss.uploadDialog: Cannot read property 'map' of undefined. This is likely caused by the extension that contributes zowe.uss.uploadDialog.”

USS delete/rename pre-existing bugs in master branch:
- Deleting a file/folder from regular session node does not remove it from Favorites. On master branch, it deletes from the Favorites in the tree view UI, but not from the Favorites in settings. Thus, deleted files/folders will show up in Favorites when the user next restarts VS Code session.
- Renaming file/folder from regular session node does not rename it in Favorites (master branch). - Potentially addressed by Zowe Explorer PR #961, although updates would be required after it is merged for the new Favorites hierarchy.
- Renaming files/folders in USS Favorites does not appear to work. 404 errors are returned (i.e. "No such file or directory.")
- (Not a bug, but just for completeness: you cannot delete a file/folder from USS favorites.)

### CODE REVIEW

**Comment by lauren-li** [comment]
Thanks @JillieBeanSim for looking over this PR! I have finished adding new unit tests for it, and it is ready for another review.

~
> Wanted to mention one thing that I also mentioned in the Data Sets PR about adding a profile name to favorites by right clicking before a search is done and an empty space being saved in the favorites.

This is pre-existing behavior in the master branch, but I agree it's not the best UX. I have created issue #1002 so that we can address it in a future PR.

**Comment by lauren-li** [comment]
**Note for reviewers:** If there are no more changes/issues with the USS portion of PR #961 by the end of today, I plan to go ahead and start merging it into this PR (#997) to preemptively address updates that will need to be made to USS Favorites renaming for the 1.9.0 release.

**Comment by lauren-li** [comment]
If PR #961 will get merged into the master branch with no significant changes to the USS portion, then this PR can be closed and PR #1006 should be reviewed instead.
- PR #1006 consists of this PR (#997) with PR #961 merged in and updates made to USS renaming for favorites grouped by profile.

**Review by katelynienaber — CHANGES_REQUESTED** [review]
Hey! Seems to be okay for the most part. 2 comments (which I thinkkk are covered in my PRs but I will write them all the same):

- When a folder is renamed from favorites, the session in the tree collapses and doesn't reopen:
comment1
- When a folder is renamed from not-favorites, the favorite is not renamed, and then you can't work with it:
comment2

And 1 thing which is not covered in my PRs:
- When I make a new file/folder inside a closed folder, would it be possible to expand the tree to the new file/folder? ie. expand the parent folder and select the new file/folder, using vscode's reveal function?

**Comment by lauren-li** [comment]
Thanks @katelynienaber for reviewing this PR! You are correct, the first two points you mentioned should be covered by your PR #961. You can check out PR #1006 to test the functionality from this PR combined with the fixes from your PR #961. (In fact, I did not touch USS renaming prior to PR #1006 because I knew you were working on improving it.)

For your last point, I think adding functionality to expand the USS tree to a newly-created file/folder is outside the scope of what this PR is meant to address, as I also do not see this behavior in the current master branch. (Let me know if you are experiencing differently.) However, this would be a great UX improvement to address in a future issue/PR.

**Comment by jellypuno** [comment]
Looks great! Thank you @JillieBeanSim ! I found minor issues but it is not really big deal because the validation is still happening.
I am approving this PR. We can just keep these issues in mind for future re-factoring.

Minor Issue:
- When you Enable Validation and click the PDS the validation is triggered but the folder is not updated.
- When I click Disable Validation and right click again the text is not updated to Enable unless I do something.
- The Greater Than sign next to the profile is not triggering validation. But this is okay because I do want flipstate() to contain the validation because it is called everywhere. It will have more errors.

valid8errz

**Comment by lauren-li** [comment]
Closing this PR in favor of PR #1006 (PR #997 with PR #961: Group USS favorites by profile and Fix USS rename).

**Pull request closed without merging**
