### PR TITLE
Fix error messages being duplicated in errorHandling calls

### PR DESCRIPTION
**Pull request by t1m0thyj**
## Proposed changes

This PR fixes our use of the `errorHandling` method to eliminate duplicate error messages that were observed when showing error cases in the Zowe system demo.

TODO:
* [x] Investigate confusing error message for #2095
* [x] Increase patch coverage

## Release Notes

Milestone: 2.8.0

Changelog: Fixed redundant text in error messages that included the same error details twice.

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

### CODE REVIEW

**Review by JillieBeanSim — DISMISSED** [review]
LGTM! thanks @t1m0thyj

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
Thanks for also removing some extra spacing in some of the strings/messages 😋

**Comment by t1m0thyj** [comment]
> Investigate confusing error message for https://github.com/zowe/vscode-extension-for-zowe/issues/2095

The error message for profiles that fail validation comes from Imperative so we don't have control over it in ZE. And unfortunately VS Code strips newlines out of multiline error messages which makes them hard to read. For now the best solution I could think of is to replace newlines with a vertical bar character. Let me know if there are any objections to this change and I can revert it.
image

**Review by traeok — DISMISSED** [review]
LGTM!

**Review by traeok — APPROVED** [review]

**Review by zFernand0 — APPROVED** [review]
thanks for simplifying the errorHandling logic
LGTM! 😋

**Pull request merged**
