### PR TITLE
Fix: Change RU to fix the spike

### PR DESCRIPTION
**Pull request by jellypuno**
Signed-off-by: Jessielaine Punongbayan <jessielaine.punongbayan@broadcom.com>

## Proposed changes

This PR will fix spike #1094. As per investigation, ZE is passing ru=true because of how it is coded in the API. I changed it  and now it is fixed 😄 

Capture

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [x] gif or screenshot is included if visual changes are made
- [x] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JillieBeanSim — APPROVED** [review]
@jellypuno this works great! all tests and checks are passing as well. Thank you so much for this important fix @jellypuno 

@zFernand0 if we could get this into this weeks release that would be awesome! I tagged @lauren-li to test this as well since she was also running into the issue.

**Comment by zFernand0** [comment]
No objections here!
Glad this was a "simple" fix! 😋

**Review by zFernand0 — APPROVED** [review]

**Comment by zFernand0** [comment]
With this PR, I believe we enter code-freeze, is that right?

**Comment by lauren-li** [comment]
>With this PR, I believe we enter code-freeze, is that right?

@zFernand0 I believe so. I see this PR just got merged in, but I will still test on my end anyway to see if the issue is fixed for me. :)

**Comment by JillieBeanSim** [comment]
> With this PR, I believe we enter code-freeze, is that right?

Don't know if we were waiting on 1100 as well was about to test it.  the zFTP issue we spoke of wasn't dealing with what we thought and Jelly was going to investigate further.  I do have a branch with zFTP making use of merging with base in case base stored user/pass for profiles but it's not important for this release could go in next

**Comment by jellypuno** [comment]
@JillieBeanSim #1100 is not going in to the next release. Those are cosmetic fix. But I think #1097 should go in? I'm not sure.

**Comment by zFernand0** [comment]
🤦‍♂️ you are right, I recall parts of that conversation.
and Katelyn had already approved it! 😋

**Comment by lauren-li** [comment]
I tested `master` branch with the changes from this PR, and now the apiml log in/log out in Zowe Explorer works great for me! Also, all unit and expected integration tests are passing. Thanks @jellypuno for figuring this out and fixing it!

**Pull request merged**
