### PR TITLE
[next] Add support for project level config

### PR DESCRIPTION
**Pull request by crawr**
Signed-off-by: Richelle Anne Craw <richelleanne.craw@broadcom.com>

## Proposed changes

This PR adds the checking of project level context for `zowe.config.json`

## Release Notes

Milestone: N/A

Changelog: Support project level config

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

Compatible with CLI version 7.0.0-next.202106012053

### CODE REVIEW

**Comment by JillieBeanSim** [comment]
This PR needs the audit fixes, they can be brought in from `next` after the refactor PR https://github.com/zowe/vscode-extension-for-zowe/pull/1429 is merged

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
@crawr this works well for picking up zosmf profiles from team config, but didn't show my zftp in team config available with the ftp extension from this branch installed, I didn't even get the popup `Zowe Explorer was modified for FTP support.` .  Also, when creating/editing it opens the global config instead of team config.

**Review by jellypuno — DISMISSED** [review]

**Comment by JillieBeanSim** [comment]
@crawr did we loose something with the merges?  I only see changes in the ZE package.json & yarn.lock.  I created a project level config file and it is not recognized anymore at the project level

**Comment by crawr** [comment]
Looks like I messed this up when merging and my changes were gone. :( I will be updating this from a recent commit.

**Comment by JillieBeanSim** [comment]
@crawr this works great funcionally! the correct config file shows up when loading ZE and with update/create/& delete whether it's team or global needed.  I do get 5 failing unit tests that deal with the import `import { trueCasePathSync } from "true-case-path";` with a TypeError
` TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined` 
not sure if this is what you see as well running unit tests

**Comment by jellypuno** [comment]
> @crawr this works great funcionally! the correct config file shows up when loading ZE and with update/create/& delete whether it's team or global needed. I do get 5 failing unit tests that deal with the import `import { trueCasePathSync } from "true-case-path";` with a TypeError
> ` TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined`
> not sure if this is what you see as well running unit tests
> 
> I didn't see these failures until moving the import into the ProfilesUtils.ts for the function I created in an earlier PR getProfileInfo

This error is super weird. It's okay if the import is done in extension.ts 😕

**Review by jellypuno — APPROVED** [review]

**Review by JillieBeanSim — APPROVED** [review]
Approving since functionality works, I can pull into my PR branch and see about fixing the tests or removing the call from extenders file so we can move the code back into extension.ts so build will work

**Pull request merged**
