### PR TITLE
fix: limit API requests to codecov and npm audit

### PR DESCRIPTION
**Pull request by dkelosky**
Signed-off-by: Dan Kelosky <dkelosky@gmail.com>

## Proposed changes

This reduces the amount of times codecov and `npm audit` are done to avoid using the backend APIs and having requests be rejected.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] `npm run vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by zFernand0** [comment]
@VitGottwald, any thoughts?

**Comment by dkelosky** [comment]
I added other reviewers - I think @VitGottwald is out for a bit.

**Comment by jellypuno** [comment]
@zFernand0 @dkelosky Curious, why are we not testing on Node v8? Are we not supporting it anymore?

**Comment by zFernand0** [comment]
> @zFernand0 @dkelosky Curious, why are we not testing on Node v8? Are we not supporting it anymore?

I'm more than happy to include it back. I guess we dropped it since NodeJS officially dropped support for it?

**Comment by jellypuno** [comment]
> > @zFernand0 @dkelosky Curious, why are we not testing on Node v8? Are we not supporting it anymore?
> 
> I'm more than happy to include it back. I guess we dropped it since NodeJS officially dropped support for it?

We don't have to. I just wanted to know why.

**Comment by dkelosky** [comment]
hi @jellypuno - i was looking at Node releases according to this: https://nodejs.org/en/about/releases/

Since I didn't see Node 8 there, I dropped it. Do you think that is acceptable?

**Comment by dkelosky** [comment]
Side note, even though Jenkins Theia test appears to show as passing, this test is failing in both places:
image

**Comment by dkelosky** [comment]
It looks like building with `vsix` with the webpack `--production` flag does not keep `__tests__` in the `out` folder.  I updated github actions workflow to rebuild tests for mocha after creating the `vsix`.  I did not update the jenkins pipeline (which fails but reports success).

**Comment by dkelosky** [comment]
The only failing test is `codecov/project` - but I haven't changed any source files.

**Comment by zFernand0** [comment]
Thanks for fixing!

**Comment by dkelosky** [comment]
Hey @jellypuno - Did you have a chance to look at the latest updates to your question?

**Comment by zFernand0** [comment]
@VitGottwald, any thoughts about the limitations?
Also @dkelosky, Have you considered @tjohnsonBCM suggestions of splitting the Audit to its own check?

**Comment by dkelosky** [comment]
I can pull that as a separate workflow. My question in the other repos were how the cron job approach would impact urgency. 

If we have lint as part of the PR workflow it would halt merging of features until audit issues are fixed.  

I’m pretty indifferent on what’s best, just sharing a consideration. 

Theia pipelines are failing in the meantime on Jenkins. Perhaps after this is merged, we can make the Theia workflow required.

**Comment by zFernand0** [comment]
Could the status-check (stage?) name be changed to indicate that it is in fact the theia build?
`Theia Zowe Explorer CI / build` -> `Theia Zowe Explorer CI / theia-build`
i.e. 
```yaml
jobs:
  theia-build:
    ...
```

Made it a requirement for now.
May need to revisit this if the name changes (and messes up with the requirement)

**Pull request merged**
