### PR TITLE
Display message in status bar

### PR DESCRIPTION
**Pull request by anokhikastiaIBM**
Signed-off-by: Anokhi Kastia <90722760+anokhikastiaIBM@users.noreply.github.com>

## Proposed changes
[#213] Display messages in status bar

Description of the Issue: When editing a dataset in VS Code, a notification appears every time it saves that says "Dataset uploaded successfully." The frequency of these notifications seems undesirable when making a lot of edits, as they keep on popping up.

The status bar should be at the bottom of the screen instead. This would make the info less distracting, while still visible for users who want to see it.

Changes: The only change that I made was to the file action.ts on line 1358. When a file is changed, the function saveFile is called when the text document is being saved. A message "DataSet uploaded successfully" (uploadResponse.commandResponse) shows up. I changed to setStatusBarMessage.

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [ ] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [ ] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [ ] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [ ] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [ ] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by lauren-li** [comment]
Waiting on discussion follow-up in issue #213.

**Comment by JillieBeanSim** [comment]
@anokhikastiaIBM I removed the `onHold` tag after the discussion.  Would you let us know here when the PR is ready for review?

**Comment by JillieBeanSim** [comment]
Issue to address other notification items after the `save` issue is addressed https://github.com/zowe/vscode-extension-for-zowe/issues/1517

**Comment by jellypuno** [comment]
@anokhikastiaIBM Thanks for adding this. So I tried it out. The message in the status bar is kind of misleading. I edited a Data set member and saved it. The message in the status bar says "Data set uploaded successfully". I was expecting that this message would appear during upload member rather than saving the file.

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim I see. ok. Do you think that we can implement this in Get Dataset List or Opening Dataset? Those Info message that pops up all the time?

@jellypuno yes we have documented wanting to do that here https://github.com/zowe/vscode-extension-for-zowe/issues/1517

**Comment by JillieBeanSim** [comment]
@anokhikastiaIBM I didn't realize this PR was going to cover the other issue, just the save issue that it's linked to

**Comment by anokhikastiaIBM** [comment]
@JillieBeanSim Now it only covers the save issue that it is linked to, and not the other ones.

**Comment by anokhikastiaIBM** [comment]
@JillieBeanSim I signed off the commit. It is ready for review & merged!

**Comment by anokhikastiaIBM** [comment]
@JillieBeanSim It is still failing even though I signed it off.

**Comment by lauren-li** [comment]
> Thanks for noticing that @jellypuno, it looks like this line will be needed to be added above any line with the timeout `// tslint:disable-next-line:no-magic-numbers`

Perhaps we want to assign the 5000 ms to a constant (e.g. `STATUS_BAR_TIMEOUT`) in the [`globals.ts`](https://github.com/zowe/vscode-extension-for-zowe/blob/master/packages/zowe-explorer/src/globals.ts) file where the other constants are.

**Pull request closed without merging**
