### PR TITLE
Ph fix 514 spawn

### LINKED ISSUE #514: Zowe 1.2.1 does not activate when ~/.zowe directory is not present
In Zowe Explorer v1.1.0 we had a ProfileLoader class that would actually spawn a node process to run the imperative main from node_modules to basically run Zowe CLI to create the .zowe directory in the user’s home directory and if already present read the profiles already available.  This was useful for users who do not have Zowe CLI installed as they could just use Zowe Explorer without installing the CLI. 

I see that this code got removed in this PR https://github.com/zowe/vscode-extension-for-zowe/pull/400. So now when I install Zowe Explorer without having a ~/.zowe directory activation of Zowe Explorer even fails. The only workaround it seems is installing Zowe CLI and calling any command.

image

### PR DESCRIPTION
**Pull request by zFernand0**
fixes #514

### CODE REVIEW

**Comment by zFernand0** [comment]
Replaying build because of #489 again

**Comment by zFernand0** [comment]
Personally, I'm not concerned about Codecov failing here since this may be just a temporary fix.

**Comment by zFernand0** [comment]
> This looks fine. Are we treating as a temporary fix?. Replacing with Tim's more comprehensive solution?

That's correct. We want to fix this as soon as we possibly can, in case new users download the extension over the weekend and they don't have the CLI 😄

**Comment by tjohnsonBCM** [comment]
Tested this branch without a `~/.zowe` folder present and got an error, although Zowe Explorer seemed to work fine afterwards.
image

**Comment by zFernand0** [comment]
We believe that the worst case scenario is that people may not be able to store secure profiles over the weekend (until the next version - 1.3) comes out on Tuesday

**Pull request merged**
