### PR TITLE
[next] Refactor for SDK compatibility

### PR DESCRIPTION
**Pull request by crawr**
Signed-off-by: Richelle Anne Craw <richelleanne.craw@broadcom.com>

## Proposed changes

This will update the Zowe Explorer dependency to get the most recent @next version of the SDK. Deprecated functions were replaced. 

Zowe SDK version compatibility: 7.0.0-next.202108202027

## Release Notes

Milestone:

Changelog:

## Types of changes

What types of changes does your code introduce to Zowe Explorer?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Updates to Documentation or Tests (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This checklist will be used as reference for both the contributor and the reviewer_

- [x] I have read the [CONTRIBUTOR GUIDANCE](https://github.com/zowe/vscode-extension-for-zowe/wiki/Best-Practices:-Contributor-Guidance) wiki
- [x] PR title follows [Conventional Commits Guidelines](https://www.conventionalcommits.org/en/v1.0.0-beta.2/)
- [x] PR Description is included
- [ ] gif or screenshot is included if visual changes are made
- [x] `yarn workspace vscode-extension-for-zowe vscode:prepublish` has been executed
- [x] All checks have passed (DCO, Jenkins and Code Coverage)
- [ ] I have added unit test and it is passing
- [ ] I have added integration test and it is passing
- [ ] There is coverage for the code that I have added
- [ ] I have tested it manually and there are no regressions found
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any PR dependencies have been merged and published (if appropriate)

## Reminder

After a PR is merged into the `master` branch, create a PR from `master` to the `next` branch resolving any conflicts.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by JillieBeanSim — CHANGES_REQUESTED** [review]
zFTP profiles aren't being recognized at all anymore with this PR.  With zOSMF, the `create new connection` isn't opening the config file and `update profile` & `delete profile` is throwing an error instead of opening the config file.

**Comment by crawr** [comment]
@JillieBeanSim It looks like the error happens when the ftp extension is initialized after the extension has already been activated. This should be fixed in the latest commit. Can you please check again?

**Review by JillieBeanSim — COMMENTED** [review]
@crawr this is awesome! ftp, old style profiles, and update & delete work for both global and workspace config.  Create is working for workspace config opening the config file in the correct location but I don't get that with global config., I click the `+` and select `Create new connection` then nothing happens

I wonder if it has something to do with being in a workspace folder but not having a team config, let me try something.

**Comment by crawr** [comment]
> @crawr this is awesome! ftp, old style profiles, and update & delete work for both global and workspace config. Create is working for workspace config opening the config file in the correct location but I don't get that with global config., I click the `+` and select `Create new connection` then nothing happens
> 
> I wonder if it has something to do with being in a workspace folder but not having a team config, let me try something.

Thanks for checking this use case. :smile: I added a check to handle this. If the config file is present in the workspace, open it. Otherwise, it will open the global config during `+ Create new connection`

**Review by JillieBeanSim — APPROVED** [review]
LGTM now, thanks @crawr !!!

**Comment by JillieBeanSim** [comment]
@crawr are we going to do something with the broken 16x tests?

**Review by jellypuno — APPROVED** [review]

**Pull request merged**
