### PR TITLE
Fix vulnerabilities

### PR DESCRIPTION
**Pull request by zFernand0**

### CODE REVIEW

**Comment by phaumer** [comment]
@Colin-Stone was `"@brightside/imperative"` removed by accident from package.json as that now causes linting errors wherever it is used?

**Comment by zFernand0** [comment]
Hey @phaumer,
The reason why we are able to remove `imperative` is because we are able to pull those packages directly from the `@brightside/core` dependencies.
I may be wrong though. I will double check this in a second. Apologies for the confusion.

**Comment by phaumer** [comment]
For example in `USSTree.ts` I get the "no indirect imports" linting error for `import { IProfileLoaded, Logger } from "@brightside/core";`.

**Comment by zFernand0** [comment]
> @Colin-Stone was `"@brightside/imperative"` removed by accident from package.json as that now causes linting errors wherever it is used?

Please see https://github.com/zowe/vscode-extension-for-zowe/pull/288

**Pull request merged**
