### PR TITLE
1.19 to next (2nd go)

### PR DESCRIPTION
**Pull request by katelynienaber**
## Proposed changes

Merge 1.19.0 changes into next branch for testing purposes.

### CODE REVIEW

**Comment by katelynienaber** [comment]
@JillieBeanSim Would you have any idea how to fix the failing tests here? It has to do with an NPM version it seems...

**Comment by JillieBeanSim** [comment]
> @JillieBeanSim Would you have any idea how to fix the failing tests here? It has to do with an NPM version it seems...

@katelynienaber it looks like with the bringing in of master branch you are also bringing in the node 12 tests which are removed in the next branch as Node 10 is not supported anymore.

**Comment by JillieBeanSim** [comment]
removed the node 10 from GHA tests as well as node 16 like done in #1472 https://github.com/zowe/vscode-extension-for-zowe/blob/e9fb19d9e864494177dbcfa0b939ea7152ac4a13/.github/workflows/zowe-explorer-ci.yml#L19

**Review by JillieBeanSim — COMMENTED** [review]
~most new functionality is working well, I do see that the FTP profile is not validating though. This is with old style profiles and if config file is created via cli and includes FTP. @lauren-li @tiantn~
UPDATE: My bad, I forgot to package and install the FTP extension from this branch, all is working!

Another thing I see that could be a separate issue/PR would be that `Issue TSO Command` isn't recognizing the TSO profile information like acct number from the config file.

**Review by JillieBeanSim — APPROVED** [review]
Thanks @katelynienaber for putting this together to update next with the most recent changes.  I will create the issue for the TSO stuff I noticed.

**Review by crawr — APPROVED** [review]
LGTM. Thanks @katelynienaber 

I did find an issue in the `next` branch where the Job ID link does not work unless a search has already been performed on the profile. But this also exists outside of this PR so I will file a separate issue.

**Pull request merged**
